spidernet-io/spiderpool

.github/workflows/build-base-image.yaml
=> fix building base image

.github/workflows/lint-golang.yaml, .github/workflows/robot-update-changelog.yaml
=> opt workflow for workflow

.github/dependabot.yaml, .github/labels.yml
=> add dependabot

.github/dependabot.yml
=> limit dependabot pr

.github/workflows/auto-release.yaml, .github/workflows/build-ci-image.yaml, .github/workflows/release-chart.yaml, charts/Makefile, charts/spiderpool/.helmignore, charts/spiderpool/Chart.yaml, charts/spiderpool/LICENSE, charts/spiderpool/README.md, charts/spiderpool/templates/NOTES.txt, charts/spiderpool/templates/_helpers.tpl, charts/spiderpool/templates/configmap.yaml, charts/spiderpool/templates/daemonset.yaml, charts/spiderpool/templates/deployment.yaml, charts/spiderpool/templates/pdb.yaml, charts/spiderpool/templates/service.yaml, charts/spiderpool/templates/serviceaccount.yaml, charts/spiderpool/values.yaml, cmd/spiderpool-agent/main.go, cmd/spiderpool-controller/main.go, cmd/spiderpool/main.go
=> charts and chart repo

docs/charts/index.html, docs/index.html
=> add html for test

.github/workflows/auto-release.yaml, .github/workflows/build-beta-image.yaml, .github/workflows/build-ci-image.yaml, .github/workflows/build-release-image.yaml, Makefile.defs, charts/Makefile, images/Makefile, images/spiderpool-agent/Dockerfile, images/spiderpool-controller/Dockerfile
=> update building image

pkg/lock/lock_debug_test.go, pkg/lock/lock_fast_test.go, pkg/lock/lock_suite_test.go
=> unitest for lock pkg

charts/spiderpool/values.yaml
=> change chart define

README.md
=> coverage badge

README.md
=> quality badge

.github/workflows/lint-golang.yaml
=> check build

.gitbook.yaml
=> gitbook confing

.github/workflows/build-image-ci.yaml
=> token for workflow

.github/workflows/build-image-base.yaml, .github/workflows/build-image-ci.yaml, .github/workflows/call-release-image.yaml
=> token for push image

.github/ISSUE_TEMPLATE/feature_request.md, .github/codespell-config, .github/codespell-ignorewords, .github/labels.yml, .github/workflows/auto-release.yaml, .github/workflows/call-lint-chart.yaml, .github/workflows/pr-label-check.yaml, Makefile, charts/spiderpool/values.yaml, docs/README.md, docs/cmdref/spiderpool-controller.md, docs/cmdref/spiderpoolctl.md, docs/contributing/development/changelog.md, docs/contributing/development/daily_build.md, docs/contributing/development/github_pages.md, docs/contributing/development/pullrequest.md, pkg/ippoolmanager/README.md, pkg/workloadendpointmanager/README.md
=> workflow spell

.github/codespell-config, .github/workflows/lint-spell.yaml
=> lint spell

.github/workflows/ci-image-gc-by-pr.yaml
=> fix workflow

Makefile
=> fix makefile for CI

.github/.spelling, Makefile, docs/contributing/development/pullrequest.md
=> add label check for test file

charts/spiderpool/Chart.yaml, charts/spiderpool/templates/daemonset.yaml, charts/spiderpool/templates/deployment.yaml, charts/spiderpool/values.yaml, images/spiderpool-agent/Dockerfile, images/spiderpool-controller/Dockerfile
=> fix charts

.github/workflows/lint-golang.yaml
=> ci: check go sdk

.github/workflows/lint-golang.yaml
=> check openapi sdk

.github/.spelling, .github/workflows/lint-golang.yaml
=> check test label

.github/workflows/build-image-ci.yaml, .github/workflows/lint-golang.yaml, .github/workflows/lint-license.yaml, .github/workflows/lint-spell.yaml
=> fix sha for push case

.github/workflows/call-lint-chart.yaml
=> workflow, ignore ct --check-version-increment

codecov.yml, docs/contributing/development/roadmap.md
=> low coverage target

.github/workflows/auto-nightly-ci.yaml
=> fix auto-nightly-ci timeout

.github/workflows/build-image-ci.yaml
fix build-iamge-ci yaml format
=> fix build-iamge-ci yaml format

.github/workflows/auto-nightly-ci.yaml
=> optimize smoke ci

.github/workflows/auto-nightly-ci.yaml
=> optimize e2e

.github/workflows/lint-golang.yaml
=> opt workflow

test/Makefile, test/Makefile.defs, test/scripts/install-multus.sh, test/scripts/prepare.sh, test/yamls/multus-daemonset-thick-plugin.yml
=> add multus ci smoke

.github/.spelling, .gitignore, Makefile, docs/contributing/development/test.md, test/Makefile, test/Makefile.defs, test/scripts/cni-install.sh, test/scripts/install-tools.sh, test/scripts/prepare.sh
=> check tools

.gitignore, Makefile, test/Makefile, test/Makefile.defs, test/scripts/install-macvlan.sh, test/scripts/install-multus.sh, test/scripts/install-tools.sh, test/scripts/install-whereabouts.sh, test/scripts/prepare.sh, test/yamls/multus-daemonset-thick-plugin.tmpl
=> optimise e2e

.github/.spelling, .github/workflows/status.yaml, test/doc/performance.md, test/doc/testippool.md, test/e2e/framework/const.go, test/e2e/ippool/pod_test.go, tools/scripts/e2ecover.sh
=> update e2e status

cmd/spiderpool-agent/cmd/config.go, cmd/spiderpool-agent/cmd/daemon.go, cmd/spiderpool/cmd/cmd_suite_test.go, cmd/spiderpool/cmd/command_test.go, pkg/cmdgenmd/cmd_generate_markdown.go
fix 'unix socket path address already in use' bug
https://github.com/spidernet-io/spiderpool/issues/200
=> fix unix socket path already listen bug

CODEOWNERS, tools/scripts/e2ecover.sh
=> update e2e cal

.github/PULL_REQUEST_TEMPLATE/pull_request_template.md, .golangci.yaml
=> update pr template

test/doc/performance.md, test/doc/reliability.md, test/doc/testippool.md
add e2e test cases to markdown
continue to supplement
=> add e2e test cases to markdown

.github/workflows/status.yaml, README.md, tools/scripts/todocover.sh
=> calculate todo number

.github/workflows/build-image-ci.yaml, .github/workflows/lint-golang.yaml, cmd/spiderpool-agent/cmd/command_shutdown.go, cmd/spiderpool-agent/cmd/daemon.go, cmd/spiderpool-agent/cmd/health.go, cmd/spiderpool-agent/cmd/ipam.go, cmd/spiderpool-agent/cmd/runtime_status.go, cmd/spiderpool-controller/cmd/command_shutdown.go, cmd/spiderpool-controller/cmd/command_status.go, cmd/spiderpool-controller/cmd/controller_manager.go, cmd/spiderpool-controller/cmd/daemon.go, cmd/spiderpool-controller/cmd/runtime_status.go, docs/contributing/development/pullrequest.md, tools/scripts/todocover.sh
=> check TODO comment

Makefile.defs, test/Makefile, test/Makefile.defs, test/scripts/install-whereabouts.sh, test/scripts/prepare.sh
---
---
---
add e2e-test  arm support
None
`make clean` it doesn't work in mac, Since `xargs: illegal option -- i`
Signed-off-by: cyclinder qifeng.guo@daocloud.io
=> add e2e-test arm64 support

go.mod, test/e2e/common/pod.go, test/e2e/common/tools.go, test/e2e/ippool/namespace_test.go
test ip gc after namespace is deleted
=> case E00008 test ip gc after namespace is deleted

go.mod, go.sum, test/e2e/common/daemonset.go, test/e2e/ippool/daemonset_pod_test.go, vendor/github.com/spidernet-io/e2eframework/framework/daemonset.go, vendor/modules.txt
=> add daemonset E00004

test/e2e/common/replicaset.go, test/e2e/ippool/replicaset_pod_test.go
add replicaset e2e test (E00006)
=> add replicaset e2e test (E00006)

.github/workflows/auto-nightly-ci.yaml
=> run all e2e when e2e updated

.github/workflows/auto-nightly-ci.yaml, .github/workflows/status.yaml
=> fix ci bug

Makefile, docs/contributing/development/test.md, test/Makefile, test/Makefile.defs
=> update e2e markdown

cmd/spiderpool/cmd/command_add.go, cmd/spiderpool/cmd/command_delete.go, cmd/spiderpool/cmd/command_test.go
=> add unit test case for plugin

go.mod, go.sum, test/doc/reliability.md, test/e2e/common/pod.go, test/e2e/ippool/namespace_test.go, test/e2e/ippool/pod_test.go, test/e2e/reliability/reliability_suite_test.go, test/e2e/reliability/reliability_test.go, vendor/github.com/spidernet-io/e2eframework/framework/daemonset.go, vendor/github.com/spidernet-io/e2eframework/framework/deployment.go, vendor/github.com/spidernet-io/e2eframework/framework/error.go, vendor/github.com/spidernet-io/e2eframework/framework/namespace.go, vendor/github.com/spidernet-io/e2eframework/framework/pod.go, vendor/github.com/spidernet-io/e2eframework/framework/replicaset.go, vendor/github.com/spidernet-io/e2eframework/framework/statefulset.go, vendor/modules.txt
case R00002 create pod when etcd is unstable
=> case R00002 create pod when etcd is unstable

cmd/spiderpool/cmd/command_test.go
=> solve merge conflict

go.mod, go.sum, test/e2e/common/constant.go, test/e2e/performance/ippool_perf_test.go, test/e2e/performance/performance_suite_test.go, vendor/github.com/spidernet-io/e2eframework/framework/pod.go, vendor/github.com/spidernet-io/e2eframework/framework/statefulset.go, vendor/modules.txt
add performance test case for spiderpool
=> add performance test case for spiderpool

.github/workflows/auto-nightly-ci.yaml
=> optimize ci

.github/workflows/auto-clean-image.yaml, .github/workflows/auto-nightly-ci.yaml, .github/workflows/auto-release.yaml, .github/workflows/build-image-beta.yaml, .github/workflows/build-image-release.yaml, .github/workflows/call-release-changelog.yaml, .github/workflows/call-release-chart.yaml, .github/workflows/call-release-doc.yaml
=> fix CI bug of creating PR

.github/workflows/auto-nightly-ci.yaml, charts/spiderpool/values.yaml
=> ci bug for triggering e2e

.github/.spelling, .github/workflows/auto-nightly-ci.yaml, README.md, docs/develop/test.md, test/Makefile, test/Makefile.defs, test/e2e/ippool/statefulset_test.go, test/scripts/install-multus.sh, test/scripts/installTestPod.sh, test/yamls/kind-config.tmpl, test/yamls/multus-daemonset-thick-plugin.tmpl
=> e2e support ipv4, ipv6 and dual-stack

codecov.yml
=> codecov: change patch coverage

test/e2e/common/job.go, test/e2e/ippool/ippool_suite_test.go, test/e2e/ippool/job_pod_test.go
=> add job e2e test (E00005)

.github/workflows/auto-nightly-ci.yaml, README.md, test/Makefile, test/Makefile.defs, test/scripts/install-multus.sh, test/yamls/kind-config.tmpl, test/yamls/multus-daemonset-thick-plugin.tmpl
e2e: add bridge cni for service traffic
=> e2e: add bridge cni for service traffic

test/doc/performance.md
=> add case for batch ippool

test/e2e/ippool/job_pod_test.go
=> modify job e2e case E00005

go.mod, go.sum, test/e2e/performance/performance_test.go, test/e2e/reclaim/reclaim_test.go, vendor/github.com/spidernet-io/e2eframework/framework/namespace.go, vendor/github.com/spidernet-io/e2eframework/framework/pod.go, vendor/modules.txt
case G00002 delete same-name pod in different namespace
=> case G00002 delete same-name pod in different namespace

go.mod, go.sum, test/e2e/annotation/annotation_suite_test.go, test/e2e/assignip/assiginip_suite_test.go, test/e2e/assignip/assignip_test.go, test/e2e/cli/cli_suite_test.go, test/e2e/common/constant.go, test/e2e/common/spiderpool.go, test/e2e/configmap/configmap_suite_test.go, test/e2e/editcrd/editcrd_suite_test.go, test/e2e/ippool/ippool_suite_test.go, test/e2e/ippool/job_pod_test.go, test/e2e/metric/metric_suite_test.go, test/e2e/performance/performance_suite_test.go, test/e2e/reclaim/reclaim_suite_test.go, test/e2e/reliability/reliability_suite_test.go, test/e2e/reservedip/reservedip_suite_test.go, vendor/github.com/spidernet-io/e2eframework/framework/configmap.go, vendor/github.com/spidernet-io/e2eframework/framework/framework.go, vendor/modules.txt
=> e2e: add spiderpool api

go.mod, go.sum, test/e2e/annotation/annotation_test.go, test/e2e/assignip/assignip_test.go, test/e2e/common/constant.go, test/e2e/common/pod.go, vendor/github.com/spidernet-io/e2eframework/framework/configmap.go, vendor/github.com/spidernet-io/e2eframework/framework/events.go, vendor/modules.txt
add test case A00003: fail to run a pod with invalid annotations
=> add test case A00003

test/e2e/common/spiderpool.go
add GetNamespaceDefaultIppool api
=> add GetNamespaceDefaultIppool api

test/e2e/common/spiderpool.go
add api create/delete ippool for spiderpool
=> add api create/delete ippool for spiderpool

api/v1/agent/models/ip_config.go, api/v1/agent/openapi.yaml, api/v1/agent/server/embedded_spec.go, charts/spiderpool/crds/spiderpool.spidernet.io_ippools.yaml, charts/spiderpool/crds/spiderpool.spidernet.io_workloadendpoints.yaml, cmd/spiderpool-agent/cmd/crd_manager.go, cmd/spiderpool-agent/cmd/daemon.go, cmd/spiderpool-agent/cmd/ipam.go, pkg/ipam/ipam.go, pkg/ippoolmanager/ippool_manager.go, pkg/k8s/apis/v1/ippool_types.go, pkg/k8s/apis/v1/workloadendpoint_types.go, pkg/k8s/apis/v1/zz_generated.deepcopy.go, pkg/logutils/log.go, pkg/logutils/log_test.go, pkg/namespacemanager/namespace_manager.go, pkg/nodemanager/node_manager.go, pkg/podmanager/pod_manager.go, pkg/reservedipmanager/reservedip_manager.go, pkg/workloadendpointmanager/workloadendpoint_manager.go, test/e2e/performance/performance_test.go
- Roll back allocated IP when Allocate() failed.
- Add backbone code to release IP.
=> ipam:Add code to release IP

go.mod, go.sum, test/e2e/annotation/annotation_test.go, test/e2e/common/constant.go, test/e2e/common/spiderpool.go, test/e2e/common/tools.go, test/e2e/performance/performance_test.go, vendor/github.com/spidernet-io/e2eframework/framework/deployment.go, vendor/github.com/spidernet-io/e2eframework/framework/node.go, vendor/github.com/spidernet-io/e2eframework/framework/pod.go, vendor/modules.txt
case name:
it fails to run a pod with different VLAN for ipv4 and ipv6 ippool
=> add test case A00001 for spiderpool

charts/spiderpool/Chart.yaml, charts/spiderpool/templates/daemonset.yaml, charts/spiderpool/templates/deployment.yaml, cmd/spiderpool-agent/cmd/command_daemon.go, cmd/spiderpool-agent/cmd/config.go, cmd/spiderpool-controller/cmd/command_daemon.go, cmd/spiderpool-controller/cmd/config.go, cmd/spiderpool-controller/cmd/crd_manager.go, cmd/spiderpool-controller/cmd/http_server.go
=> Update Spiderpool-controller env args

.github/.spelling, docs/usage/annotation.md
=> doc:Add doc annotation.md

docs/mkdocs.yml
=> update webui theme

test/e2e/annotation/annotation_test.go
the 'ippools' annotation has the higher priority over the 'ippool' annotation
=> E2E: add case A00005 for spiderpool

docs/usage/annotation.md, docs/usage/config.md, docs/usage/select-ippool.md
=> docs:Add docs select-ippool.md

test/e2e/annotation/annotation_test.go, test/e2e/assignip/assignip_test.go, test/e2e/common/constant.go, test/e2e/common/spiderpool.go, test/e2e/common/tools.go
E00015 fail to run a pod when IP resource of an ippool is exhausted
=> E2E: E00015 fail to run a pod when IP resource of an ippool is exhausted

charts/spiderpool/crds/spiderpool.spidernet.io_ippools.yaml, pkg/k8s/apis/v1/ippool_types.go
=> fix:Typo namespaceSelector

.github/workflows/auto-nightly-ci.yaml, .github/workflows/auto-pr-ci.yaml, .github/workflows/call-ci.yaml
=> ci: seperate e2e ci

test/e2e/common/tools.go, vendor/github.com/onsi/gomega/gbytes/buffer.go, vendor/github.com/onsi/gomega/gbytes/io_wrappers.go, vendor/github.com/onsi/gomega/gbytes/say_matcher.go, vendor/github.com/onsi/gomega/gexec/build.go, vendor/github.com/onsi/gomega/gexec/exit_matcher.go, vendor/github.com/onsi/gomega/gexec/prefixed_writer.go, vendor/github.com/onsi/gomega/gexec/session.go, vendor/modules.txt
=> add execCommand

test/e2e/reliability/reliability_test.go
E2E add R00001/R00004 reliability about spiderpool component
=> E2E add R00001/R00004 reliability about spiderpool component

cmd/spiderpool/cmd/cni_types.go, cmd/spiderpool/cmd/command_test.go, cmd/spiderpool/main.go
=> add multiple cni version support

test/e2e/annotation/annotation_test.go
the namespace annotation has precedence over global default ippool
=> E2E: add smoke test case A00006 for namespace annotations

api/v1/agent/models/ipam_add_args.go, api/v1/agent/openapi.yaml, api/v1/agent/server/embedded_spec.go, charts/spiderpool/templates/daemonset.yaml, charts/spiderpool/values.yaml, cmd/spiderpool/cmd/cni_types.go, cmd/spiderpool/cmd/command_add.go, pkg/ipam/ipam.go, test/scripts/install-multus.sh
=> ipam:Add default IP pools at CNI network configuration level

.github/workflows/auto-nightly-ci.yaml, .github/workflows/auto-pr-ci.yaml, .gitignore, Makefile, charts/spiderpool/values.yaml, docs/develop/test.md, images/spiderpool-agent/Dockerfile, images/spiderpool-base/Dockerfile, images/spiderpool-controller/Dockerfile, test/Makefile, test/Makefile.defs, test/scripts/debugEnv.sh
=> ci: print log

go.mod, go.sum, test/e2e/common/pod.go, test/e2e/ippool/job_pod_test.go, test/e2e/reclaim/reclaim_test.go, vendor/github.com/spidernet-io/e2eframework/framework/deployment.go, vendor/github.com/spidernet-io/e2eframework/framework/node.go, vendor/github.com/spidernet-io/e2eframework/framework/pod.go, vendor/github.com/spidernet-io/e2eframework/tools/tools.go, vendor/modules.txt
=> E2E: fix api CheckPodListIpReady

pkg/ipam/ipam.go
=> fix:Failed to correctly filter IP pool

cmd/spiderpool-controller/cmd/daemon.go, pkg/gcmanager/scanAll_IPPool.go, pkg/gcmanager/tracePod_worker.go
=> improve ip gc

.github/workflows/auto-nightly-ci.yaml, .github/workflows/auto-pr-ci.yaml, Makefile, go.mod, go.sum, images/spiderpool-agent/Dockerfile, images/spiderpool-base/Dockerfile, test/e2e/performance/performance_test.go, test/e2e/reclaim/reclaim_test.go, test/e2e/reliability/reliability_test.go, vendor/github.com/spidernet-io/e2eframework/framework/pod.go, vendor/modules.txt
=> e2e: fix bug for R00002

test/e2e/reliability/reliability_test.go
=> E2E:fix ci for spiderpool

go.mod, go.sum, vendor/github.com/spidernet-io/e2eframework/framework/pod.go, vendor/modules.txt
=> E2E:update go.mod for E2E CI BUG

test/doc/annotation.md, test/doc/assignip.md, test/doc/configmap.md, test/doc/editcrd.md, test/doc/ippoolcr.md, test/doc/labelselector.md, test/doc/performance.md, test/doc/reclaim.md, test/doc/reliability.md, test/doc/reservedip.md
- added some test cases for spiderpool 
- update the completion status of the test case
the following cases have been added to this pr.
- S00003 
- L00007  
- R00007 
- A00007
- L00008
- L00009
Fixes #
complement test cases according to the latest development documentation.
People who need attention:
Everyone at spiderpool
```
form：yangwei`s docs https://dwiki.daocloud.io/pages/viewpage.action?pageId=126292327
```
=> E2E:Add some test cases for Spiderpool

test/scripts/debugEnv.sh
=> ci: add more debug information

.github/.spelling, README.md
Improve the text for easy readability.
/kind documentation
/kind cleanup
/language en
=> [docs] improve README.md

test/e2e/assignip/assignip_test.go, test/e2e/labelselector/labelselector_suite_test.go
- synchronize e2e case label with e2e case doc for spiderpool
Fixes #
Based on the latest e2e doc
```
https://github.com/spidernet-io/spiderpool/tree/main/test/doc
```
=> E2E:Synchronize e2e case label with e2e case doc for spiderpool

test/scripts/debugEnv.sh
=> ci: print previous log

test/scripts/makeNodeMacvlan.sh
=> ci: fix gateway for makeNodeMacvlan

pkg/limiter/limiter_suite_test.go, pkg/limiter/queue.go, pkg/limiter/queue_test.go
=> feat:Add pkg limiter

.github/.spelling, README.md, charts/spiderpool/values.yaml, docs/usage/demo.md, docs/usage/install.md
fix https://github.com/spidernet-io/spiderpool/issues/352
=> doc: fix readme

test/Makefile, test/scripts/debugEnv.sh
=> ci: add some debug log

test/e2e/annotation/annotation_suite_test.go, test/e2e/annotation/annotation_test.go, test/e2e/common/spiderpool.go
- add test case A00004 for spiderpool
- Integrating annotation priority-related test cases
Fixes #
case description：the pod annotation has the highest priority over namespace and global default ippool
```
https://github.com/spidernet-io/spiderpool/tree/main/test/doc
```
=> E2E:add test case A00004 for spiderpool

docs/usage/install.md
=> doc: install

charts/spiderpool/templates/configmap.yaml
=> charts: optimize configmap

pkg/gcmanager/scanAll_IPPool.go, pkg/workloadendpointmanager/workloadendpoint_manager.go
=> improve IPPool IP GC when containerID is different with WEP current

test/doc/annotation.md
- add e2e case A00008 for spiderpool
Fixes #234 
- New use case
```
None
```
=> E2E: add case A00008 for fix issue #234

test/e2e/common/deployment.go, test/e2e/common/reservedip.go, test/e2e/reservedip/reservedip_test.go
- add test case S00001 for spiderpool
Fixes #
case description：an IP who is set in ReservedIP CRD, should not be assigned to a pod
```
https://github.com/spidernet-io/spiderpool/tree/main/test/doc
```
=> E2E: add test case S00001 for spiderpool

.github/workflows/auto-nightly-ci.yaml, .github/workflows/auto-pr-ci.yaml
=> workflow: retention-days of artifact

pkg/ipam/tools.go
Owing to the variable version has defined within one time, I reassign a new version variable in each branch of if to handle the address conflict.
=>  Fixed the address conflict in pkg/ipam/tool.go

pkg/ipam/tools.go
=> Fixed variable which share the same address in pkg/ipam/tool.go

pkg/limiter/queue.go
=> limter pkg: avoid unnecessary wait

.github/workflows/auto-release.yaml, .github/workflows/call-release-chart.yaml, .github/workflows/call-release-doc.yaml, .github/workflows/call-update-githubpages.yaml, test/e2e/reliability/reliability_test.go
=> github action: submit charts to github pages

.github/workflows/auto-release.yaml, .github/workflows/call-lint-chart.yaml, .github/workflows/call-release-changelog.yaml, .github/workflows/call-release-chart.yaml, .github/workflows/ci-image-gc-by-pr.yaml, .github/workflows/pr-label-assign.yaml, .github/workflows/pr-label-check.yaml
=> workflow: comment

.github/workflows/auto-version-release.yaml
=> workflow: fix badge

README.md
=> readme: badge

.github/.spelling, docs/usage/statefulset.md
=> add statefulset support markdown

test/e2e/reliability/reliability_test.go
fix eventually for R00006
#474 #458 
Please hold off on the review, I need to reproduce this issue several times with the help of CI and if the issue is fixed correctly I will submit it for review.
=> E2E: fix eventually for R00006

docs/usage/install.md
=> docs: fix some install steps

CODEOWNERS
=> add owner of doc

cmd/spiderpool-agent/cmd/config.go, cmd/spiderpool-agent/cmd/daemon.go, cmd/spiderpool-agent/cmd/runtime_status.go, cmd/spiderpool-controller/cmd/config.go, cmd/spiderpool-controller/cmd/daemon.go, cmd/spiderpool-controller/cmd/http_server.go, cmd/spiderpool-controller/cmd/runtime_status.go, go.mod
=> add startup probe for spiderpool agent&controller

.github/.spelling, test/doc/annotation.md, test/doc/assignip.md, test/doc/cli.md, test/doc/configmap.md, test/doc/ippoolcr.md, test/doc/labelselector.md, test/doc/metric.md, test/doc/performance.md, test/doc/reclaim.md, test/doc/reliability.md, test/doc/reservedip.md
=> [docs] updated test docs

test/e2e/common/spiderpool.go, test/e2e/ippool/job_pod_test.go, test/e2e/ippoolcr/ippoolcr_test.go, test/e2e/reliability/reliability_test.go
E2E:add case D00006 batch create and delete ippool
https://github.com/spidernet-io/spiderpool/pull/410 have closed
=> E2E:add case  batch create and delete ippool（D00006 and D00004）

docs/README.md, docs/concepts/arch.md, docs/mkdocs.yml
https://github.com/spidernet-io/spiderpool/issues/518
=> Change Docs Order

README.md, cmd/spiderpool-controller/cmd/runtime_status.go, pkg/ippoolmanager/ippool_webhook.go
use webhook http connection check as k8s readiness and liveness probe
=> add readiness and liveness probe for spider controller

test/e2e/reservedip/reservedip_test.go
- add e2e case S00003 for spiderpool
Fixes #
- Case Description: Failed to set same IP in excludeIPs when an IP is assigned to a pod
```
None
```
=> E2E: add e2e case S00003 for spiderpool

.github/.spelling, docs/cmdref/spiderpool-agent.md, docs/cmdref/spiderpool-controller.md, docs/cmdref/spiderpoolctl.md, docs/concepts/allocation.md, docs/concepts/annotation.md, docs/concepts/arch.md, docs/concepts/gc.md, docs/develop/pullrequest.md
Signed-off-by: windsonsea <haifeng.yao@daocloud.io>
Fix some grammar issues about writing.
=> [docs] updated several files about grammar

test/e2e/annotation/annotation_test.go
- add e2e case A00008 for spiderpool
Fixes #
- Case Description: Successfully run an annotated multi-container pod
```
None
```
=> E2E: add test case A00008 for spiderpool

charts/spiderpool/crds/spiderpool.spidernet.io_spiderippools.yaml, charts/spiderpool/crds/spiderpool.spidernet.io_spiderreservedips.yaml, charts/spiderpool/templates/webhook.yaml, cmd/spiderpool-agent/cmd/daemon.go, cmd/spiderpool-controller/cmd/daemon.go, pkg/ip/ips.go, pkg/ippoolmanager/ippool_validate.go, pkg/ippoolmanager/ippool_webhook.go, pkg/k8s/apis/v1/ippool_types.go, pkg/k8s/apis/v1/reservedip_types.go, pkg/reservedipmanager/reservedip_manager.go, pkg/reservedipmanager/reservedip_validate.go, pkg/reservedipmanager/reservedip_webhook.go
- Add mutating and validating webhook for ReserverdIP.
- Add IsIPRangeOverlap function in ip pkg to verify whether IPRanges overlap.
- Verify whether each IPRange in 'ips' or 'excludeIPs' field of IPPool overlaps.
=> feat:Add webhook for ReservedIP

.github/workflows/call-lint-chart.yaml, charts/spiderpool/templates/tls.yaml, charts/spiderpool/templates/webhook.yaml, charts/spiderpool/values.yaml, docs/usage/install.md, test/Makefile
=> change tls name of chart values

docs/develop/changelog.md, docs/usage/ippool-affinity-pod.md
Signed-off-by: michelle.wu <michelle.wu@daocloud.io>
about: correct some grammar errors in docs
=> correct grammatical errors

.github/workflows/call-lint-chart.yaml, charts/spiderpool/Chart.yaml
=> workflow: check chart version

test/doc/labelselector.md, test/e2e/labelselector/labelselector_test.go
case L00007: Succeed to run deployment/pod who is cross-zone deployment with matched nodeSelector
=> E2E: case L00007 Succeed to run daemonSet/pod who is cross-zone daemonSet with matched nodeSelector

pkg/limiter/queue.go
=> fix:Limiter holds lock for too long

charts/spiderpool/LICENSE, charts/spiderpool/values.yaml
=> chart: new tolerations for agent

.github/workflows/auto-nightly-ci.yaml, .github/workflows/auto-pr-ci.yaml, .github/workflows/call-lint-chart.yaml, test/Makefile, test/Makefile.defs, test/yamls/kind-config.tmpl
=> e2e: use latest k8s version

cmd/spiderpool/cmd/cni_types.go, cmd/spiderpool/cmd/command_add.go, cmd/spiderpool/cmd/command_delete.go, cmd/spiderpool/cmd/utils.go, docs/concepts/config.md, pkg/logutils/log.go, pkg/logutils/log_test.go
=> fix ipam default log file

.github/workflows/lint-codeowners.yaml, .github/workflows/lint-markdown.yaml
=> workflow typo

.github/workflows/update-chart-readme.yml, CODEOWNERS, charts/spiderpool/templates/_helpers.tpl, charts/spiderpool/templates/daemonset.yaml, charts/spiderpool/templates/deployment.yaml, charts/spiderpool/values.yaml, test/Makefile
=> add global.imageRegistry to chart values

.github/workflows/update-chart-readme.yml
=> CI: update chart readme

test/Makefile, test/e2e/labelselector/labelselector_test.go, test/e2e/reclaim/reclaim_test.go, test/e2e/reliability/reliability_test.go
=> E2E: Fixed failed to get masternode when run case L00006

charts/spiderpool/templates/cluster-default-ippool.yaml, charts/spiderpool/templates/webhook.yaml, cmd/spiderpool-agent/cmd/http_server.go, cmd/spiderpool-agent/cmd/runtime_status.go, cmd/spiderpool-agent/cmd/unix_server.go, cmd/spiderpool-controller/cmd/crd_manager.go, cmd/spiderpool-controller/cmd/runtime_status.go, pkg/ippoolmanager/ippool_webhook.go
=> switch webhook health check from L4 to L7

.github/workflows/lint-spell.yaml, .github/workflows/update-chart-readme.yml, charts/spiderpool/templates/deployment.yaml, charts/spiderpool/values.yaml
=> chart: remove values GcEvictedPodPod

docs/usage/statefulset.md
=> fix statefulset markdown format

docs/usage/ipv6.md
=> add IPv6 support usage markdown

go.sum, pkg/gcmanager/scanAll_IPPool.go
=> improve IP GC scan all log format

pkg/ipam/convert.go
=> fix:Parse custom routes defined by Pod annotation panic

test/e2e/annotation/annotation_test.go, test/e2e/assignip/assignip_test.go, test/e2e/ippool/job_pod_test.go, test/e2e/ippoolcr/ippoolcr_test.go, test/e2e/labelselector/labelselector_test.go, test/e2e/performance/performance_test.go, test/e2e/reclaim/reclaim_test.go, test/e2e/reliability/reliability_test.go, test/e2e/reservedip/reservedip_test.go
after createnamespace, we need to check wether is the default serviceAccount ready #446
=> E2E: FIX update CreateNamespace to CrateNamespaceUntilDefaultServiceAccountReady

test/Makefile
=> ci: set --slow-spec-threshold

test/e2e/annotation/annotation_test.go
add case A00002 edit pod annotations about route field
=> E2E: add case A00002 edit pod annotations about route field

charts/spiderpool/templates/webhook.yaml
=> remove validating webhook post-install

.github/.spelling, docs/example/reserved-ip/already-in-use-ippool.yaml, docs/example/reserved-ip/created-by-someone-else-ippool.yaml, docs/example/reserved-ip/not-use-excludeips-ippool.yaml, docs/example/reserved-ip/reservedip-example-deploy.yaml, docs/example/reserved-ip/test-ipv4-ippool.yaml, docs/example/reserved-ip/test-ipv4-reservedip.yaml, docs/example/reserved-ip/use-excludeips-ippool.yaml, docs/usage/reserved-ip.md
=> docs:Update docs reserved-ip.md and add some examples

pkg/election/lease_election.go
=> fix leader election log

docs/example/ippool-multi/dummy-pod.yaml, docs/example/ippool-multi/multi-ippool-example-deploy.yaml, docs/example/ippool-multi/test-ipv4-ippools.yaml, docs/usage/ippool-multi.md
=> docs:Add docs ippool-multi.md

docs/usage/ippool-affinity-namespace.md
=> docs:Add ippool-affinity-namespace.md

docs/usage/ippool-affinity-node.md
=> docs:Add docs ippool-affinity-node.md

docs/example/ippool-namespace/ns1-default-ippool-deploy.yaml, docs/example/ippool-namespace/ns1-default-ipv4-ippool.yaml, docs/example/ippool-namespace/ns1-ippool-selection-patch.yaml, docs/usage/ippool-namespace.md
=> docs:Add docs ippool-namespace.md

docs/usage/cli.md, docs/usage/multi-interfaces-annotation.md, docs/usage/multi-interfaces-cni.md, docs/usage/statefulset.md
=> add multi interfaces docs markdown

charts/spiderpool/templates/daemonset.yaml
delete the old plugin binary in installation
=> improve ipam plugin installation

charts/spiderpool/Chart.yaml
=> chart: typo

Makefile, charts/spiderpool/README.md, charts/spiderpool/templates/_helpers.tpl, charts/spiderpool/templates/cluster-default-ippool.yaml, charts/spiderpool/templates/pod.yaml, charts/spiderpool/templates/role.yaml, charts/spiderpool/templates/role_binding.yaml, charts/spiderpool/templates/serviceaccount.yaml, charts/spiderpool/values.yaml, cmd/spiderpool-init/Makefile, cmd/spiderpool-init/main.go, images/spiderpool-controller/Dockerfile, test/Makefile, test/scripts/debugEnv.sh
pod annotation
```
env:
- name: SPIDERPOOL_INIT_DEFAULT_IPV4_IPPOOL_NAME
value: "default-v4-ippool"
- name: SPIDERPOOL_INIT_DEFAULT_IPV4_IPPOOL_SUBNET
value: "172.16.0.0/16"
- name: SPIDERPOOL_INIT_DEFAULT_IPV4_IPPOOL_IPRANGES
value: "[172.16.0.100-172.16.0.100]"
- name: SPIDERPOOL_INIT_DEFAULT_IPV6_IPPOOL_NAME
value: "default-v6-ippool"
- name: SPIDERPOOL_INIT_DEFAULT_IPV6_IPPOOL_SUBNET
value: "fd00::/64"
- name: SPIDERPOOL_INIT_DEFAULT_IPV6_IPPOOL_IPRANGES
value: "[fd00::10-fd00::100]"
```
=> install default ippool in pod

pkg/ip/ips.go
=> fix:Failed to correctly judge whether the subnets of the two IP pools overlap each other

cmd/spiderpool/cmd/command_add.go, cmd/spiderpool/cmd/command_delete.go
=> improve ipam plugin log

.github/workflows/auto-pr-ci.yaml, test/e2e/performance/performance_test.go
=> ci: do not run time-cost test if possible

tools/k8s-controller-gen/update-controller-gen.sh, tools/scripts/update-codegen.sh
=> Use `trap` to recycle temporary directories and files in code generation scripts

.github/.spelling, pkg/ippoolmanager/ippool_manager.go, pkg/k8s/apis/spiderpool.spidernet.io/v1/spiderippool_types.go, pkg/k8s/apis/spiderpool.spidernet.io/v1/zz_generated.deepcopy.go, test/e2e/affinity/affinity_test.go
/kind pr/release/none-required
#670
=> fix issue 670, Spelling error, should not be NamesapceAffinity but NamespaceAffinity

charts/spiderpool/Chart.yaml
=> chart logo

charts/spiderpool/templates/pod.yaml, cmd/spiderpool-init/cmd/config.go, cmd/spiderpool-init/cmd/k8s.go, cmd/spiderpool-init/cmd/root.go
fix https://github.com/spidernet-io/spiderpool/issues/704
=> fix: failed to install default ippool 

pkg/ip/cidr.go, pkg/ip/ip.go, pkg/ip/iprange.go, pkg/ippoolmanager/ippool_manager.go, pkg/reservedipmanager/reservedip_manager.go
=> Add comments to pkg ip

pkg/gcmanager/pod_cache.go, pkg/gcmanager/scanAll_IPPool.go, pkg/gcmanager/tracePod_worker.go, pkg/ippoolmanager/ippool_webhook.go, pkg/k8s/apis/spiderpool.spidernet.io/v1/types_string.go
=> Add CRD String method

docs/concepts/gc.md
=> explain SpiderIPPool and SpiderEndpoint lifecycle

test/e2e/affinity/affinity_test.go, test/e2e/common/deployment.go, test/e2e/common/namesapce.go
E2E:add case L00009 one IPPool can be used by multiple namespace
=> E2E:add case L00009 one IPPool can be used by multiple namespace

pkg/ipam/ipam.go, pkg/ipam/tools.go
/kind bug
fix IPAM pool selection bug
=> fix pool selection bug and add comments

pkg/k8s/apis/spiderpool.spidernet.io/v1/types_string.go
=> improve crd types string method

.github/workflows/call-lint-chart.yaml, Makefile, charts/Makefile, charts/spiderpool/Chart.yaml, charts/spiderpool/templates/_helpers.tpl
=> rename chart version

.github/workflows/call-lint-chart.yaml
=> workflow: typo

.github/.spelling, test/doc/annotation.md, test/doc/assignip.md, test/doc/cidr.md, test/doc/ippoolcr.md, test/doc/reservedip.md
Signed-off-by: windsonsea <haifeng.yao@daocloud.io>
Help Wei.Yang to update the e2e docs.
=> Updated e2e docs for Wei.Yang

cmd/spiderpool/cmd/command_add.go, cmd/spiderpool/cmd/command_delete.go
=> print stack when recover occurs

cmd/spiderpool/cmd/command_add.go, pkg/ip/cidr.go, pkg/ip/ip.go, pkg/ipam/convert.go, pkg/ippoolmanager/utils.go
=> fix:The gateway in CIDR format passed the validating webhook by mistake

charts/spiderpool/crds/spiderpool.spidernet.io_spiderendpoints.yaml, charts/spiderpool/crds/spiderpool.spidernet.io_spiderippools.yaml, pkg/gcmanager/pod_cache.go, pkg/ipam/ipam.go, pkg/ippoolmanager/ippool_manager.go, pkg/k8s/apis/spiderpool.spidernet.io/v1/spiderendpoint_types.go, pkg/k8s/apis/spiderpool.spidernet.io/v1/spiderippool_types.go, pkg/k8s/apis/spiderpool.spidernet.io/v1/types_string.go, pkg/podmanager/utils.go, pkg/workloadendpointmanager/workloadendpoint_manager.go
=> Add 'OwnerControllerName' field in SpiderIPPool and SpiderEndpoint

README.md, docs/usage/install.md
fix readme,Refer to [demo] have not file to found, and  helm install ipv4_range is not used...
---
---
---
=> readme doc fix

test/e2e/common/spiderpool.go
issue/bug pr/release/none-required
- fix issue 720，Ensuring api robustness
#720
=> fix issue 720 :improve CheckPodIpRecordInIppool

cmd/spiderpool/cmd/command_add.go, cmd/spiderpool/cmd/command_delete.go
=> improve recover log stack

test/e2e/assignip/assignip_test.go
- After removing an IP from IPPool.Spec.excludeIPs, the IP can be assigned to a pod and the record of that pod IP can be checked in the ippool.
#
=> E2E: Supplement to S00002, IPs removed from IPPool.Spec.excludeIPs can be assigned to Pods.

charts/spiderpool/README.md, charts/spiderpool/templates/pod.yaml, charts/spiderpool/values.yaml, cmd/spiderpool-init/cmd/config.go, cmd/spiderpool-init/cmd/k8s.go, cmd/spiderpool-init/cmd/root.go, test/Makefile, test/Makefile.defs
current , it could test with `make e2e_init -e E2E_SPIDERPOOL_ENABLE_SUBNET=true`
```
NAME                VERSION   SUBNET                    FREE-IP-COUNT   TOTAL-IP-COUNT
default-v4-subnet   4         172.19.0.0/16
default-v6-subnet   6         fc00:f853:ccd:e793::/64
NAME                VERSION   SUBNET                    ALLOCATED-IP-COUNT   TOTAL-IP-COUNT   DISABLE
default-v4-ippool   4         172.19.0.0/16             4                    253              false
default-v6-ippool   6         fc00:f853:ccd:e793::/64   4                    253              false
```
=> installation: init subnet

pkg/ippoolmanager/ippool_validate.go, pkg/reservedipmanager/reservedip_validate.go, pkg/subnetmanager/subnet_validate.go
fix https://github.com/spidernet-io/spiderpool/issues/757
=> fix:Compare the pointer of 'spec.ipVersion' field in webhook

cmd/spiderpool-agent/cmd/config.go, cmd/spiderpool-agent/cmd/daemon.go, cmd/spiderpool-agent/cmd/unix_server.go, cmd/spiderpool-controller/cmd/config.go, cmd/spiderpool-controller/cmd/daemon.go, pkg/config/config.go, pkg/gcmanager/gc_manager.go, pkg/gcmanager/scanAll_IPPool.go, pkg/ipam/config.go, pkg/ipam/convert.go, pkg/ipam/ipam.go, pkg/ippoolmanager/config.go, pkg/ippoolmanager/ippool_informer.go, pkg/ippoolmanager/ippool_manager.go, pkg/ippoolmanager/types/interface.go, pkg/limiter/config.go, pkg/limiter/queue.go, pkg/limiter/queue_test.go, pkg/namespacemanager/namespace_manager.go, pkg/nodemanager/node_manager.go, pkg/podmanager/config.go, pkg/podmanager/pod_manager.go, pkg/reservedipmanager/reservedip_manager.go, pkg/reservedipmanager/reservedip_validate.go, pkg/subnetmanager/config.go, pkg/subnetmanager/subnet_manager.go, pkg/subnetmanager/types/interface.go, pkg/types/types.go, pkg/workloadendpointmanager/config.go, pkg/workloadendpointmanager/workloadendpoint_manager.go
=> Refactor configuration related code

test/doc/affinity.md, test/doc/reclaim.md, test/doc/reliability.md, test/e2e/reliability/reliability_test.go
issue/ci-fail pr/release/none-required
-  R00005 is not stable enough to avoid affecting CI, avoid it for now and wait until it is stable enough.
=> Pending case R00005

test/doc/ippoolcr.md, test/e2e/ippoolcr/ippoolcr_test.go
issue/ci-fail pr/release/none-required
-  override PR CI check
#753
=> fix: Add update Ippool case to smoke, override PR CI check

go.mod, go.sum, test/e2e/affinity/affinity_test.go, test/e2e/assignip/assignip_test.go, test/e2e/common/spiderpool.go, test/e2e/ippoolcr/ippoolcr_test.go, test/e2e/reservedip/reservedip_test.go, vendor/github.com/spidernet-io/e2eframework/framework/framework.go, vendor/modules.txt
issue/ci-fail pr/release/none-required
-  Optimised code logic
#713
=> fix issue 713: `UpdatePool` Api method revised to patch

pkg/ip/ip.go, pkg/ippoolmanager/ippool_subnet_validate.go, pkg/ippoolmanager/ippool_validate.go, pkg/ippoolmanager/ippool_webhook.go, pkg/subnetmanager/subnet_manager.go, pkg/subnetmanager/subnet_validate.go, pkg/subnetmanager/types/interface.go
=> Add SpiderSubnet related verification in SpiderIPPool Webhook

test/Makefile
=> test makefile

cmd/spiderpool-controller/cmd/daemon.go, pkg/ipam/ipam.go, pkg/ippoolmanager/ippool_subnet_validate.go, pkg/subnetmanager/config.go, pkg/subnetmanager/subnet_informer.go, pkg/subnetmanager/subnet_manager.go, pkg/subnetmanager/types/interface.go
=> feat:Add the informer of SpiderSubnet

test/doc/affinity.md, test/doc/annotation.md, test/doc/assignip.md, test/doc/cidr.md, test/doc/ippoolcr.md, test/doc/reservedip.md, test/e2e/affinity/affinity_test.go, test/e2e/annotation/annotation_test.go, test/e2e/assignip/assignip_test.go, test/e2e/common/constant.go, test/e2e/common/deployment.go, test/e2e/common/pod.go, test/e2e/common/spiderpool.go, test/e2e/ippoolcr/ippoolcr_test.go, test/e2e/performance/performance_test.go, test/e2e/reclaim/reclaim_test.go, test/e2e/reliability/reliability_test.go, test/e2e/reservedip/reservedip_test.go
issue/ci-fail pr/release/none-required
add test case a00011: Use the ippool route with cleanGateway=false in the pod annotation as a default route
step:
-  1、add cleanGateway=false, cleanGateway=true to the Pod.ippools annotations
-  2、Successful creation of Pod
-  3、When cleanGateway=false, the default route will take effect.
-  4、When cleanGateway=true, the default route will not take effect.
=> E2E：add test case A00011

pkg/ippoolmanager/ippool_subnet_validate.go, pkg/subnetmanager/subnet_informer.go
=> fix:FreeIPs of newly created SpiderSubnet cannot be synchronized automatically

charts/spiderpool/values.yaml
=> chart type

cmd/spiderpool-agent/cmd/config.go, cmd/spiderpool-agent/cmd/daemon.go, cmd/spiderpool-controller/cmd/daemon.go, pkg/ipam/ipam.go, pkg/ippoolmanager/ippool_manager.go, pkg/ippoolmanager/types/interface.go, pkg/subnetmanager/subnet_manager.go
=> fix subnet

tools/scripts/cleanCRD.sh
=> fix: CRD Name mismatch in cleanCRD.sh

pkg/ip/ip.go
=> fromat import

.github/.spelling, docs/example/basic/custom-ippool-deploy.yaml, docs/example/basic/custom-ipv4-ippool.yaml, docs/usage/basic.md, docs/usage/ippool-multi.md
=> docs:Add docs basic.md

pkg/cert/gen.go
Signed-off-by: lou-lan [loulan@loulan.me](mailto:loulan@loulan.me)
Close https://github.com/spidernet-io/spiderpool/issues/775
=> Optimize certificate checking logic

docs/usage/install.md, docs/usage/ippool-affinity-namespace.md, docs/usage/ippool-affinity-node.md, docs/usage/ippool-affinity-pod.md, docs/usage/ippool-multi.md, docs/usage/ippool-namespace.md, docs/usage/ipv6.md, docs/usage/multi-interfaces-annotation.md, docs/usage/multi-interfaces-cni.md, docs/usage/reserved-ip.md, docs/usage/statefulset.md
=> [doc] Updated /usage files

cmd/spiderpool-agent/cmd/daemon.go, pkg/ipam/config.go, pkg/limiter/config.go, pkg/limiter/queue.go, pkg/limiter/queue_test.go
=> Set defaults for limiter config

cmd/spiderpool-agent/cmd/daemon.go, cmd/spiderpool-controller/cmd/config.go, cmd/spiderpool-controller/cmd/daemon.go, pkg/ippoolmanager/config.go, pkg/ippoolmanager/ippool_validate.go, pkg/reservedipmanager/config.go, pkg/reservedipmanager/reservedip_manager.go, pkg/reservedipmanager/reservedip_validate.go, pkg/subnetmanager/config.go, pkg/subnetmanager/subnet_manager.go, pkg/subnetmanager/subnet_validate.go
=> Prohibit to create  IPv4/6 IPPools when IPv4/6 is disabled

cmd/spiderpool-controller/cmd/daemon.go
=> fix:Wrong import

pkg/k8s/apis/spiderpool.spidernet.io/v1/types_string.go, pkg/subnetmanager/deployment_controller.go, pkg/subnetmanager/subnet_controller.go, pkg/subnetmanager/utils.go
bug fix
https://github.com/spidernet-io/spiderpool/blob/0f372705e28db1cad3cd7e118b63e900f06eb313/pkg/subnetmanager/deployment_controller.go#L75
once we use the standard IPAM mode and we changed the deployment replicas, we can also get into the subnet manager logic source codes and meet panic here.
=> fix subnet no pointer bug

.github/workflows/label-syncer.yaml
=> Retain existing labels

test/e2e/common/spiderpool.go, test/e2e/common/spidersubnet.go
add some apis about spidersubnet such as: create, get, delete etc
=> E2E: add some apis about spidersubnet

cmd/spiderpool-controller/cmd/config.go, cmd/spiderpool-controller/cmd/daemon.go, pkg/constant/k8s.go, pkg/event/event.go
=> feat:Add K8s event recorder

charts/spiderpool/templates/tls.yaml, pkg/ippoolmanager/ippool_subnet_validate.go, pkg/ippoolmanager/ippool_webhook.go, pkg/subnetmanager/subnet_informer.go, pkg/subnetmanager/subnet_manager.go, pkg/subnetmanager/subnet_validate.go, pkg/subnetmanager/subnet_webhook.go
=> Cascade delete SpiderSubnet and SpiderIPPools controlled by it

charts/spiderpool/templates/_helpers.tpl
fix https://github.com/spidernet-io/spiderpool/issues/844
=> chart typo

pkg/limiter/queue_test.go
=> test:Add test case for setting defaults when new a Limiter

pkg/lock/lock_debug.go
=> fix:ApplyPodEntry holds the lock for too long

charts/spiderpool/templates/role.yaml, pkg/k8s/apis/spiderpool.spidernet.io/v1/rbac.go
fix https://github.com/spidernet-io/spiderpool/issues/875
=> chart removes role of secret

go.mod, go.sum, vendor/github.com/emicklei/go-restful/.gitignore, vendor/github.com/emicklei/go-restful/.travis.yml, vendor/github.com/emicklei/go-restful/CHANGES.md, vendor/github.com/emicklei/go-restful/Makefile, vendor/github.com/emicklei/go-restful/README.md, vendor/github.com/emicklei/go-restful/container.go, vendor/github.com/emicklei/go-restful/cors_filter.go, vendor/github.com/emicklei/go-restful/curly.go, vendor/github.com/emicklei/go-restful/custom_verb.go, vendor/github.com/emicklei/go-restful/jsr311.go, vendor/github.com/emicklei/go-restful/parameter.go, vendor/github.com/emicklei/go-restful/path_processor.go, vendor/github.com/emicklei/go-restful/request.go, vendor/github.com/emicklei/go-restful/response.go, vendor/github.com/emicklei/go-restful/route.go, vendor/github.com/emicklei/go-restful/route_builder.go, vendor/github.com/emicklei/go-restful/route_reader.go, vendor/github.com/emicklei/go-restful/service_error.go, vendor/github.com/emicklei/go-restful/web_service.go, vendor/modules.txt
fix https://github.com/spidernet-io/spiderpool/issues/873
=> update vendor to fix CVE-2022-1996

.github/codespell-ignorewords, Makefile, images/spiderpool-agent/Dockerfile, images/spiderpool-controller/Dockerfile
=> update base image

charts/spiderpool/templates/daemonset.yaml, charts/spiderpool/templates/deployment.yaml
fix https://github.com/spidernet-io/spiderpool/issues/890
=> chart: remove useless http header

pkg/limiter/queue_test.go, pkg/lock/lock_debug.go, pkg/lock/lock_debug_test.go, pkg/lock/lock_fast_test.go, pkg/lock/lock_suite_test.go
=> test:Add test for pkg lock

cmd/spiderpool-controller/cmd/config.go, cmd/spiderpool-controller/cmd/daemon.go, pkg/ippoolmanager/ippool_manager.go, pkg/ippoolmanager/ippool_subnet_validate.go, pkg/ippoolmanager/ippool_webhook.go, pkg/ippoolmanager/types/interface.go, pkg/reservedipmanager/reservedip_webhook.go, pkg/subnetmanager/subnet_manager.go, pkg/subnetmanager/subnet_webhook.go, pkg/subnetmanager/types/interface.go
=> feat:Add retry mechanism for updating 'status.freeIPs' of SpiderSubnet

pkg/ippoolmanager/ippool_webhook.go, pkg/subnetmanager/subnet_informer.go
=> Add the label of its owner SpiderSubnet name to the SpiderIPPool

pkg/ip/cidr.go, pkg/ippoolmanager/ippool_subnet_validate.go, pkg/ippoolmanager/ippool_validate.go, pkg/reservedipmanager/reservedip_validate.go, pkg/subnetmanager/subnet_validate.go
=> fix:Illegal creation of two SpiderSubnets with the same 'spec.subnet'

cmd/spiderpool-agent/cmd/config.go, cmd/spiderpool-agent/cmd/daemon.go, cmd/spiderpool-controller/cmd/config.go, cmd/spiderpool-controller/cmd/daemon.go, test/Makefile
=> add debug information and set go max procs

docs/usage/install.md, docs/usage/ipv6.md, docs/usage/spider-subnet.md, docs/usage/statefulset.md
docs: fix helm upgrade feature.enableSpiderSubnet
#909
=> Docs: fix helm upgrade feature.enableSpiderSubnet

test/doc/cidr.md
Docs: update test case
#869 
#870
=> Docs: update test case

pkg/ipam/ipam.go, pkg/workloadendpointmanager/workloadendpoint_manager.go
=> fix:Panic when failed to mark an IP allocation

charts/spiderpool/templates/tls.yaml, cmd/spiderpool-controller/cmd/daemon.go, pkg/workloadendpointmanager/workloadendpoint_manager.go, pkg/workloadendpointmanager/workloadendpoint_webhook.go
=> feat:Add mutating webhook for SpiderEndpoint

cmd/spiderpool-controller/cmd/config.go, cmd/spiderpool-controller/cmd/daemon.go, pkg/subnetmanager/config.go, pkg/subnetmanager/subnet_informer.go
=> feat:Enable the RESYNC mechanism of SpiderSubnet Informer

test/e2e/common/spiderpool.go, test/e2e/performance/performance_test.go
=> E2E: strength the e2e case P00002

docs/concepts/annotation.md, docs/concepts/arch.md, docs/concepts/config.md, docs/concepts/gc.md, docs/concepts/metrics.md, docs/concepts/roadmap.md, docs/concepts/spiderendpoint.md, docs/concepts/spiderippool.md, docs/concepts/spiderreservedip.md, docs/concepts/spidersubnet.md
Polish some text in this folder:
```
docs/concepts/
```
=> [docs] updated concept pages

pkg/ippoolmanager/ippool_manager.go, pkg/ippoolmanager/ippool_subnet_validate.go, pkg/ippoolmanager/ippool_validate.go, pkg/reservedipmanager/reservedip_validate.go, pkg/subnetmanager/subnet_validate.go
=> fix:Duplicated codes in ippool_subnet_validate.go

test/e2e/common/spiderpool.go
=> fix:Avoid ci failure, add workload delete judgement logic

pkg/limiter/queue.go, pkg/limiter/queue_test.go
=> test:Add "forgot to start" test to Limiter

pkg/constant/k8s.go, pkg/ipam/utils.go, pkg/types/k8s.go, test/e2e/common/namespace.go
=> Adjust some annotations specifying pool selection rules

pkg/ipam/ipam.go
=> Return the cause of IPPool being filtered when selecting IPPools

pkg/ippoolmanager/ippool_informer.go, pkg/subnetmanager/subnet_informer.go, pkg/subnetmanager/subnet_manager.go
fix some bugs with related issues
https://github.com/spidernet-io/spiderpool/issues/948
https://github.com/spidernet-io/spiderpool/issues/950
=> fix subnet panic bug

charts/spiderpool/Chart.yaml
=> chart version

test/e2e/common/constant.go, test/e2e/common/spidersubnet.go, test/e2e/subnet/subnet_suite_test.go, test/e2e/subnet/subnet_test.go, tools/scripts/e2eperformance.sh
- add test case
- Re-open with original PR of #842 
None
Additional
- Fix some api
- Exporting new badges
=> E2E: add subnet case for spiderpool

pkg/k8s/apis/spiderpool.spidernet.io/v1/types_string.go
=> add SpiderSubnet string method

test/e2e/common/deployment.go, test/e2e/subnet/subnet_test.go
=> E2E: there are enough resources on the node that the deployment pod will eventually run

test/scripts/debugEnv.sh
=> e2e: print detail

pkg/ipam/ipam.go
fix bug
The current IPAM get subnet IPPool candidates may get duplicated IPPools, which will cause one Pod get two IPs.
In this situation, the two allocated IPs owns the same pod name and same container ID and the spiderpool-controller wouldn't gc it.
https://github.com/spidernet-io/spiderpool/issues/963
=> fix ipam get subnet duplicated ippools

cmd/spiderpool-agent/cmd/daemon.go, cmd/spiderpool-controller/cmd/config.go, cmd/spiderpool-controller/cmd/daemon.go, pkg/constant/k8s.go, pkg/event/event.go, pkg/ippoolmanager/ippool_subnet_validate.go, pkg/subnetmanager/subnet_informer.go
=> add event records for SpiderSubnet 

.github/workflows/status.yaml, tools/scripts/e2ecover.sh
=> fix:add e2e coverage

.github/workflows/auto-nightly-ci.yaml, test/Makefile, test/scripts/debugEnv.sh
=> ci: debug error

test/Makefile, test/scripts/debugEnv.sh
=> ci: print debug information

pkg/ippoolmanager/ippool_informer.go, pkg/ippoolmanager/ippool_manager.go, pkg/subnetmanager/subnet_manager.go, pkg/subnetmanager/types/interface.go
---
---
fix bug 
https://github.com/spidernet-io/spiderpool/issues/980
=> fix IPPool scale up but subnet no more IPs issue

pkg/election/lease_election.go
---
log improve
https://github.com/spidernet-io/spiderpool/issues/990
=> improve election log

pkg/gcmanager/scanAll_IPPool.go
=> improve IP GC log

docs/develop/test.md, test/Makefile, test/e2e/annotation/annotation_test.go, test/e2e/assignip/assignip_test.go
fix:the subnet function is switched off and e2e cannot be run.
#987 
=> fix:the subnet function is switched off and e2e cannot be run.

pkg/ipam/ipam.go, pkg/subnetmanager/subnet_informer.go
=> debug:Panic happens occasionally at func allocateIPFromPoolCandidates(...)

.github/.spelling, docs/concepts/annotation.md, docs/concepts/spidersubnet.md, docs/example/spider-subnet/deploy-use-subnet.yaml, docs/example/spider-subnet/subnet-demo.yaml, docs/usage/spider-subnet.md
=> update spider subnet markdown

cmd/spiderpool-controller/cmd/config.go, cmd/spiderpool-controller/cmd/daemon.go, pkg/ippoolmanager/config.go, pkg/ippoolmanager/ippool_informer.go
=> remove workqueue discarding object incase that the event is lost

.github/.spelling, docs/concepts/config.md
=> fix cni configuration file example

charts/spiderpool/README.md, docs/usage/basic.md
=> update readme doc

pkg/ippoolmanager/ippool_informer.go
=> improve spiderpool controller ippool informer log

pkg/constant/errors.go, pkg/ippoolmanager/ippool_informer.go, pkg/ippoolmanager/ippool_manager.go, pkg/ippoolmanager/ippool_subnet_validate.go, pkg/podmanager/pod_manager.go, pkg/subnetmanager/subnet_informer.go, pkg/subnetmanager/subnet_manager.go, test/scripts/debugEnv.sh
fix https://github.com/spidernet-io/spiderpool/issues/974
=> fix panic in AllocateIP() api when allocate IP for pod

pkg/ippoolmanager/ippool_validate.go, pkg/subnetmanager/subnet_validate.go
=> fix:Invalid validation of `spec.ips` and `spec.excludeIPs` fields of SpiderSubnet

pkg/ipam/ipam.go, pkg/ippoolmanager/ippool_manager.go
=> fix:Panic happens occasionally at func allocateIPFromPoolCandidates

test/e2e/common/spidersubnet.go, test/e2e/subnet/subnet_test.go
=> fix: ctx is not used

test/e2e/common/spidersubnet.go
=> fix: api added ip conflict

pkg/ip/errors.go, pkg/ip/route.go, pkg/ipam/utils.go, pkg/ippoolmanager/ippool_informer.go, pkg/ippoolmanager/ippool_manager.go, pkg/ippoolmanager/ippool_subnet_validate.go, pkg/subnetmanager/subnet_informer.go
=> Add format verification to route annotation of Pod

cmd/spiderpool-controller/cmd/config.go, cmd/spiderpool-controller/cmd/daemon.go, pkg/ippoolmanager/ippool_informer.go, pkg/ippoolmanager/ippool_subnet_validate.go, pkg/ippoolmanager/ippool_validate.go, pkg/ippoolmanager/utils.go, pkg/subnetmanager/config.go, pkg/subnetmanager/subnet_informer.go, pkg/subnetmanager/subnet_manager.go, pkg/subnetmanager/types/interface.go
=> Refactor SpiderSubnet controller

pkg/ipam/ipam.go
fix bug
https://github.com/spidernet-io/spiderpool/issues/1020
=> add ipam pool candidate validation for subnet

pkg/ippoolmanager/ippool_informer.go
fix bug
https://github.com/spidernet-io/spiderpool/issues/1031
=> fix subnet cursor data race

charts/spiderpool/crds/spiderpool.spidernet.io_spiderreservedips.yaml, pkg/k8s/apis/spiderpool.spidernet.io/v1/spiderreservedip_types.go, pkg/reservedipmanager/reservedip_validate.go
=> Remove the verification of the array length of the field `spec.ips` of SpiderReservedIP

charts/spiderpool/templates/role.yaml, pkg/k8s/apis/spiderpool.spidernet.io/v1/rbac.go
=> fix:Spiderpool controller lacks permission to patch Event

pkg/subnetmanager/subnet_informer.go
=> fix:When deleting a SpiderSubnet, its finalizer cannot be removed correctly

test/Makefile
=> E2E: update ginkgo function

docs/example/basic/custom-ippool-deploy.yaml, docs/usage/basic.md
=> docs: Update install.md and basic.md

test/e2e/common/constant.go, test/e2e/common/replicaset.go, test/e2e/common/statefulset.go, test/e2e/subnet/subnet_test.go
=> E2E: Automatic creation, extension and deletion of ippool by different controllers

pkg/logutils/log_test.go
=> add logutils unit test

docs/example/reserved-ip/reservedip-deploy.yaml, docs/usage/reserved-ip.md
=> docs: Update reserved-ip.md

test/e2e/subnet/subnet_test.go
=> E2E: add test case related to subnet.spec field validation

test/e2e/affinity/affinity_test.go, test/e2e/annotation/annotation_test.go, test/e2e/common/spiderpool.go, test/e2e/common/tools.go
=> fix: add a retry mechanism for api

docs/example/ippool-affinity-node/master-ipv4-ippool.yaml, docs/example/ippool-affinity-node/node-affinity-deploy.yaml, docs/example/ippool-affinity-node/worker-ipv4-ippool.yaml, docs/example/ippool-multi/dummy-pod.yaml, docs/example/ippool-multi/multi-ippool-deploy.yaml, docs/example/ippool-namespace/ns1-ippool-selection-patch.yaml, docs/usage/ippool-affinity-node.md, docs/usage/ippool-multi.md, docs/usage/ippool-namespace.md, docs/usage/reserved-ip.md
=> docs: Update usage documents

test/Makefile, test/e2e/assignip/assignip_test.go, test/e2e/common/deployment.go, test/e2e/common/replicaset.go, test/e2e/common/statefulset.go, test/e2e/ippoolcr/ippoolcr_test.go, test/e2e/subnet/subnet_test.go
=> fix: Avoid getting an empty pod list

.github/.spelling, docs/example/basic/custom-ippool-deploy.yaml, docs/usage/basic.md, docs/usage/install.md
=> docs: Pretty print install.md

pkg/ippoolmanager/ippool_informer.go
fix bug
https://github.com/spidernet-io/spiderpool/issues/1067
=> fix ipool workequeue panic

pkg/ipam/ipam.go
improve statefulset cmdDel mechanism to clean up the last failure IPAM allocations
fix bug
https://github.com/spidernet-io/spiderpool/issues/1045
=> improve statefulset ipam cmd delete

pkg/ippoolmanager/ippool_manager.go, pkg/subnetmanager/subnet_controller.go
In the previous version, if we create 40 app at the same time, it will cost over 197s to create empty IPPools.
But now, we decrease the time duration to 43s
Signed-off-by: Icarus9913 <icaruswu66@qq.com
=> make create or mark IPPool asynchronized

test/e2e/common/deployment.go, test/e2e/common/spidersubnet.go
Improve e2e robustness
Improve some APIs
=> E2E: Improve some api

docs/example/ippool-affnity-namespace/different-ns-deploys.yaml, docs/example/ippool-affnity-namespace/test-ns-ipv4-ippool.yaml, docs/usage/ippool-affinity-namespace.md, docs/usage/ippool-affinity-node.md
=> docs: Add doc ippool-affinity-namespace.md

.github/.spelling, docs/example/ippool-affinity-pod/static-ippool-deploy.yaml, docs/example/ippool-affinity-pod/static-ipv4-ippool.yaml, docs/example/ippool-affinity-pod/wrong-static-ippool-deploy.yaml, docs/usage/ippool-affinity-pod.md, docs/usage/ippool-namespace.md, docs/usage/reserved-ip.md
=> docs: Add doc ippool-affinity-pod.md

test/doc/annotation.md, test/doc/assignip.md, test/doc/cidr.md, test/doc/configmap.md, test/doc/ippoolcr.md, test/e2e/common/constant.go, test/e2e/subnet/subnet_test.go
None
Wait for now, still need to wait for [this problem](#1088 ) to be resolved
=> E2E: add case create deploys with the same name

pkg/namespacemanager/namespace_manager_test.go, pkg/namespacemanager/namespacemanager_suite_test.go, pkg/nodemanager/node_manager_test.go, pkg/nodemanager/nodemanager_suite_test.go, pkg/podmanager/pod_manager_test.go, pkg/podmanager/podmanager_suite_test.go
=> unittest: add unittest

test/e2e/subnet/subnet_test.go
Unreleased deployment resources
=> fix: resources not released

images/spiderpool-agent/Dockerfile, images/spiderpool-controller/Dockerfile
=> fix:Docker automatic ARG `TARGETARCH` is missing

images/spiderpool-agent/Dockerfile, images/spiderpool-controller/Dockerfile
=> fix: The architecture of base image mismatch

.github/workflows/auto-version-release.yaml
=> ci: release branch

.github/workflows/auto-cherrypick.yaml, .github/workflows/auto-version-release.yaml, .github/workflows/call-update-githubpages.yaml
=> ci: cherry pick

pkg/ip/cidr_test.go, pkg/ip/ip.go, pkg/ip/ip_suite_test.go, pkg/ip/ip_test.go, pkg/ip/iprange.go, pkg/ip/iprange_test.go, pkg/ip/route_test.go, pkg/ip/utils.go, pkg/ip/utils_test.go, pkg/ippoolmanager/ippool_informer.go, pkg/subnetmanager/subnet_manager.go, pkg/types/ip.go, pkg/types/types.go
=> test: Add unit tests for pkg ip

test/e2e/common/spiderpool.go, test/e2e/common/spidersubnet.go, test/e2e/subnet/subnet_test.go
Waiting for the issue to be resolved
- https://github.com/spidernet-io/spiderpool/issues/868
- https://github.com/spidernet-io/spiderpool/issues/746
=> E2E: the same spec is used to create the subnet and only one should succeed

pkg/limiter/limiter_suite_test.go, pkg/limiter/queue_test.go, pkg/nodemanager/node_manager_suite_test.go
=> test: Update the descriptions and labels of some specs

cmd/spiderpool-agent/cmd/daemon.go, cmd/spiderpool-controller/cmd/daemon.go, pkg/ippoolmanager/ippool_manager.go, pkg/reservedipmanager/config.go, pkg/reservedipmanager/reservedip_manager.go, pkg/reservedipmanager/reservedip_manager_suite_test.go, pkg/reservedipmanager/reservedip_manager_test.go, pkg/reservedipmanager/reservedip_mutate.go, pkg/reservedipmanager/reservedip_validate.go, pkg/reservedipmanager/reservedip_webhook.go, pkg/reservedipmanager/utils.go, pkg/subnetmanager/subnet_manager.go
=> test: Add unit tests for pkg reservedipmanager

.github/workflows/auto-cherrypick.yaml, .github/workflows/pr-label-check.yaml
=> ci: check label

pkg/ippoolmanager/ippool_informer.go, pkg/ippoolmanager/ippool_manager.go, pkg/ippoolmanager/types/interface.go, pkg/ippoolmanager/utils.go, pkg/subnetmanager/controllers/utils.go
robot cherry pick pr <https://github.com/spidernet-io/spiderpool/pull/1135>,  action <https://github.com/spidernet-io/spiderpool/actions/runs/3646148587>  , commits 1880fcad029c5d075d9c9fc43ea9df58851a6180
=> auto cherry pick PR 1135 to branch release-v0.3

pkg/ippoolmanager/ippool_informer.go, pkg/subnetmanager/app_controller.go, pkg/subnetmanager/controllers/cronjob_informer.go, pkg/subnetmanager/controllers/daemonset_informer.go, pkg/subnetmanager/controllers/deployment_informer.go, pkg/subnetmanager/controllers/job_informer.go, pkg/subnetmanager/controllers/replicaset_informer.go, pkg/subnetmanager/controllers/statefulset_informer.go, pkg/subnetmanager/subnet_informer.go
robot cherry pick pr <https://github.com/spidernet-io/spiderpool/pull/1155>,  action <https://github.com/spidernet-io/spiderpool/actions/runs/3648060653>  , commits 8de5b681cb61dea24f1d330820008f1b14e5e464
=> auto cherry pick PR 1155 to branch release-v0.3

.github/workflows/auto-cherrypick.yaml, .github/workflows/pr-label-check.yaml
=> workflow: fix gh cli

.github/workflows/auto-pr-ci.yaml, .github/workflows/e2e-init.yaml, .github/workflows/trivy-scan-image.yaml
Through the test, the current CI time is about 30 minutes, and it took 60+ minutes before
https://github.com/spidernet-io/spiderpool/actions/runs/3644512524/jobs/6153897207
=> Modify e2e CI job to be parallel

.github/.spelling, docs/develop/upgrade.md, docs/mkdocs.yml, docs/usage/spider-subnet.md, pkg/ippoolmanager/ippool_informer.go, pkg/subnetmanager/controllers/utils.go
cherry pick [#1662](https://github.com/spidernet-io/spiderpool/pull/1162) to release v0.3
https://github.com/spidernet-io/spiderpool/issues/1176
=> cherry pick pr 1662 to release v0.3

pkg/ippoolmanager/ippool_informer.go
robot cherry pick pr <https://github.com/spidernet-io/spiderpool/pull/1169>,  action <https://github.com/spidernet-io/spiderpool/actions/runs/3681739116>  , commits 1b57f0d81ce7b0774cfa0cad05d62c489173751b
=> auto cherry pick PR 1169 to branch release-v0.3

pkg/gcmanager/scanAll_IPPool.go, pkg/gcmanager/tracePod_worker.go, pkg/workloadendpointmanager/workloadendpoint_manager.go, test/e2e/common/spiderpool.go, test/scripts/debugEnv.sh
=> bug fix: leak the spiderendpoint of StatefulSet

.github/workflows/auto-cherrypick.yaml
=> ci: title for cherry pick pr

pkg/workloadendpointmanager/workloadendpoint_manager.go
=> fix: The normal IP addresses are recycled by mistake when multiple Pods with the same namespace and name are created in a short time

cmd/spiderpool-agent/cmd/daemon.go, cmd/spiderpool-controller/cmd/daemon.go, pkg/namespacemanager/namespace_manager_test.go, pkg/namespacemanager/utils_test.go, pkg/nodemanager/node_manager_test.go, pkg/podmanager/pod_manager_test.go, pkg/podmanager/utils_test.go, pkg/statefulsetmanager/sts_manager.go, pkg/statefulsetmanager/sts_manager_suite_test.go, pkg/statefulsetmanager/sts_manager_test.go
=> test: Add unit tests for pkg statefulsetmanager

pkg/ippoolmanager/ippool_subnet_validate.go, pkg/ippoolmanager/ippool_webhook.go, pkg/podmanager/utils_test.go, pkg/reservedipmanager/reservedip_webhook.go, pkg/reservedipmanager/reservedip_webhook_test.go, pkg/reservedipmanager/utils.go, pkg/reservedipmanager/utils_test.go, pkg/subnetmanager/subnet_webhook.go
=> No longer validate when deleting SpiderIPPool, SpiderSubnet and SpiderReservedIP

charts/spiderpool/values.yaml
=> modify charts value comments

test/e2e/affinity/affinity_test.go, test/e2e/annotation/annotation_suite_test.go, test/e2e/annotation/annotation_test.go, test/e2e/common/tools.go, test/e2e/reclaim/reclaim_suite_test.go, test/e2e/reclaim/reclaim_test.go, test/e2e/reliability/reliability_test.go
Adapt to the default subnet, cancel the use of the default pool, and create a new pool as a public pool
=> E2E: sync default subnet

docs/mkdocs.yml
=> Added mkdocs display

docs/usage/basic.md
=> fix: quickstart docs deployment fails question

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/ci-failure.md, .github/ISSUE_TEMPLATE/doc.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/usage.md
=> ci: issue assingees

Makefile
=> fix: The "tags" plugin is not installed

Makefile
robot cherry pick pr <https://github.com/spidernet-io/spiderpool/pull/1228> to branch release-v0.3,  action <https://github.com/spidernet-io/spiderpool/actions/runs/3792800961>  , commits 16fd1aa7bdec8efbd8f4f0b29393c37842c76c9e
=> title:	fix: The "tags" plugin is not installed

Makefile
=> mkdocs-material:8.5.11

charts/spiderpool/values.yaml
modify charts value comments and make it regular.
=> fix charts value comment

.github/workflows/call-release-changelog.yaml
=> ci: changelog

cmd/spiderpool-controller/cmd/daemon.go, pkg/ippoolmanager/ippool_manager.go, pkg/ippoolmanager/ippool_manager_suite_test.go, pkg/ippoolmanager/ippool_mutate.go, pkg/ippoolmanager/ippool_subnet_validate.go, pkg/ippoolmanager/ippool_validate.go, pkg/ippoolmanager/ippool_webhook.go, pkg/ippoolmanager/ippool_webhook_test.go, pkg/ippoolmanager/types/interface.go
=> test: Add webhook unit tests for pkg ippoolmanager

pkg/subnetmanager/app_controller.go, pkg/subnetmanager/subnet_manager.go, pkg/subnetmanager/types/interface.go
This is a cherrypick to releaseV0.3, reference PR: (#1260)[https://github.com/spidernet-io/spiderpool/pull/1260]
This PR will potential SpiderSubnet feature panic where we may use nil address pointer.
fix bug
https://github.com/spidernet-io/spiderpool/issues/1252
=> fix potential panic with SpiderSubnet feature application pod selector

test/e2e/common/spidersubnet.go, test/e2e/subnet/subnet_test.go
=> fix: Patch reports an error version has changed

cmd/spiderpool-agent/cmd/daemon.go, cmd/spiderpool-controller/cmd/daemon.go, pkg/subnetmanager/app_controller.go, pkg/subnetmanager/config.go, pkg/subnetmanager/subnet_informer.go, pkg/subnetmanager/subnet_manager.go, pkg/subnetmanager/types/interface.go
=> Refactor the informer code of SpiderSubnet

pkg/podmanager/pod_manager_test.go
=> test: supplement pod manager unit test

cmd/spiderpool/cmd/command_test.go
=> test: supplement cmdAdd and cmdDel unit test

.github/workflows/auto-nightly-ci.yaml
=> fix: UT failed, but no issue was created

test/doc/assignip.md, test/doc/cidr.md, test/e2e/common/spiderpool.go, test/e2e/common/spidersubnet.go, test/e2e/kruise/kruise_test.go, test/e2e/subnet/subnet_test.go
=> E2E: Add E2E with SpiderSubnet supporting multiple interfaces, default subnets and third-party controllers.

docs/mkdocs.yml, docs/usage/spider-subnet.md
- Add spidernet to the nav list
- Remove `usage/cidrManger.md`, which doesn't exist, from nav
- Remove `usage/cli.md`, which is blank currently, from nav
- Improve some text
=> [Docs] Add spidersubnet to mkdocs.yml

test/e2e/affinity/affinity_test.go, test/e2e/common/spiderpool.go, test/e2e/subnet/subnet_test.go
=> fix: e2e failure to detect endpoint

charts/spiderpool/crds/spiderpool.spidernet.io_spidersubnets.yaml, pkg/constant/k8s.go, pkg/ip/utils.go, pkg/ip/utils_test.go, pkg/ippoolmanager/ippool_mutate.go, pkg/ippoolmanager/ippool_subnet_validate.go, pkg/ippoolmanager/ippool_validate.go, pkg/ippoolmanager/ippool_webhook_test.go, pkg/k8s/apis/spiderpool.spidernet.io/v1/spidersubnet_types.go, pkg/reservedipmanager/reservedip_mutate.go, pkg/reservedipmanager/reservedip_validate.go, pkg/reservedipmanager/reservedip_webhook_test.go, pkg/subnetmanager/subnet_mutate.go, pkg/subnetmanager/subnet_validate.go, pkg/subnetmanager/subnet_webhook_test.go
=> Refactor webhook

test/e2e/affinity/affinity_test.go, test/e2e/annotation/annotation_test.go, test/e2e/subnet/subnet_test.go
=> fix: Concurrently created deployments of the same name causing check events to fail.

pkg/gcmanager/scanAll_IPPool.go
=> fix: An incorrect GC occurred during IP allocation

pkg/ip/ip.go, pkg/ip/ip_test.go, pkg/ip/iprange.go, pkg/ip/utils.go, pkg/ippoolmanager/ippool_informer.go, pkg/ippoolmanager/ippool_manager.go, pkg/ippoolmanager/ippool_subnet_validate.go, pkg/ippoolmanager/ippool_validate.go, pkg/subnetmanager/controllers/utils.go, pkg/subnetmanager/subnet_informer.go, pkg/subnetmanager/subnet_validate.go, test/e2e/common/spidersubnet.go
=> Add flag to IPsDiffSet, IPsDiffSet and IPsIntersectionSet to determine whether the IP addresses result set needs to be sorted

pkg/subnetmanager/subnet_informer.go
=> Sync CIDR label in SpiderSubnet controller

README.md
=> doc: Update README-en

cmd/spiderpool-agent/cmd/crd_manager.go, cmd/spiderpool-controller/cmd/crd_manager.go, cmd/spiderpool/cmd/command_delete.go
=> Adjust the burst and qps of the API server client of spiderpool-agent and spiderpool-controller

cmd/spiderpool-agent/cmd/ipam.go, docs/concepts/metrics.md, pkg/ipam/ipam.go, pkg/ippoolmanager/ippool_manager.go, pkg/metric/metrics_instance.go, pkg/metric/metrics_ipam.go
=> Add the metrics of queue time and the count of conflicts when updating IPPool

pkg/subnetmanager/controllers/controller_internal_test.go, pkg/subnetmanager/controllers/controllers_suite_test.go, pkg/subnetmanager/controllers/cronjob_informer_internal_test.go, pkg/subnetmanager/controllers/daemonset_informer_internal_test.go, pkg/subnetmanager/controllers/deployment_informer_internal_test.go, pkg/subnetmanager/controllers/job_informer_internal_test.go, pkg/subnetmanager/controllers/replicaset_informer_internal_test.go, pkg/subnetmanager/controllers/statefulset_informer_internal_test.go, pkg/subnetmanager/controllers/utils_internal_test.go
=> ut subnetmanager contorllers

charts/spiderpool/crds/spiderpool.spidernet.io_spiderippools.yaml, charts/spiderpool/crds/spiderpool.spidernet.io_spidersubnets.yaml, pkg/k8s/apis/spiderpool.spidernet.io/v1/spiderippool_types.go, pkg/k8s/apis/spiderpool.spidernet.io/v1/spidersubnet_types.go
=> feat: Add the 'status.default' column to the 'kubectl get' output of SpiderSubnet and SpiderIPPool

docs/README.md
---
about: fix the incorrect jump link address of the document
---
---
Signed-off-by: Zechun Chen <zechun.chen@daocloud.io>
=> fix the incorrect jump link address of the document

cmd/spiderpool/cmd/utils.go, test/e2e/cli/cli_suite_test.go, test/e2e/common/reservedip.go, test/e2e/configmap/configmap_suite_test.go, test/e2e/ippoolcr/ippoolcr_suite_test.go, test/e2e/metric/metric_suite_test.go, test/e2e/performance/performance_suite_test.go
Signed-off-by: Zechun Chen <zechun.chen@daocloud.io>
=> optimized the order of import packages

pkg/ipam/release.go
=> Replace the timeout of CNI DEL's ctx to the deletion grace period of Pod

cmd/spiderpoolctl/cmd/command_root.go, pkg/lock/lock_debug_test.go, pkg/lock/lock_fast_test.go, pkg/statefulsetmanager/sts_manager_test.go, pkg/workloadendpointmanager/workloadendpoint_manager.go, pkg/workloadendpointmanager/workloadendpoint_manager_test.go
=> test: Add some unit tests for Endpoint manager and STS manager

cmd/spiderpool-agent/cmd/command_daemon.go, cmd/spiderpool-agent/cmd/command_root.go, cmd/spiderpool-agent/cmd/command_shutdown.go, cmd/spiderpool-agent/cmd/daemon.go, cmd/spiderpool-controller/cmd/command_daemon.go, cmd/spiderpool-controller/cmd/command_root.go, cmd/spiderpool-controller/cmd/command_shutdown.go, cmd/spiderpool-controller/cmd/command_status.go, cmd/spiderpool-controller/cmd/daemon.go, cmd/spiderpoolctl/cmd/command_root.go, pkg/utils/cmdgenmd/cmd_generate_markdown.go
=> Adjust some log messages and pkg structure

cmd/spiderpool-agent/cmd/ipam.go, pkg/ipam/release.go
=> fix: Pod UID is an empty string when calling CNI DEL

cmd/spiderpool-agent/cmd/config.go, cmd/spiderpool-controller/cmd/config.go, cmd/spiderpool/cmd/command_add.go, pkg/ipam/allocate.go
=> Adjust the timeout of ctx to 100s when CNI ADD

pkg/ippoolmanager/ippool_validate.go, pkg/ippoolmanager/ippool_webhook_test.go, pkg/subnetmanager/subnet_validate.go, pkg/subnetmanager/subnet_webhook_test.go
=> Add validation for `spec.default` in the webhook of SpiderSubnet and

pkg/gcmanager/gc_manager.go, pkg/gcmanager/pod_cache.go, pkg/gcmanager/pod_informer.go, pkg/gcmanager/scanAll_IPPool.go, pkg/gcmanager/tracePod_worker.go, pkg/ipam/release.go, pkg/statefulsetmanager/sts_manager.go, pkg/statefulsetmanager/sts_manager_test.go
implement IP garbage collection
=> IP garbage collection

charts/spiderpool/crds/spiderpool.spidernet.io_spiderendpoints.yaml, pkg/ipam/allocate.go, pkg/ipam/release.go, pkg/k8s/apis/spiderpool.spidernet.io/v1/spiderendpoint_types.go, pkg/k8s/apis/spiderpool.spidernet.io/v1/types_string.go, pkg/utils/convert/convert.go, pkg/workloadendpointmanager/utils.go, pkg/workloadendpointmanager/utils_test.go, pkg/workloadendpointmanager/workloadendpoint_manager.go, pkg/workloadendpointmanager/workloadendpoint_manager_test.go
=> fix: The IP allocation of Endpoint is incomplete in multi-NIC mode

cmd/spiderpool-agent/cmd/daemon.go, cmd/spiderpool-controller/cmd/daemon.go, pkg/ipam/allocate.go, pkg/ipam/pool_selections.go, pkg/ipam/release.go, pkg/ippoolmanager/ippool_manager.go, pkg/ippoolmanager/utils.go, pkg/k8s/apis/spiderpool.spidernet.io/v1/spidersubnet_types.go, pkg/subnetmanager/subnet_informer.go, pkg/subnetmanager/subnet_informer_test.go, pkg/subnetmanager/subnet_manager.go, pkg/subnetmanager/subnet_validate.go, pkg/subnetmanager/subnet_webhook_test.go, pkg/utils/convert/convert.go, test/e2e/reclaim/reclaim_test.go
=> Refactor Subnet Controller

pkg/limiter/queue.go, pkg/limiter/queue_test.go
=> feat: Add queuer timeout mechanism based on context for pkg limiter

pkg/ippoolmanager/ippool_manager_suite_test.go, pkg/namespacemanager/namespace_manager_suite_test.go, pkg/nodemanager/node_manager_suite_test.go, pkg/podmanager/pod_manager_suite_test.go, pkg/reservedipmanager/reservedip_manager_suite_test.go, pkg/statefulsetmanager/sts_manager_suite_test.go, pkg/subnetmanager/subnet_manager_suite_test.go, pkg/workloadendpointmanager/workloadendpoint_manager_suite_test.go, pkg/workloadendpointmanager/workloadendpoint_manager_test.go
=> test: Add field index to fake client

pkg/constant/k8s.go, pkg/ipam/pool_selections.go, pkg/ipam/utils.go, pkg/podmanager/pod_manager.go, pkg/podmanager/pod_manager_test.go
=> [unit tests] pod mananger unit test

charts/spiderpool/templates/tls.yaml
=> Change the request path of webhook from v1 to v2beta1

pkg/ippoolmanager/ippool_manager.go, pkg/utils/convert/convert.go
=> fix: Field `status.allocatedIPCount` is empty instead of 0

cmd/spiderpool-init/cmd/config.go
=> fix: In the case of IPv6 only, the default IPv6 SpiderSubnet or SpiderIPPool is not created

.github/workflows/e2e-init.yaml, test/e2e/e2e_test/e2e_test_suite_test.go
=> Pending for e2e, facilitating the release of new versions

.trivyignore, CODEOWNERS, Makefile
=> Add config file .trivyignore and filter vulnerability AVD-KSV-0046

pkg/ipam/release.go, pkg/ippoolmanager/ippool_manager.go, pkg/ippoolmanager/ippool_manager_suite_test.go, pkg/ippoolmanager/ippool_manager_test.go, pkg/subnetmanager/subnet_manager_test.go
=> test: Add unit tests for IPPoolManager

pkg/ipam/pool_selections.go, test/e2e/kruise/kruise_test.go
Because of issue https://github.com/spidernet-io/spiderpool/issues/1495, the e2e case is Pending and will now be opened.
=> e2e test case for releasing a statefulset controlled by a third party

pkg/applicationcontroller/app_controller.go, pkg/applicationcontroller/applicationinformers/utils.go, pkg/ipam/pool_selections.go, pkg/subnetmanager/subnet_manager.go
=> decrease auto-created ippool name

test/Makefile.defs
=> Update the Kubernetes version of spiderpool e2e to 1.26.x

docs/concepts/arch.md
---
about: Fix the CRD description document entry
---
---
Signed-off-by: Zechun Chen <zechun.chen@daocloud.io>
=> update the crd description document entry

docs/README.md, docs/mkdocs.yml, docs/usage/basic.md, docs/usage/install.md
=> doc: add overview  &  optimize quick start

README.md, docs/usage/basic.md
=> Optimize some of the instructions in the documentation

pkg/statefulsetmanager/sts_manager.go, pkg/statefulsetmanager/sts_manager_test.go
=> change statefulset pod validation

pkg/gcmanager/scanAll_IPPool.go
In the source codes, there's a simple error that I ignored. 
Once I found the IPPool allocation pod not exist in kubernetes, I searched its corresponding SpiderEndpoint CR object and if I found it, I just check whether it's a StatefulSet pod and decide to GC. If it's not a StatefulSet pod, it should be also GC.
=> fix IP GC scan all not work issue

pkg/limiter/queue.go, pkg/limiter/queue_test.go
=> fix: Limiter may deadlock when the queuer's ctx is about to deadline

pkg/subnetmanager/subnet_informer.go
=> fix: SubnetInformer executes SYNC too many times

cmd/spiderpool-controller/cmd/daemon.go, pkg/gcmanager/gc_manager.go, pkg/gcmanager/pod_informer.go
make IP GC pod informer to watch pod once the spiderpool-controller aquire the leader
=> improve IP GC pod informer startup

charts/spiderpool/README.md, charts/spiderpool/values.yaml
=> Enable feature SpiderSubnet by default

pkg/gcmanager/scanAll_IPPool.go, pkg/gcmanager/tracePod_worker.go, pkg/ipam/release.go, pkg/workloadendpointmanager/workloadendpoint_manager.go, pkg/workloadendpointmanager/workloadendpoint_manager_test.go
=> Patch instead of updating the finalizer of SpiderEndpoint

docs/usage/get-started-macvlan-zh_CN.md
=> add quick start doc for macvlan

docs/develop/CODE-OF-CONDUCT.md
=> code conduct

pkg/applicationcontroller/applicationinformers/applicationinformers_suite_test.go, pkg/applicationcontroller/applicationinformers/controller_test.go, pkg/applicationcontroller/applicationinformers/cronjob_informer_test.go, pkg/applicationcontroller/applicationinformers/daemonset_informer_test.go, pkg/applicationcontroller/applicationinformers/deployment_informer_test.go, pkg/applicationcontroller/applicationinformers/job_informer_test.go, pkg/applicationcontroller/applicationinformers/replicaset_informer_test.go, pkg/applicationcontroller/applicationinformers/statefulset_informer_test.go, pkg/applicationcontroller/applicationinformers/utils_test.go
=> [unit tests] supplement application controller unit tests

cmd/spiderpool-agent/cmd/daemon.go, cmd/spiderpool-controller/cmd/daemon.go
=> improve statrup

charts/spiderpool/templates/daemonset.yaml, charts/spiderpool/templates/deployment.yaml
=> Adjust the parameters of the probe

Makefile
=> Remove deprecated Ginkgo flag `--slow-spec-threshold`

docs/usage/performance-zh_CH.md
=> docs: Add docs for performance testing

pkg/applicationcontroller/app_controller.go, pkg/applicationcontroller/app_controller_test.go, pkg/applicationcontroller/applicationcontroller_suite_test.go
=> [unit test] supplement application controller unit test

docs/usage/get-started-calico-zh_CN.md, docs/usage/get-started-calico.md
=> add translation for get-started-calico

docs/usage/performance-zh_CH.md, docs/usage/performance.md
=> docs: Add docs performance.md

pkg/ippoolmanager/ippool_manager_suite_test.go, pkg/ippoolmanager/ippool_manager_test.go
=> test: Add some unit tests for IPPoolManager

docs/example/multi-interfaces-annotation/different-segment-ipv4-subnets.yaml, docs/example/multi-interfaces-annotation/ippool-test-deploy.yaml, docs/example/multi-interfaces-annotation/multus-conf.yaml, docs/example/multi-interfaces-annotation/subnet-test-deploy.yaml, docs/usage/multi-interfaces-annotation.md
=> add multi interfaces doc

test/e2e/affinity/affinity_test.go, test/e2e/assignip/assignip_test.go, test/e2e/ippoolcr/ippoolcr_test.go, test/e2e/performance/performance_test.go, test/e2e/reservedip/reservedip_test.go
=> Fixing ambiguous aliases

test/e2e/performance/performance_test.go
=> improve e2e test log

README-zh_CN.md, README.md
=> update en readme

pkg/ipam/pool_selections.go, pkg/ipam/utils.go
=> code optimization with third-party controller SpiderSunet feature

cmd/spiderpool-agent/cmd/runtime_status.go, cmd/spiderpool-controller/cmd/runtime_status.go
Add additional logs for readiness probe check
improvement
=> improve readiness probe logs

test/e2e/reclaim/reclaim_test.go, test/e2e/reliability/reliability_test.go
=> add debug time for issue 1612

test/e2e/kruise/kruise_test.go
=> E2E: Automatic pools of third party controllers can be reclaimed automatically

docs/usage/get-started-calico-zh_CN.md, docs/usage/get-started-calico.md
=> docs: optimize the execution command in the document

README-zh_CN.md
Signed-off-by: Zechun Chen <zechun.chen@daocloud.io>
=> docs: remove unnecessary errors in translation

pkg/gcmanager/pod_cache.go, pkg/gcmanager/pod_informer.go
=> improve ip gc logs

Makefile, Makefile.defs, docs/example/multi-interfaces-annotation/subnet-test-deploy.yaml, docs/mkdocs.yml, docs/usage/get-started-calico-zh_CN.md, docs/usage/get-started-kind-zh_CN.md, docs/usage/get-started-kind.md, docs/usage/get-started-macvlan-zh_CN.md, docs/usage/get-started-macvlan.md, docs/usage/get-started-sriov-zh_CN.md, docs/usage/get-started-sriov.md, docs/usage/get-started-weave-zh_CN.md, docs/usage/install.md, docs/usage/multi-interfaces-annotation.md, test/Makefile.defs
=> docs: add get started for kind

pkg/subnetmanager/subnet_manager.go
It's illegal to change the SpiderSubnet for applications in SpiderSubnet feature, and it will make the system work not good.
And you must change it back if you switched the subnet in the application.template.annotation.
Also, you will check the corresponding original auto-created IPPools events if you did change it.
fix bug
https://github.com/spidernet-io/spiderpool/issues/1647
=> make it takes not effect when app subnet changed in SpiderSubnet feature

docs/usage/gc.md, pkg/gcmanager/pod_cache.go, pkg/gcmanager/tracePod_worker.go
fix bug
https://github.com/spidernet-io/spiderpool/issues/1659
=> fix IP GC doesn't trace statefulset terminating pod issue

pkg/statefulsetmanager/sts_manager.go, pkg/statefulsetmanager/sts_manager_test.go
Ref: https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#start-ordinal
=> add kubernetes StatefulSet Start ordinal support

pkg/statefulsetmanager/sts_manager.go, pkg/statefulsetmanager/sts_manager_test.go
robot cherry pick pr <https://github.com/spidernet-io/spiderpool/pull/1667> to branch release-v0.4,  action <https://github.com/spidernet-io/spiderpool/actions/runs/4697966148>  , commits 47d5925ec60638042ca93189edfcae16e60cbed4
=> title:	add kubernetes StatefulSet Start ordinal support

pkg/subnetmanager/subnet_manager.go
robot cherry pick pr <https://github.com/spidernet-io/spiderpool/pull/1664> to branch release-v0.4,  action <https://github.com/spidernet-io/spiderpool/actions/runs/4696892411>  , commits ed1e41dee6005271dfad2fb258a6cd70e2b33060
=> title:	make it takes not effect when app subnet changed in SpiderSubnet feature

Makefile, cmd/spiderpool-agent/cmd/daemon.go
=> fix: Pod of spiderpool-agent restarts too slowly when node restart

Makefile, cmd/spiderpool-agent/cmd/daemon.go
robot cherry pick pr <https://github.com/spidernet-io/spiderpool/pull/1669> to branch release-v0.4,  action <https://github.com/spidernet-io/spiderpool/actions/runs/4698539155>  , commits c4a9ec9df8c37ded73001b62185fa6c638f363d5
=> title:	fix: Pod of spiderpool-agent restarts too slowly when node restart

docs/mkdocs.yml, docs/usage/get-started-ovs-zh_CN.md, docs/usage/get-started-ovs.md, docs/usage/install.md
=> docs:add get started for ovs-cni

.github/workflows/call-release-image.yaml
=> support cosign for image signature and SBOM

cmd/spiderpool-agent/cmd/config.go, cmd/spiderpool-agent/cmd/metrics_server.go, cmd/spiderpool-controller/cmd/config.go, cmd/spiderpool-controller/cmd/daemon.go, cmd/spiderpool-controller/cmd/metrics_server.go, docs/concepts/metrics.md, pkg/ippoolmanager/ippool_informer.go, pkg/ippoolmanager/ippool_manager_suite_test.go, pkg/metric/metrics.go, pkg/metric/metrics_instance.go, pkg/metric/metrics_ipam.go, pkg/subnetmanager/subnet_informer.go, pkg/subnetmanager/subnet_manager_suite_test.go, pkg/subnetmanager/subnet_validate.go
=> add debug level metrics

cmd/spiderpool-agent/cmd/daemon.go, cmd/spiderpool-agent/cmd/health.go, cmd/spiderpool-agent/cmd/ipam.go, cmd/spiderpool-controller/cmd/daemon.go, cmd/spiderpool-controller/cmd/runtime_status.go, pkg/ippoolmanager/ippool_informer.go, pkg/ippoolmanager/utils.go, pkg/subnetmanager/subnet_manager.go
=> remove todo comments

charts/spiderpool/README.md, charts/spiderpool/templates/grafanaDashboard.yaml, charts/spiderpool/values.yaml, pkg/metric/metrics_instance.go
=> add grafana dashaboard

charts/spiderpool/README.md, charts/spiderpool/templates/grafanaDashboard.yaml, charts/spiderpool/values.yaml, pkg/metric/metrics_instance.go
robot cherry pick pr <https://github.com/spidernet-io/spiderpool/pull/1676> to branch release-v0.4,  action <https://github.com/spidernet-io/spiderpool/actions/runs/4760921867>  , commits 395302c889c27e0eba29beae2184e43e519d4a2a cb859702da4e0a722cef565080be08aaecbb021a
=> title:	add grafana dashaboard

docs/usage/get-started-sriov.md
=> docs: typo

pkg/subnetmanager/subnet_manager.go
=> fix auto-created pool reconcile algorithm

pkg/subnetmanager/subnet_manager.go
robot cherry pick pr <https://github.com/spidernet-io/spiderpool/pull/1693> to branch release-v0.4,  action <https://github.com/spidernet-io/spiderpool/actions/runs/4776473438>  , commits ad9bc0e7a712b0d5e03407f60d64fb8f126de8ad
=> title:	fix auto-created pool reconcile algorithm

docs/usage/performance-zh_CH.md, docs/usage/performance.md
=> docs: Add CNI performance test data in IPv4 single stack case

.github/workflows/call-update-githubpages.yaml
=> fix update githubpages ci

.github/workflows/call-update-githubpages.yaml
robot cherry pick pr <https://github.com/spidernet-io/spiderpool/pull/1708> to branch release-v0.4,  action <https://github.com/spidernet-io/spiderpool/actions/runs/4796445239>  , commits d23f057c9a474fe204d8cf1075cb73be54ea3703
=> title:	fix update githubpages ci

docs/develop/release.md, docs/usage/performance-zh_CH.md, docs/usage/performance.md
=> docs: Add performance test data for CNIs in fault recovery case

.github/workflows/call-release-image.yaml
=> fix ci typo

.github/workflows/call-release-image.yaml
robot cherry pick pr <https://github.com/spidernet-io/spiderpool/pull/1734> to branch release-v0.5,  action <https://github.com/spidernet-io/spiderpool/actions/runs/4819334911>  , commits 702d7db297190010d74fe24815572fabfdc9abc3
=> title:	fix ci typo

docs/concepts/annotation.md
=> docs: Update docs concepts/annotation.md

pkg/ippoolmanager/ippool_informer_test.go, vendor/k8s.io/client-go/dynamic/fake/simple.go, vendor/modules.txt
=> add ippool-informer unit test

docs/mkdocs.yml
=> modify github document

pkg/ippoolmanager/ippool_informer_test.go, pkg/subnetmanager/subnet_informer_test.go, pkg/subnetmanager/subnet_manager_suite_test.go
=> supplement subnet-informer unit test

pkg/subnetmanager/subnet_manager_test.go
=> supplement subnet manager unit test

pkg/ipam/pool_selections.go
This is a bug from https://github.com/spidernet-io/spiderpool/pull/1725.
I did not use the pod annotation reclaim value.
fix bug
close #1745
=> fix third-party controller auto-pool reclaim ippool symbol

pkg/ipam/pool_selections.go
robot cherry pick pr <https://github.com/spidernet-io/spiderpool/pull/1746> to branch release-v0.5,  action <https://github.com/spidernet-io/spiderpool/actions/runs/4911197112>  , commits 6932aea53372c3f911b16fd27b042a2173680e05
=> title:	fix third-party controller auto-pool reclaim ippool symbol
