docs/usage/gc.md
=> supplement IP GC documents

docs/usage/gc.md
robot cherry pick pr <https://github.com/spidernet-io/spiderpool/pull/1750> to branch release-v0.5,  action <https://github.com/spidernet-io/spiderpool/actions/runs/4913851118>  , commits db0d334b3a65c66778d890fac163426096521ddf
=> title:	supplement IP GC documents

pkg/applicationcontroller/app_controller.go, pkg/applicationcontroller/applicationinformers/utils.go, pkg/ipam/pool_selections.go, pkg/subnetmanager/subnet_manager.go
=> add auto pool reclaim swicth support

pkg/applicationcontroller/app_controller.go, pkg/applicationcontroller/applicationinformers/utils.go, pkg/constant/k8s.go, pkg/ipam/pool_selections.go, pkg/ippoolmanager/ippool_informer.go, pkg/ippoolmanager/ippool_webhook_test.go, pkg/ippoolmanager/utils.go, pkg/ippoolmanager/utils_test.go, pkg/subnetmanager/subnet_manager.go
cherry-pick
close #1754 
close #1757
=> Cherrypick 1749&1757 to release v0.5

charts/spiderpool/README.md, charts/spiderpool/templates/configmap.yaml, charts/spiderpool/values.yaml, cmd/spiderpool-controller/cmd/config.go, cmd/spiderpool-controller/cmd/daemon.go, pkg/applicationcontroller/applicationinformers/utils.go
robot cherry pick pr <https://github.com/spidernet-io/spiderpool/pull/1763> to branch release-v0.5,  action <https://github.com/spidernet-io/spiderpool/actions/runs/4923947095>  , commits 7bad2c165042e293841c4f738a673cce59253ee0 87106ecc6353d5eefd0bb93bf9a02f427b2878d3
=> title:	add cluster subnet flexible ip number support

pkg/applicationcontroller/app_controller.go, pkg/ipam/pool_selections.go, pkg/subnetmanager/subnet_manager.go, pkg/subnetmanager/subnet_manager_test.go, pkg/types/k8s.go
supplement annotation for auto-created IPPool to explain whether its IP number is flexible or fixed.
new feature
close #1769
=> supplement annotation for Auto-Pool 

docs/concepts/annotation.md, docs/concepts/config.md, docs/usage/spider-subnet.md, docs/usage/statefulset.md, docs/usage/third-party-controller.md
=> docs improvement

pkg/applicationcontroller/app_controller.go, pkg/ipam/pool_selections.go, pkg/subnetmanager/subnet_manager.go, pkg/types/k8s.go
=> cherrypick 1768 to release-v0.5

pkg/ip/ip.go, pkg/ip/iprange.go
=> improve iprange function to reduce memory allocation

.github/workflows/auto-diff-k8s-ci.yaml, test/Makefile.defs
=> compatibility Testing for kubernetes v1.27

docs/concepts/annotation.md, docs/concepts/config.md, docs/usage/spider-subnet.md, docs/usage/statefulset.md, docs/usage/third-party-controller.md
robot cherry pick pr <https://github.com/spidernet-io/spiderpool/pull/1765> to branch release-v0.5,  action <https://github.com/spidernet-io/spiderpool/actions/runs/4945040018>  , commits 78553e56a690b2ce17f9ebf4243036ce0cdac3a3
=> title:	docs improvement

pkg/ip/ip.go, pkg/ip/iprange.go
robot cherry pick pr <https://github.com/spidernet-io/spiderpool/pull/1776> to branch release-v0.5,  action <https://github.com/spidernet-io/spiderpool/actions/runs/4945064487>  , commits 7a6f2a7cdefd23c9b9142d41fc748ec0db956a54
=> title:	improve iprange function to reduce memory allocation

test/doc/assignip.md, test/doc/cidr.md, test/doc/third-party-controller.md, test/e2e/common/spiderpool.go, test/e2e/kruise/kruise_test.go
=> E2E: Third party controller use case changes

test/e2e/common/constant.go, test/e2e/common/spiderpool.go, test/e2e/reclaim/reclaim_test.go, test/e2e/reliability/reliability_test.go
=> fix: check wbehook healthy ready for e2e

charts/spiderpool/templates/tls.yaml, cmd/spiderpool-controller/cmd/daemon.go, pkg/coordinatormanager/coordinator_mutate.go, pkg/coordinatormanager/coordinator_validate.go, pkg/coordinatormanager/coordinator_webhook.go
=> feat: Add SpiderCoordinator webhook

docs/usage/get-started-calico-zh_CN.md, docs/usage/get-started-calico.md
---
---
---
opt calico doc
https://github.com/spidernet-io/spiderpool/issues/1723
=> opt calico doc

docs/usage/get-started-calico-zh_CN.md, docs/usage/get-started-calico.md
robot cherry pick pr <https://github.com/spidernet-io/spiderpool/pull/1761> to branch release-v0.5,  action <https://github.com/spidernet-io/spiderpool/actions/runs/5009888875>  , commits 4ea3f69cea7af92f29681f5421ade723362a3db4
=> title:	opt calico doc

pkg/coordinatormanager/coordinator_informer.go
=> fix: CoordinatorController's member coordinatorName exists data race

charts/spiderpool/crds/spiderpool.spidernet.io_spidercoordinators.yaml, charts/spiderpool/templates/pod.yaml, charts/spiderpool/values.yaml, cmd/spiderpool-init/cmd/client.go, cmd/spiderpool-init/cmd/config.go, cmd/spiderpool-init/cmd/root.go, pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/spidercoordinator_types.go, test/Makefile, test/Makefile.defs
=> feat: Auto installation of default SpiderCoordinator

docs/usage/spider-subnet.md
=> fix: spider-subnet.md typo

docs/example/ippool-affinity-node/master-ipv4-ippool.yaml, docs/example/ippool-affinity-node/worker-ipv4-ippool.yaml, docs/usage/ippool-affinity-node.md
=> add gateway for ippool-affinity-node.md

pkg/constant/k8s.go, pkg/ippoolmanager/ippool_validate.go, pkg/ippoolmanager/ippool_webhook_test.go, vendor/k8s.io/apimachinery/pkg/apis/meta/v1/validation/validation.go, vendor/modules.txt
robot cherry pick pr <https://github.com/spidernet-io/spiderpool/pull/1806> to branch release-v0.5,  action <https://github.com/spidernet-io/spiderpool/actions/runs/5055503034>  , commits 6db113057954741f524581ab9de01037d48b3b8d
=> title:	add ippool podAffinity validation

docs/usage/spider-subnet.md
robot cherry pick pr <https://github.com/spidernet-io/spiderpool/pull/1796> to branch release-v0.5,  action <https://github.com/spidernet-io/spiderpool/actions/runs/5055509551>  , commits 113d27f78fbad63b0aa006f8fbcb0b1dae8a5694
=> title:	supplement spider subnet feature docs

docs/usage/gc.md, docs/usage/get-started-calico-zh_CN.md, docs/usage/get-started-calico.md, docs/usage/get-started-kind-zh_CN.md, docs/usage/get-started-kind.md, docs/usage/get-started-macvlan-zh_CN.md, docs/usage/get-started-macvlan.md, docs/usage/get-started-ovs-zh_CN.md, docs/usage/get-started-ovs.md, docs/usage/get-started-sriov-zh_CN.md, docs/usage/get-started-sriov.md, docs/usage/ippool-affinity-pod.md, docs/usage/ippool-multi.md, docs/usage/ipv6.md, docs/usage/multi-interfaces-annotation.md, docs/usage/performance-zh_CH.md, docs/usage/performance.md, docs/usage/route.md, docs/usage/spider-subnet.md, docs/usage/statefulset.md, docs/usage/third-party-controller.md
=> format markdown doc

cmd/spiderpool-agent/cmd/daemon.go, cmd/spiderpool-controller/cmd/daemon.go
robot cherry pick pr <https://github.com/spidernet-io/spiderpool/pull/1839> to branch release-v0.5,  action <https://github.com/spidernet-io/spiderpool/actions/runs/5118272446>  , commits 96a2175019d2ac596557c7f56ba2321131d1149c
=> title:	fix spiderpool-agent daemon data race

charts/spiderpool/templates/daemonset.yaml
---
---
---
opt spider-agent installtion
https://github.com/spidernet-io/spiderpool/issues/1846
=> opt spider-agent installtion

pkg/ippoolmanager/ippool_manager.go
I added the IPPool CR object resource version to log printer in order to troubleshooting.
=> add ippool resource version in ipam log

pkg/applicationcontroller/applicationinformers/utils_test.go
=> supplement unit test

pkg/coordinatormanager/coordinator_informer.go
=> fix: Remove legacy code of kubeadm-config

pkg/ippoolmanager/ippool_manager.go
robot cherry pick pr <https://github.com/spidernet-io/spiderpool/pull/1847> to branch release-v0.6,  action <https://github.com/spidernet-io/spiderpool/actions/runs/5131327193>  , commits f7551b27c235710343517ec34caf2ad836334bd0
=> title:	add ippool resource version in ipam log

cmd/coordinator/cmd/cni_types.go, cmd/coordinator/cmd/command_add.go, cmd/coordinator/cmd/utils.go
=> fix coordinator disable failure

docs/usage/gc-zh_CN.md, docs/usage/gc.md
- update english text in `gc.md`
- translate into Chinese
=> sync usage/gc.md

pkg/gcmanager/scanAll_IPPool.go, pkg/ipam/release.go, pkg/ippoolmanager/ippool_informer.go
=> improve log print

test/Makefile
e2e fix: gcAll field is incorrect
close #1865 
- none
=> e2e fix: gcAll field is incorrect

pkg/gcmanager/scanAll_IPPool.go
robot cherry pick pr <https://github.com/spidernet-io/spiderpool/pull/1883> to branch release-v0.5,  action <https://github.com/spidernet-io/spiderpool/actions/runs/5257037136>  , commits 46f8c7ff3fd22ee0ae2bf82d3d10b536ef9f87bc
=> title:	fix IP GC scan all running unhealthy

test/e2e/common/constant.go
https://github.com/spidernet-io/spiderpool/issues/1917
=> e2e fix: increase pod startup time

pkg/gcmanager/pod_cache.go
robot cherry pick pr <https://github.com/spidernet-io/spiderpool/pull/1906> to branch release-v0.6,  action <https://github.com/spidernet-io/spiderpool/actions/runs/5369245182>  , commits 104abb235130994492d884fdb0b4154be4f15a16
=> IP-GG: discarding tracing hostnetwork pod

test/Makefile, test/scripts/install-multus.sh
=> e2e: creating a subnet requires the subnet function to be enabled

charts/spiderpool/README.md, charts/spiderpool/values.yaml
=> disable subnet by default

pkg/ipam/config.go
=> in dual stack environment, support only ipv4 or ipv6 address

charts/spiderpool/README.md, charts/spiderpool/templates/configmap.yaml, charts/spiderpool/values.yaml
=> chart: change subnetDefaultFlexibleIPNumber location

charts/spiderpool/README.md, charts/spiderpool/templates/configmap.yaml, charts/spiderpool/values.yaml, cmd/spiderpool-agent/cmd/config.go, docs/concepts/config.md
=> chart: remove networkMode

charts/spiderpool/templates/daemonset.yaml, cmd/ifacer/Makefile, cmd/ifacer/cmd/cmd_add.go, cmd/ifacer/cmd/cmd_del.go, cmd/ifacer/cmd/types.go, cmd/ifacer/cmd/utils.go, cmd/ifacer/main.go, docs/concepts/ifacer.md, images/spiderpool-agent/Dockerfile, pkg/networking/networking/ip.go
---
---
---
feat: add support for subvlan
=> feat: add cni plugin ifacer

test/doc/subnet.md, test/e2e/subnet/subnet_test.go
=> e2e: Inconsistent ippool counts for subnets

pkg/ipam/allocate.go, test/e2e/annotation/annotation_test.go
currently, spec.vlan in spiderippool does not effect anything, so remove the check
=> no check for the vlan of ippool

charts/spiderpool/README.md, charts/spiderpool/templates/grafanaDashboard.yaml, charts/spiderpool/templates/multus-daemonset.yaml, charts/spiderpool/values.yaml, docs/develop/contributing.md, test/scripts/debugEnv.sh, test/scripts/install-default-cni.sh
=> chart: optimize

cmd/coordinator/cmd/command_add.go
This reverts commit 82620f98dfadaa598bed3605eb945c477372a927, reversing changes made to 0416bd617c27b449c02e0120bd3a8d98709d9219.
---
---
---
=> Revert "Merge branch 'release-v0.6' into main"

pkg/multuscniconfig/utils.go
=> fix coordinator spelling faults

cmd/ifacer/cmd/cmd_add.go
---
---
---
slave must be down if enslave to bond
=> slave must be down before creating bond

cmd/coordinator/cmd/command_del.go
=> fix type assert faults

docs/README-zh_CN.md
Fix a typesetting problem and a mixed Chinese and English problem
---
---
---
=> Fix a typesetting problem and a mixed Chinese and English problem

charts/spiderpool/README.md, charts/spiderpool/values.yaml
=> chart: enable dual-stack by default

.github/workflows/auto-diff-k8s-ci.yaml, .github/workflows/auto-nightly-ci.yaml, .github/workflows/auto-pr-ci.yaml, .github/workflows/call-release-image.yaml, .github/workflows/e2e-init.yaml, .github/workflows/lint-markdown.yaml, MAINTAINERS.md, test/Makefile, test/e2e/coordinator/macvlan-overlay-one/macvlan_overlay_one_test.go, test/e2e/kruise/kruise_test.go, test/e2e/reservedip/reservedip_test.go
**What this PR does / why we need it:**
1. Correct some mismatched information in MAINTAINERS.md
2. Optimize CI and support multiple modes of operation
3. Change some obsolete methods like set-output
4. optimize e2e
=> e2e: optimize ci and e2e

test/e2e/common/mode.go, test/e2e/coordinator/macvlan-overlay-one/macvlan_overlay_one_test.go
=> set testIPv6 to false for cilium mode

test/e2e/annotation/annotation_test.go
fix #2016 
The ipv6 address on the network interface will be abbreviated. For example fd00:0c3d::2 becomes fd00:c3d::2.
Abbreviate the expected ipv6 address and use it in subsequent assertions.
=> fix e2e: The ipv6 address is abbreviated and the expected IP address cannot be found

test/e2e/subnet/subnet_test.go
=> fix e2e: delete the subnet, prompting that the subnet does not exist

CODEOWNERS, CODE_OF_CONDUCT.md, README-zh_CN.md, README.md, docs/README-zh_CN.md, docs/README.md
- Add cncf logo in README
- Add a file: code of conduct to follow cncf style
- Fix links, minor changes about `Pod` and spaces
- Provide a newline char around col 80-120, easy to recognize changes in future PR
=> add cncf logo in README and add code-of-conduct.md

docs/README-zh_CN.md
=> improve README-zh_CN.md

pkg/statefulsetmanager/utils.go, pkg/utils/string/string.go, pkg/workloadendpointmanager/utils_test.go, pkg/workloadendpointmanager/workloadendpoint_manager_suite_test.go, pkg/workloadendpointmanager/workloadendpoint_manager_test.go, tools/k8s-controller-gen/update-controller-gen.sh, tools/scripts/update-codegen.sh
=> header license

cmd/coordinator/cmd/utils.go, pkg/networking/networking/ip.go, pkg/networking/networking/mac.go
---
---
---
cleanup dirty rule、route、neigh tables in cmdAdd, Make sure dirty tables doesn't interfere with new pod, but note that the cleanup is only as much as possible, and if it can't be deleted or fails, we'll just log warnings but won't return errors.
=> cleanup dirty rule、route、neigh tables in cmdAdd

docs/concepts/allocation.md
=> implement IP allocation process document

cmd/coordinator/cmd/command_del.go
---
---
---
coordinator: cmdDel should return nil, and change logger to logger.Sugar()...(Or we can't fetch the log message)
#2061 
=> coordinator: cmdDel should return nil

charts/spiderpool/crds/spiderpool.spidernet.io_spiderippools.yaml, pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/spiderippool_types.go
=> fix IPPool crd wrong vlanID range

pkg/ippoolmanager/ippool_mutate.go, pkg/ippoolmanager/ippool_webhook_test.go, test/e2e/annotation/annotation_test.go
robot cherry pick pr <https://github.com/spidernet-io/spiderpool/pull/2036> to branch release-v0.5,  action <https://github.com/spidernet-io/spiderpool/actions/runs/5641125651>  , commits 06a50d78fc24f7fe56e4a0d1c84a249d0c50d785
=> title:	ippool inherits subnet properties 

charts/spiderpool/crds/spiderpool.spidernet.io_spidermultusconfigs.yaml, docs/concepts/spiderendpoint.md, docs/concepts/spiderippool.md, docs/concepts/spidermultusconfig.md, docs/concepts/spiderreservedip.md, docs/concepts/spidersubnet.md, pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/spidermultus_types.go
1. update outdated CRD document
2. optimize SpiderMultusConfig CRD (the original field is long to be hard for writing)
update docs
close #1903
=> update CRD documentation

test/e2e/common/constant.go
=> e2e fix: increase check time for multus cr rebuilds.

test/e2e/coordinator/macvlan-overlay-one/macvlan_overlay_one_test.go
fix #2070  and increase PodCIDRType for coordinator
=> e2e: fix ipv6 address abbreviation and supplement PodCIDRType for coordinator spec

charts/spiderpool/templates/tls.yaml, pkg/coordinatormanager/coordinator_validate.go
There's a bug in the SpiderMultusConfig ValidatingWebhookConfiguration 
fix bug
close #2066 
close #2081
=> fix SpiderMultusConfig ValidatingWebhookConfiguration

test/e2e/coordinator/macvlan-overlay-one/macvlan_overlay_one_test.go
=> e2e fix: the conflicting IP address cannot be the IP of the gateway or NIC

test/scripts/install-default-cni.sh
update cilium field ipam.operator.clusterPoolIPv4PodCIDR to ipam.operator.clusterPoolIPv4PodCIDRList
fix #2084  #2086
=> update cilium field ipam.operator.clusterPoolIPv4PodCIDR to ipam.operator.clusterPoolIPv4PodCIDRList

.github/workflows/lint-doc.yaml, .gitignore, Makefile, README-zh_CN.md, README.md, docs/README-zh_CN.md, docs/README.md, docs/concepts/metrics.md, docs/mkdocs.yml
=> ci: check document

charts/spiderpool/crds/spiderpool.spidernet.io_spidersubnets.yaml, pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/spidersubnet_types.go, pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/zz_generated.deepcopy.go
fix SpiderSubnet CRD vlanID range
=> fix SpiderSubnet CRD vlanID

docs/mkdocs.yml, docs/reference/crd-spidercoordinator.md, docs/usage/coordinator-zh_CN.md, docs/usage/ifacer-zh_CN.md, docs/usage/ifacer.md, docs/usage/install/overlay/get-started-calico-zh_cn.md, docs/usage/install/overlay/get-started-cilium-zh_cn.md, docs/usage/install/underlay/get-started-sriov-zh_CN.md, docs/usage/install/underlay/get-started-sriov.md
---
---
---
docs: coordinator config
=> docs: coordinator config

docs/usage/coordinator-zh_CN.md, docs/usage/install/underlay/get-started-sriov-zh_CN.md, docs/usage/install/underlay/get-started-sriov.md
---
---
---
update sriov get-started and coordinator docs
=> update sriov get-started and coordinator docs

cmd/coordinator/cmd/utils.go
previous log is not easy to understand
=> optimize the coordinator log

.github/workflows/auto-cherrypick.yaml, cmd/coordinator/cmd/utils.go
=> ci: bug for cherry pick

tools/scripts/cleanCRD.sh
spidercoordinators & spidermultusconfigs
---
---
---
=> fix:Missing resource type in cleanCRD scripts

docs/usage/install/underlay/get-started-sriov-zh_CN.md
---
---
---
docs: update get-started-sriov-zh_CN.md
https://github.com/spidernet-io/spiderpool/issues/2132
=> docs: update get-started-sriov-zh_CN.md

docs/reference/crd-spidercoordinator.md, docs/usage/coordinator-zh_CN.md
---
---
---
docs: update coordinator-zh_CN.md
https://github.com/spidernet-io/spiderpool/issues/2129
=> docs: update coordinator-zh_CN.md

cmd/coordinator/cmd/utils.go
while spiderpool only in v4 or v6 family on a dual-stack cluster
---
---
---
We need to make sure that the gateway and DST must be the same IP family. If not, we do not add this route.
https://github.com/spidernet-io/spiderpool/issues/2125
=> coordinator: fix failed to setupHijackRoutes 

cmd/spiderpool-agent/cmd/coordinator.go, pkg/coordinatormanager/calico_ippool_informer.go, pkg/coordinatormanager/coordinator_informer.go
---
---
---
- clean up spidercoordinator.status if phase is NotReady
- return error if spidercoordinator.phase is NotReady
https://github.com/spidernet-io/spiderpool/issues/2128
=> clean up spidercoordinator.status if phase is NotReady

cmd/coordinator/cmd/utils.go
robot cherry pick pr <https://github.com/spidernet-io/spiderpool/pull/2148> to branch release-v0.6,  action <https://github.com/spidernet-io/spiderpool/actions/runs/5784452049>  , commits 001c091bf4ffd984eb40302f92e8b518d8f482c6
=> title:	coordinator: fix failed to setupHijackRoutes 

pkg/multuscniconfig/utils.go, test/doc/spidermultus.md
---
---
---
spidermultusconfig: remove redundant field "resourceName"
https://github.com/spidernet-io/spiderpool/issues/2133
=> spidermultusconfig: remove redundant field "resourceName"

pkg/coordinatormanager/coordinator_informer.go
---
---
---
typo: make spidercoordinator.status.phase uppercase
https://github.com/spidernet-io/spiderpool/actions/runs/5792045706/job/15697905012
=> typo: make spidercoordinator.status.phase uppercase

charts/spiderpool/crds/spiderpool.spidernet.io_spiderendpoints.yaml, docs/reference/crd-spidermultusconfig.md, docs/reference/crd-spidersubnet.md, pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/spiderendpoint_types.go, test/e2e/subnet/subnet_test.go
fix wrong SpiderEndpoint vlan ID number  and other wrong vlan ID codes&docs
fix bug
close https://github.com/spidernet-io/spiderpool/issues/2059
=> fix wrong SpiderEndpoint vlan ID number 

cmd/spiderpool-agent/cmd/coordinator.go, pkg/coordinatormanager/calico_ippool_informer.go, pkg/coordinatormanager/coordinator_informer.go
robot cherry pick pr <https://github.com/spidernet-io/spiderpool/pull/2152> to branch release-v0.6,  action <https://github.com/spidernet-io/spiderpool/actions/runs/5792001446>  , commits aeb38b43585c447ca073ed1fe6ad6b0e6ec2baff
=> title:	clean up spidercoordinator.status if phase is NotReady

charts/spiderpool/crds/spiderpool.spidernet.io_spiderendpoints.yaml, docs/reference/crd-spidermultusconfig.md, docs/reference/crd-spidersubnet.md, pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/spiderendpoint_types.go, test/e2e/subnet/subnet_test.go
robot cherry pick pr <https://github.com/spidernet-io/spiderpool/pull/2160> to branch release-v0.6,  action <https://github.com/spidernet-io/spiderpool/actions/runs/5796904460>  , commits 57b780eecdf3e30736ea0e210d3befbc7a7eeedc
=> title:	fix wrong SpiderEndpoint vlan ID number 

.github/workflows/e2e-init.yaml, Makefile, test/Makefile
Add cleanup check in CI
#2154
```
None
```
=> add clean for CI

pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/types_string.go
robot cherry pick pr <https://github.com/spidernet-io/spiderpool/pull/2172> to branch release-v0.6,  action <https://github.com/spidernet-io/spiderpool/actions/runs/5817864067>  , commits 81eec5f0aba1e5222731993acba85bfe0fc225ca
=> title:	fix potential panic with CRD string method

docs/usage/install/cloud/get-started-alibaba-zh_CN.md, docs/usage/install/cloud/get-started-alibaba.md
=> doc: add en get-started-alibaba

pkg/applicationcontroller/applicationinformers/utils.go
robot cherry pick pr <https://github.com/spidernet-io/spiderpool/pull/2177> to branch release-v0.6,  action <https://github.com/spidernet-io/spiderpool/actions/runs/5823809238>  , commits 7de69b165a7f794e39dc13c073c3c9d75c816e22
=> title:	optimize the autopool name length to 253

test/doc/assignip.md, test/doc/coordinator.md, test/doc/ifacer.md, test/doc/ippoolcr.md, test/doc/spidercoodinator.md, test/doc/spidermultus.md
=> new features e2e supplement

test/doc/reliability.md
add e2e for spiderpool
```
None
```
=> e2e: add spiderpool controller active/standby

docs/usage/install/overlay/get-started-calico-zh_cn.md, docs/usage/install/overlay/get-started-calico.md
=> doc: add en get-started-calico

test/e2e/common/ips.go, test/e2e/common/spiderpool.go, test/e2e/common/spidersubnet.go, test/e2e/coordinator/macvlan-overlay-one/macvlan_overlay_one_test.go, test/scripts/debugEnv.sh
=> fix IP overlap that occurs with low probability

docs/usage/install/overlay/get-started-calico.md, docs/usage/install/overlay/get-started-cilium-zh_cn.md, docs/usage/install/overlay/get-started-cilium.md
=> doc: add en get-started -cilium

pkg/ipam/pool_selections.go
=> orphan pod skip SpiderSubnet feature

.github/workflows/build-image-latest.yaml, .github/workflows/call-release-image.yaml
=> ci: build latest image

docs/usage/network-topology-zh_CN.md, docs/usage/spider-subnet-zh_CN.md
add some usage for spiderpool
```
None
```
=> [docs]: add some usage of spiderpool

pkg/multuscniconfig/multusconfig_informer.go
robot cherry pick pr <https://github.com/spidernet-io/spiderpool/pull/2225> to branch release-v0.6,  action <https://github.com/spidernet-io/spiderpool/actions/runs/5964232690>  , commits 8fa4b81879c936588924e3aa8a6e95ed784984fc
=> fix SpiderMultusConfig potential panic

cmd/coordinator/cmd/cni_types.go, cmd/coordinator/cmd/command_add.go, cmd/coordinator/cmd/utils.go, docs/mkdocs.yml, docs/reference/plugin-coordinator.md, pkg/networking/networking/route.go, test/doc/coordinator.md
---
---
---
coordinator: 
- make all host rule tables exist in Table 500
- remove dependencies on NIC prefixes
https://github.com/spidernet-io/spiderpool/issues/2161
https://github.com/spidernet-io/spiderpool/issues/2202
=> coordinator: make all host rule tables exists in table 500

test/doc/coordinator.md, test/doc/ifacer.md, test/doc/ippoolcr.md, test/doc/spidermultus.md
support multiple versions of documents
```
None
```
=> e2e docs changes

.github/workflows/call-release-doc.yaml, docs/mkdocs.yml, docs/overrides/main.html
support multiple versions of documents
#2215 
```
mike deploy --push --update-aliases 0.6.0 latest
mike set-default --push latest
mike deploy --push --update-aliases 0.7.0 latest
```
=> support multiple versions of documents

.github/workflows/call-release-doc.yaml
=> fix docs logs

.github/workflows/auto-version-release.yaml, .github/workflows/call-update-githubpages.yaml
Use mike to construct the version, no artifact exists
=> Use mike to construct the version, no artifact exists

.github/workflows/call-release-doc.yaml
=> CI: fix invalid path

.github/workflows/auto-version-release.yaml, .github/workflows/call-release-changelog.yaml, .github/workflows/call-release-chart.yaml, .github/workflows/call-release-doc.yaml, .github/workflows/call-update-githubpages.yaml, docs/mkdocs.yml
The automatic publishing process needs to merge and submit the products of chart and documents. Create products based on the original
=> Fix automatic publishing document version failure

.github/workflows/auto-version-release.yaml, .github/workflows/call-release-changelog.yaml, .github/workflows/call-release-chart.yaml, .github/workflows/call-release-doc.yaml, .github/workflows/call-update-githubpages.yaml, docs/mkdocs.yml, docs/overrides/main.html
=> rebase main 

api/v1/agent/openapi.yaml, api/v1/agent/server/embedded_spec.go, cmd/spiderpool-agent/cmd/coordinator.go, pkg/coordinatormanager/coordinator_validate.go
The coordinator ignored one PodCIDRType "none"
=> fix coordinator webhook

.github/workflows/call-release-changelog.yaml, .github/workflows/call-release-chart.yaml, .github/workflows/ci-image-gc-by-pr.yaml, docs/mkdocs.yml
repair document template
```
NONE
```
```
NONE
```
=> repair document template

charts/spiderpool/README.md, charts/spiderpool/values.yaml
=> set chart enableSpiderSubnet to be true

docs/develop/roadmap.md
=> roadmap: submariner

docs/usage/install/underlay/get-started-ovs-zh_CN.md, docs/usage/install/underlay/get-started-ovs.md, docs/usage/install/underlay/get-started-sriov-zh_CN.md, docs/usage/install/underlay/get-started-sriov.md, docs/usage/spider-subnet.md
Optimize the format of some document sites.
#2311 
```
NONE
```
=> [docs]: optimize doc format for spiderpool

cmd/spiderpool-init/cmd/config.go, pkg/coordinatormanager/coordinator_mutate.go, pkg/coordinatormanager/coordinator_validate.go, pkg/ip/ip.go, pkg/ip/ip_test.go, test/scripts/install-multus.sh
---
---
---
This PR allows set IP address to hijackCIDR, you can set it as a netip or a cidr
https://github.com/spidernet-io/spiderpool/issues/2223
=> spidercoordinator: allow set ip addr to hijackCIDR

pkg/ipam/pool_selections.go
=> update codes comments

test/e2e/affinity/affinity_test.go, test/e2e/annotation/annotation_test.go, test/e2e/assignip/assignip_test.go, test/e2e/common/constant.go, test/e2e/common/deployment.go, test/e2e/ippoolcr/ippoolcr_test.go, test/e2e/kruise/kruise_test.go, test/e2e/performance/performance_test.go, test/e2e/reclaim/reclaim_test.go, test/e2e/reliability/reliability_test.go, test/e2e/reservedip/reservedip_test.go, test/e2e/spidermultus/spidermultus_test.go, test/e2e/subnet/subnet_test.go, test/scripts/debugEnv.sh
add large-scale case for spiderpool
=> add large-scale case for spiderpool

README-zh_CN.md, docs/README-zh_CN.md, docs/usage/statefulset-zh_CN.md, docs/usage/statefulset.md
[docs]: add statefulset usage docs for spiderpool
```
NONE
```
=> [docs]: add statefulset usage docs for spiderpool

docs/usage/install/upgrade.md
```
Provide a way to upgrade
```
```
NONE
```
=> Upgrade spiderpool from (<=0.6.0) to 0.7.0

docs/usage/coordinator-zh_CN.md, docs/usage/coordinator.md
=> doc: add en coordinator

docs/usage/reserved-ip-zh_CN.md, docs/usage/reserved-ip.md
=> doc: add en reserved-ip

docs/usage/install/cloud/get-started-alibaba-zh_CN.md
[docs]: update alibaba docs for spiderpool
```
NONE
```
=> [docs]: update alibaba docs for spiderpool

test/scripts/debugEnv.sh
Add debug logs for ip n on the host
```
NONE
```
=> Add debug logs for ip n on the host

docs/usage/reserved-ip.md, docs/usage/spider-subnet-zh_CN.md, docs/usage/spider-subnet.md
=> doc: add en spidersubnet

pkg/applicationcontroller/app_controller.go, pkg/applicationcontroller/app_controller_test.go, pkg/applicationcontroller/applicationcontroller_suite_test.go, pkg/podmanager/pod_manager.go, pkg/podmanager/pod_manager_test.go
robot cherry pick pr <https://github.com/spidernet-io/spiderpool/pull/2370> to branch release-v0.6,  action <https://github.com/spidernet-io/spiderpool/actions/runs/6438758893>  , commits 9cf02c49f1fd08291ea7718f6c0b64ac369d0399
=> improve GetTopController method

.github/workflows/auto-version-release.yaml, .github/workflows/call-release-chart.yaml, .github/workflows/call-release-doc.yaml
fix the problem that the rc version cannot generate artifact.
#2373
Fix product issues while decoupling workflows
=> fix the problem that the rc version cannot generate artifact.

docs/concepts/allocation-zh_CN.md, docs/concepts/allocation.md, docs/mkdocs.yml, docs/usage/spider-affinity-zh_CN.md, docs/usage/spider-affinity.md, docs/usage/spider-multus-config-zh_CN.md, docs/usage/spider-multus-config.md
[docs]: add some usage and concepts for spiderpool
```
None
```
=> [docs]: add some usage and concepts for spiderpool

docs/usage/statefulset-zh_CN.md, docs/usage/statefulset.md
=> doc: add en statefulset

.github/workflows/auto-version-release.yaml, .github/workflows/call-release-chart.yaml
robot cherry pick pr <https://github.com/spidernet-io/spiderpool/pull/2403> to branch release-v0.7,  action <https://github.com/spidernet-io/spiderpool/actions/runs/6482471856>  , commits a09eba4828a45bf6059845650dd16b99b7535bec
=> Fix ci calling release-chart error

docs/usage/rdma-zh_CN.md, docs/usage/rdma.md
=> doc: add en rdma

.github/PULL_REQUEST_TEMPLATE.md
Fix invalid link in PULL_REQUEST_TEMPLATE.md
=> Fix invalid link in PULL_REQUEST_TEMPLATE.md

README-zh_CN.md, README.md
=> doc: update readme

docs/usage/install/underlay/get-started-sriov-zh_CN.md, docs/usage/install/underlay/get-started-sriov.md
=> doc: update en sriov

README-zh_CN.md, README.md, docs/README-zh_CN.md, docs/README.md
=> doc: update doc/readme

.github/workflows/e2e-init.yaml, Makefile, test/Makefile, test/Makefile.defs, test/e2e/coordinator/macvlan-overlay-one/macvlan_overlay_one_test.go, test/e2e/coordinator/macvlan-underlay-one/macvlan_underlay_one_test.go, test/scripts/install-default-cni.sh, test/scripts/install-multus.sh
test macvlan work with cilium without kube-proxy.
---
---
---
CI: run cilium without kube-proxy
=> CI: run cilium without kube-proxy

test/e2e/kubevirt/kubevirt_test.go
reference: https://github.com/spidernet-io/spiderpool/issues/2460
=> pending e2e kubevirt Passt with IPv6-only case

README-zh_CN.md, README.md, docs/concepts/arch-zh_CN.md, docs/concepts/arch.md, docs/develop/contributing.md, docs/usage/readme-zh_CN.md, docs/usage/readme.md
update en docs for readme, usage/readme and arch based on #2458
=> en doc: update readme and arch based on pr#2458

docs/usage/spider-affinity-zh_CN.md, docs/usage/spider-affinity.md
=> doc: add en affinity

.github/workflows/auto-cherrypick.yaml, .github/workflows/build-image-plugins.yaml, test/Makefile, test/Makefile.defs, test/scripts/install-kubevirt.sh, tools/scripts/changelog.sh
https://github.com/spidernet-io/spiderpool/issues/2479
=> ci: retry  for curl

cmd/coordinator/cmd/command_add.go, cmd/coordinator/cmd/utils.go, pkg/networking/networking/route.go, test/doc/coordinator.md, test/scripts/install-multus.sh
we could make sure the source of the traffic forwarded via veth0 is from eth0, It makes sense in multui-nic case.
---
---
---
we could make sure the source of the traffic forwarded via veth0 is from eth0, It makes sense in multui-nic case.
https://github.com/spidernet-io/spiderpool/issues/2422
=> coordinator: fix the eth0 source IP for the packet going through veth0

docs/usage/install/cloud/get-started-aws-zh_CN.md, docs/usage/install/cloud/get-started-aws.md
=> doc: add en aws doc

.github/workflows/call-release-chart.yaml
Fix chart file cannot be found
=> Fix chart file cannot be found

test/e2e/common/constant.go, test/e2e/ifacer/ifacer_test.go
---
---
---
https://github.com/spidernet-io/spiderpool/issues/2502
=> CI: fix ifacer e2e case

test/e2e/coordinator/macvlan-overlay-one/macvlan_overlay_one_test.go, test/e2e/ifacer/ifacer_test.go, test/e2e/performance/performance_test.go
---
---
---
CI: don't run node reboot case for ifacer
https://github.com/spidernet-io/spiderpool/issues/2512
https://github.com/spidernet-io/spiderpool/issues/2502
=> CI: don't run node reboot case for ifacer

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/ci-failure.md, .github/ISSUE_TEMPLATE/doc.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/usage.md, .github/PULL_REQUEST_TEMPLATE.md
=> Use github forms for issue templates

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/ci-failure.md, .github/ISSUE_TEMPLATE/doc.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/usage.md
=> fix github issue forms

.github/workflows/e2e-init.yaml
=> ci: upload badge

cmd/spiderpool-controller/cmd/runtime_status.go
fix bug
close https://github.com/spidernet-io/spiderpool/issues/2533
=> spiderpool-controller readiness health check failure

.github/ISSUE_TEMPLATE/doc.yaml, .github/workflows/e2e-init.yaml
=> fix judgment on spiderpoolperformance.json file

charts/spiderpool/templates/daemonset.yaml
=> add downward API for spiderpool-agent to get pod name and namespace

docs/usage/route-zh_CN.md, docs/usage/route.md
=> doc: update en route

docs/usage/spider-ippool-zh_CN.md, docs/usage/spider-ippool.md
=> doc: add en ippool

docs/usage/kubevirt-zh_CN.md, docs/usage/kubevirt.md
=> doc: add en kubevirt

docs/usage/statefulset-zh_CN.md, docs/usage/statefulset.md
=> statefulset doc

.github/workflows/call-release-chart.yaml
=> rebase call-release-chart

.github/workflows/call-release-doc.yaml
- kind/doc
Supports the latest branch and can generate development documents. The design is as follows:
In the github interface, you can pass in the parameter main to determine whether your document is published as the latest.If the value is main, development documentation will be generated based on the main branch. Its format is dev (main)，If the value is not main, it will be triggered based on tag.
Fixes #2482
=> Publish development documents through github actions.

.github/workflows/auto-cherrypick.yaml, .github/workflows/auto-diff-k8s-ci.yaml
=> CI: use GITHUB.TOKEN to operate github

docs/mkdocs.yml, docs/usage/readme.md
- release/bug 
- kind/doc
Fixes #2578 
=> docs: add kind to the document navigation bar

docs/usage/underlay_cni_service-zh_CN.md, docs/usage/underlay_cni_service.md
=> docs: fix the md format

test/e2e/kubevirt/kubevirt_test.go
=> e2e: pending e2e case F00002

docs/usage/install/underlay/get-started-sriov-zh_CN.md, docs/usage/install/underlay/get-started-sriov.md
=> docs: Update sriov's pfNames field

docs/usage/ifacer-zh_CN.md, docs/usage/ifacer.md, docs/usage/install/cloud/get-started-aws-zh_CN.md, docs/usage/install/cloud/get-started-aws.md, docs/usage/install/overlay/get-started-calico-zh_cn.md, docs/usage/install/overlay/get-started-calico.md, docs/usage/install/overlay/get-started-cilium-zh_cn.md, docs/usage/install/overlay/get-started-cilium.md, docs/usage/install/underlay/get-started-ovs-zh_CN.md, docs/usage/install/underlay/get-started-ovs.md, docs/usage/spider-affinity-zh_CN.md, docs/usage/spider-affinity.md
- kind/doc
docs: cleanup ipversion to simplify yaml
Fixes #
=> docs: cleanup ipversion to simplify yaml

docs/concepts/io-performance-zh_CN.md
=> docs: add spiderpool io performance

docs/mkdocs.yml
=> docs: add aws to the document navigation bar

docs/concepts/ipam-performance-zh_CN.md, docs/concepts/ipam-performance.md
=> docs: update spiderpool IPAM performance

docs/concepts/io-performance.md
=> docs: Add en doc for io performance

docs/concepts/ipam.md, docs/usage/readme-zh_CN.md, docs/usage/readme.md
=> fix document wrong links

docs/usage/underlay_cni_service-zh_CN.md, docs/usage/underlay_cni_service.md
=> docs: format doc

docs/mkdocs.yml, docs/usage/install/upgrade.md, docs/usage/readme-zh_CN.md, docs/usage/readme.md, docs/usage/service-zh_CN.md, docs/usage/service.md, docs/usage/underlay_cni_service-zh_CN.md
=> docs: format upgrade doc and error link

test/Makefile
aims to be more likely to trigger bug related to GC
Fixes #2541
=> e2e: Change the gc interval to 30s

.github/workflows/auto-nightly-ci.yaml, .github/workflows/auto-pr-ci.yaml, .github/workflows/e2e-init.yaml
Fixes #[2503](https://github.com/spidernet-io/spiderpool/issues/2503)
=> e2e: Add a new job to test low kernels in e2e

docs/concepts/io-performance-zh_CN.md, docs/concepts/io-performance.md, docs/usage/underlay_cni_service-zh_CN.md, docs/usage/underlay_cni_service.md
=> docs: fix performance value units

test/scripts/debugEnv.sh
Fixes The third point of #2485
=> fix invaild debug log

test/Makefile.defs, test/scripts/install-default-cni.sh
=> e2e: Support calico version use the latest

charts/spiderpool/templates/tls.yaml, pkg/constant/k8s.go, pkg/coordinatormanager/coordinator_mutate.go, pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/spidercoordinator_types.go, pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/spidermultus_types.go, pkg/multuscniconfig/multusconfig_informer.go, pkg/multuscniconfig/multusconfig_mutate.go, pkg/multuscniconfig/multusconfig_webhook.go, test/Makefile.defs, test/scripts/install-multus.sh, test/scripts/prepare.sh
- kind/cleanup
spidermultusconfig: set default value if it not set
Fixes https://github.com/spidernet-io/spiderpool/issues/2430
=> spidermultusconfig: set default value if it not set

docs/usage/install/cloud/get-started-alibaba-zh_CN.md, docs/usage/install/cloud/get-started-aws-zh_CN.md, docs/usage/install/overlay/get-started-calico-zh_cn.md, docs/usage/install/overlay/get-started-cilium-zh_cn.md, docs/usage/install/underlay/get-started-calico-zh_CN.md, docs/usage/install/underlay/get-started-macvlan-zh_CN.md, docs/usage/install/underlay/get-started-ovs-zh_CN.md, docs/usage/install/underlay/get-started-sriov-zh_CN.md, docs/usage/install/underlay/get-started-weave-zh_CN.md, docs/usage/kubevirt-zh_CN.md, docs/usage/network-topology-zh_CN.md, docs/usage/rdma-zh_CN.md
=> docs: Fix description when `multus.multusCNI.defaultCniCRName` is empty.

test/scripts/install-tools.sh
=> Add a script to install yq

test/scripts/install-tools.sh
=> e2e: Tips for installing development tools

docs/usage/egress-zh_CN.md, docs/usage/egress.md, docs/usage/install/underlay/get-started-macvlan.md, docs/usage/spider-ippool-zh_CN.md
=> docs: add egress docs for spiderpool

cmd/ifacer/cmd/cmd_add.go
- kind/bug
- release/bug 
Fix the slave with bond was not set if vlanId was set to 0
Fixes https://github.com/spidernet-io/spiderpool/issues/2638
=> ifacer: Fix the slave with bond was not set if vlanId was set to 0

README.md
=> add performance figures

charts/spiderpool/crds/spiderpool.spidernet.io_spidermultusconfigs.yaml, docs/reference/crd-spidermultusconfig.md, docs/usage/spider-multus-config-zh_CN.md, docs/usage/spider-multus-config.md, pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/spidermultus_types.go, pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/zz_generated.deepcopy.go, pkg/multuscniconfig/multusconfig_informer.go, pkg/multuscniconfig/multusconfig_mutate.go, pkg/multuscniconfig/multusconfig_validate.go, pkg/multuscniconfig/utils.go
- kind/feature
- 
It's able to configure bandwidth for sriov config.
Fixes #
=> spidermultusconfig: It's able to configure bandwidth for sriov config

.github/workflows/e2e-init.yaml
=> CI: Variables such as kdoctor are only triggered in CI

docs/concepts/coordinator-zh_CN.md, docs/concepts/coordinator.md, docs/reference/plugin-ifacer.md, docs/usage/install/underlay/get-started-kind-zh_CN.md, docs/usage/install/underlay/get-started-kind.md, docs/usage/install/underlay/get-started-macvlan-zh_CN.md, docs/usage/install/underlay/get-started-macvlan.md, docs/usage/install/underlay/get-started-ovs-zh_CN.md, docs/usage/install/underlay/get-started-ovs.md, docs/usage/install/underlay/get-started-sriov-zh_CN.md, docs/usage/install/underlay/get-started-sriov.md
- kind/doc
NetworkManager may interfere with network interfaces created through coordinator or Ifacer. We should configure NetworkManager to prevent its interference.
Fixes https://github.com/spidernet-io/spiderpool/issues/2657
=> docs: Fix NetworkManager manager ifacer's interface

charts/spiderpool/Chart.yaml
=> fix charts version typo

test/Makefile.defs
=> update kdoctor version to v0.2.1

README-zh_CN.md, README.md, docs/README-zh_CN.md, docs/README.md
=> Update status of network policy support in roadmap

README-zh_CN.md, README.md, docs/README-zh_CN.md, docs/README.md
=> optimize readme

README-zh_CN.md, README.md, docs/README-zh_CN.md, docs/README.md, docs/mkdocs.yml, docs/usage/install/underlay/get-started-kind-zh_CN.md, docs/usage/install/underlay/get-started-kind.md
=> optimize doc

.github/workflows/call-release-doc.yaml
=> Supports publishing rc and .z versions of docs to dev

charts/spiderpool/templates/pod.yaml, cmd/spiderpool-init/cmd/config.go, cmd/spiderpool-init/cmd/multus.go
- release/bug 
don't update multus configMap if multus don't install
Fixes #
=> don't update multus configMap if multus don't install

.github/workflows/e2e-init.yaml
1. Missing debug logs on different kernel versions.
2. Add kernel flags to facilitate debugging failures in low-kernel scenarios.
close #2769
=> Missing debug logs on different kernel versions.

docs/concepts/arch.md
update arch.md doc
- kind/doc
Fixes #
=> update arch.md doc

docs/usage/cilium-chaining-zh_CN.md, docs/usage/cilium-chaining.md, docs/usage/install/get-started-kind-zh_CN.md, docs/usage/install/get-started-kind.md, docs/usage/rdma-zh_CN.md
=> docs: Optimize and typo

test/doc/coordinator.md, test/doc/spidermultus.md, test/e2e/spidermultus/spidermultus_test.go
=> e2e: Set sriov.enable Rdma to true and see if multus nad has rdma

pkg/applicationcontroller/app_controller.go, pkg/ipam/pool_selections.go
=> support spidersubnet single IP in dual stack

docs/mkdocs.yml, docs/usage/install/get-started-kind-zh_CN.md, docs/usage/install/get-started-kind.md
=> update quick start

docs/README-zh_CN.md, docs/usage/install/underlay/get-started-macvlan-zh_CN.md, docs/usage/install/underlay/get-started-macvlan.md, docs/usage/readme-zh_CN.md, docs/usage/readme.md
=> docs optimization

docs/usage/install/get-started-kind-zh_CN.md, docs/usage/install/get-started-kind.md, docs/usage/readme-zh_CN.md, docs/usage/readme.md
update quick start
update quick start
update quick start
Fixes #
=> udpate get-started

AUTHORS
=> docs: update AUTHORS

docs/mkdocs.yml, docs/usage/operator-zh_CN.md, docs/usage/operator.md, docs/usage/readme-zh_CN.md, docs/usage/readme.md, docs/usage/spider-subnet-zh_CN.md, docs/usage/spider-subnet.md, docs/usage/third-party-controller-zh_CN.md, test/Makefile
=> optimize k8s extended operator document title

MAINTAINERS.md, README-zh_CN.md, README.md, docs/README-zh_CN.md, docs/README.md
=> doc: add community

MAINTAINERS.md, README-zh_CN.md, README.md, docs/README-zh_CN.md, docs/README.md
=> update community 

README-zh_CN.md, README.md, docs/README-zh_CN.md, docs/README.md
update governance document link
Fixes #
=> update governance document link

pkg/networking/networking/route.go
robot cherry pick PR <https://github.com/spidernet-io/spiderpool/pull/2919> from cyclinder,to branch release-v0.9,  action <https://github.com/spidernet-io/spiderpool/actions/runs/7219445069>  , commits fe936b58b0b429add7133513312d72e20ac2483b
=> coordinator: improve determining the default route for IPv6

test/e2e/coordinator/macvlan-underlay-one/macvlan_underlay_one_test.go
=> fix merge conflict

pkg/coordinatormanager/coordinator_informer.go
robot cherry pick PR <https://github.com/spidernet-io/spiderpool/pull/2929> from cyclinder,to branch release-v0.9,  action <https://github.com/spidernet-io/spiderpool/actions/runs/7248567810>  , commits dccff4028fb1116a465878807870c68eaaabcafb
=> spidercoordinator: It should update the status to NotReady if any errors occur

docs/usage/rdma-ib-zh_CN.md, docs/usage/rdma-ib.md, docs/usage/rdma-roce-zh_CN.md, docs/usage/rdma-roce.md
=> doc: update sriov note

.github/workflows/e2e-init.yaml
=> Warning caused by modifying invalid usage

.github/workflows/auto-cherrypick.yaml
=> Add signoff to cherry pick robot

README-zh_CN.md, README.md, docs/README-zh_CN.md, docs/README.md
https://github.com/cncf/foundation/blob/main/website-guidelines.md
=> website requirement for sandbox

docs/usage/faq-zh_CN.md, docs/usage/faq.md
=> supplement troubleshoot documents

test/doc/assignip.md, test/e2e/assignip/assignip_test.go
=> supplement assign IP e2e

test/doc/ippoolcr.md, test/e2e/ippoolcr/ippoolcr_test.go
=> supplement IPPool CR e2e

.github/workflows/auto-cherrypick.yaml
fatal: the receiving end does not support --signed push
fatal: the remote end hung up unexpectedly
Fixes #
=> fix CI : the receiving end does not support --signed push

README-zh_CN.md, README.md, docs/README-zh_CN.md, docs/README.md
=> readme: add copyright

test/doc/coordinator.md
=> add some e2e for spiderpool

charts/spiderpool/templates/daemonset.yaml
robot cherry pick PR <https://github.com/spidernet-io/spiderpool/pull/2974> from cyclinder,to branch release-v0.9,  action <https://github.com/spidernet-io/spiderpool/actions/runs/7297329230>  , commits 3b2cf2445bc87d54b773f1fd71e54216ebe68ab4
=> fix chart: Values.multus.multusCNI.uninstall does not take effect

test/e2e/performance/performance.md
=> Additional performance test data notes

docs/concepts/blog-zh_CN.md, docs/concepts/blog.md
=> Add a blog about using spiderpool in vivo.

.github/workflows/auto-version-release.yaml, .github/workflows/build-image-base.yaml, .github/workflows/build-image-ci.yaml, .github/workflows/build-image-plugins.yaml, .github/workflows/call-release-changelog.yaml, .github/workflows/call-release-chart.yaml, .github/workflows/call-release-doc.yaml, .github/workflows/call-release-image.yaml, .github/workflows/call-update-githubpages.yaml, .github/workflows/e2e-init.yaml, .github/workflows/lint-golang.yaml, .github/workflows/lint-yaml.yaml, .github/workflows/trivy-scan-image.yaml, .github/workflows/update-chart-readme.yml
- release/bug 
Upgraded actions/download-artifact in PR https://github.com/spidernet-io/spiderpool/pull/2943 and PR https://github.com/spidernet-io/spiderpool/pull/2942, but unfortunately it brought some additional problems, and this problem is not unique, many people reported this problem. refer to https://github.com/actions/download-artifact/issues/249
In this regard, first roll back the modified version and observe.
Fixes #
```
##[debug]  "signed_url": "https://productionresultssa8.blob.core.windows.net/actions-results/aaadfbe0-c403-43b5-967b-41a34931c11c/workflow-job-run-b40a7d92-9d06-5992-d6aa-ec7dfa8e686b/artifacts/image-tar-spiderpool-agent.zip?se=2023-12-24T20%3A19%3A47Z&sig=GwxUemVDqHPEFzjvrZ …
```
=> Revert "build(deps): bump actions/download-artifact and actions/upload-artifact from 3 to 4“

cmd/spiderpool-agent/cmd/daemon.go, cmd/spiderpool-controller/cmd/daemon.go
Reference: https://github.com/spidernet-io/spiderpool/pull/2971
=> [cherrypick]fix spiderpool-agent crashes when kubevirt static IP feature is off

docs/mkdocs.yml, docs/usage/install/cloud/get-started-alibaba-zh_CN.md, docs/usage/install/cloud/get-started-alibaba.md, docs/usage/install/cloud/get-started-aws-zh_CN.md, docs/usage/install/cloud/get-started-aws.md, docs/usage/install/overlay/get-started-calico-zh_cn.md, docs/usage/install/overlay/get-started-calico.md, docs/usage/install/overlay/get-started-cilium-zh_cn.md, docs/usage/install/overlay/get-started-cilium.md, docs/usage/install/system-requirements-zh_CN.md, docs/usage/install/system-requirements.md, docs/usage/install/underlay/get-started-calico-zh_CN.md, docs/usage/install/underlay/get-started-calico.md, docs/usage/install/underlay/get-started-macvlan-zh_CN.md, docs/usage/install/underlay/get-started-macvlan.md, docs/usage/install/underlay/get-started-ovs-zh_CN.md, docs/usage/install/underlay/get-started-ovs.md, docs/usage/install/underlay/get-started-sriov-zh_CN.md, docs/usage/install/underlay/get-started-sriov.md, docs/usage/install/underlay/get-started-weave-zh_CN.md, docs/usage/install/underlay/get-started-weave.md
=> supplement system requirements doc

test/Makefile.defs, test/scripts/install-default-cni.sh
=> rebase main for calico version

pkg/coordinatormanager/coordinator_informer.go
- release/bug 
Get the cluster  and service CIDR from kube-controller-manager pod's command(--service-cluster-ip-range AND cluster-cidr) rather than kubeadm-config configMap.
Sometimes, We don't use kubeadm to create a cluster, we don't have kubeadm-config configMap in this case,  so we can't fetch the cluster and service cidr.
```
apiVersion: v1
kind: Pod
metadata:
annotations:
kubernetes.io/config.hash: f20b37caa218afeda017e57331c0956a
kubernetes.io/config.mirror: f20b37caa218afeda017e57331c0956a
kubernetes.io/config.seen: "2023-12-04T09:06:09.968053030Z"
kubernetes.io/config.source: file
creationTimestamp: "2023-12-04T09:06:10Z"
labels:
component: kube-controller-manager
tier: control-plane
name: kube-controller-manager-kind-control-plane …
```
=> spidercoordinator:  fetch the serviceCIDR from  kubeControllerManager pod

pkg/ippoolmanager/ippool_mutate.go, pkg/subnetmanager/subnet_informer.go
close https://github.com/spidernet-io/spiderpool/issues/3017
=> [cherrypick]fix inherit subnet properties for ippool failure

docs/usage/spider-subnet-zh_CN.md, docs/usage/spider-subnet.md, pkg/ipam/pool_selections.go, test/doc/subnet.md, test/e2e/subnet/subnet_test.go
robot cherry pick PR <https://github.com/spidernet-io/spiderpool/pull/2952> from Icarus9913,to branch release-v0.8,  action <https://github.com/spidernet-io/spiderpool/actions/runs/7328896952>  , commits 98f0ebe999b83f7694c0dbaa6b9f1564c6c5fc8c
=> single POD without controller is forbidden to use  SpiderSubnet feature

docs/usage/install/overlay/get-started-calico-zh_cn.md, docs/usage/install/overlay/get-started-calico.md, docs/usage/install/overlay/get-started-cilium-zh_cn.md, docs/usage/install/overlay/get-started-cilium.md
- kind/doc
docs: update overlay mode get-started.md
Fixes #
=> docs: update overlay mode get-started.md

.github/dependabot.yml
=> update label in depenndabot

.github/workflows/call-release-doc.yaml
=> v0.7 call-release-doc.yaml rebase to main

README-zh_CN.md, README.md, docs/README-zh_CN.md, docs/README.md
=> List the stable versions of spiderpool

pkg/ip/cidr.go, pkg/ip/cidr_test.go, pkg/ippoolmanager/ippool_validate.go, pkg/subnetmanager/subnet_validate.go, test/e2e/common/tools.go
Refer to https://github.com/spidernet-io/spiderpool/issues/2134
=> add IPPool and Subnet property subnet field format validation

test/doc/ippoolcr.md, test/doc/performance.md, test/e2e/affinity/affinity_test.go, test/e2e/annotation/annotation_test.go, test/e2e/assignip/assignip_test.go, test/e2e/coordinator/macvlan-overlay-one/macvlan_overlay_one_test.go, test/e2e/coordinator/macvlan-underlay-one/macvlan_underlay_one_test.go, test/e2e/ifacer/ifacer_test.go, test/e2e/ippoolcr/ippoolcr_test.go, test/e2e/kruise/kruise_test.go, test/e2e/reclaim/reclaim_test.go, test/e2e/reliability/reliability_test.go, test/e2e/reservedip/reservedip_test.go, test/e2e/subnet/subnet_test.go, test/scripts/debugEnv.sh
=> e2e fix: SpiderSubnet and SpiderIPPool resource subnet overlap.

.github/workflows/auto-cherrypick.yaml, .github/workflows/call-release-chart.yaml, .github/workflows/call-release-doc.yaml, .github/workflows/call-update-githubpages.yaml
=> cherry-pick PRs submitted by robots can be verified.

.github/workflows/auto-cherrypick.yaml, .github/workflows/call-release-chart.yaml, .github/workflows/call-release-doc.yaml, .github/workflows/call-update-githubpages.yaml
=> [release-v0.8]cherry-pick PRs submitted by robots can be verified.

test/Makefile
=> e2e fix: The kind image name is wrong.

docs/example/spider-subnet/multiple-interfaces.yaml
=> fix document example typo

cmd/ifacer/cmd/cmd_add.go
=> fix: the parent interface is down, set it to up before creating the vlan sub-interface

docs/usage/rdma-ib-zh_CN.md, docs/usage/rdma-ib.md
release/bug 
kind/doc
docs: fix SpiderMultusConfig.spec.cniType in IPoIB
Fixes #
=> docs: fix SpiderMultusConfig.spec.cniType in IPoIB

docs/concepts/blog-zh_CN.md, docs/concepts/blog.md
=> update document blog

tools/scripts/e2ecover.sh
=> fix  CI 'Update badge' steps failure

README-zh_CN.md, docs/README-zh_CN.md, docs/usage/install/upgrade-zh_CN.md, docs/usage/install/upgrade.md
=> docs: Update upgrade docs

test/e2e/reliability/reliability_test.go
Fixes #3100
When the leader is elected to a new controller Pod, but the new controller has not yet successfully run (0/1), the leader record is a null value. There is a lack of judgment on the null value.
=> fix: Added judgment that SpiderControllerLeases.Spec.HolderIdentity is an empty string.

docs/mkdocs.yml, docs/usage/install/underlay/get-started-calico-zh_CN.md, docs/usage/install/underlay/get-started-calico.md
Try a comment feature for code blocks by following [MkDocs Code Block](https://squidfunk.github.io/mkdocs-material/reference/code-blocks/).
=> Add inline comment to code blocks in docs

docs/usage/install/overlay/get-started-calico-zh_cn.md, docs/usage/install/overlay/get-started-calico.md, docs/usage/install/overlay/get-started-cilium-zh_cn.md, docs/usage/install/overlay/get-started-cilium.md, docs/usage/install/underlay/get-started-calico-zh_CN.md, docs/usage/install/underlay/get-started-calico.md, docs/usage/install/underlay/get-started-sriov-zh_CN.md, docs/usage/install/underlay/get-started-sriov.md, docs/usage/install/underlay/get-started-weave-zh_CN.md, docs/usage/install/underlay/get-started-weave.md
Performed actions below:
- Fix indentations for bullets and lists
- Fix typos and Chinese punctuations
=> Fix formats in underlay and overlay docs

test/e2e/assignip/assignip_test.go
The e2e codes have a concurrency problem with the global variables
fix e2e bug
https://github.com/spidernet-io/spiderpool/issues/3108
=> fix e2e concurrency problems

cmd/spiderpool-init/cmd/client.go
robot cherry pick PR <https://github.com/spidernet-io/spiderpool/pull/3123> from Icarus9913,to branch release-v0.9,  action <https://github.com/spidernet-io/spiderpool/actions/runs/7629464362>  , commits e2085e4189252d9e4e6ef0d1905012f1a1b4d93d
=> optimize spiderpool-init restart spiderpool-agent codes

test/doc/spidercoodinator.md, test/e2e/spidercoordinator/spidercoordinator_test.go
Fixes #
In the https://github.com/spidernet-io/spiderpool/pull/3062 , @cyclinder  added e2e case, but forgot the labels. It has been added, please confirm.
=> e2e: case miss labels

README-zh_CN.md, README.md, docs/README-zh_CN.md, docs/README.md
original link is failed to visit
=> fix image link

docs/mkdocs.yml, docs/usage/ipvlan_bandwidth-zh_CN.md, docs/usage/ipvlan_bandwidth.md
- kind/doc
docs: add ipvlan bandwidth manager with cilium-chaining project.
Fixes https://github.com/spidernet-io/spiderpool/issues/2709
=> docs: bandwidth for ipvlan datapath

.github/workflows/e2e-init.yaml
- kind/bug
CI: Fix E2E_KIND_IMAGE_TAG don't works
Fixes #
=> CI: Fix E2E_KIND_IMAGE_TAG don't works

.github/workflows/call-release-changelog.yaml
robot cherry pick PR <https://github.com/spidernet-io/spiderpool/pull/3151> from ty-dc,to branch release-v0.7,  action <https://github.com/spidernet-io/spiderpool/actions/runs/7696568422>  , commits d1cd555760675c697f9c2178800bf99f2c8fadca
=> Added signoff for robot submission changelog

test/e2e/spidercoordinator/spidercoordinator_test.go
- kind/ci-bug
Fixes https://github.com/spidernet-io/spiderpool/issues/3164
=> e2e: fix typo in serviceCIDR case

test/e2e/performance/performance_test.go
=> rebase: fix e2e curl failure

.github/workflows/call-release-changelog.yaml
=> robot: add committer for create_pr

README-zh_CN.md, README.md, docs/README-zh_CN.md, docs/README.md
=> docs: Update supported stable versions

docs/usage/egress.md, docs/usage/install/underlay/get-started-calico.md, docs/usage/install/underlay/get-started-macvlan.md, docs/usage/install/underlay/get-started-ovs.md, docs/usage/install/underlay/get-started-weave.md
=> Fix typos in usage and underlay-install docs

test/doc/coordinator.md, test/doc/ifacer.md, test/doc/spidercoodinator.md, test/e2e/coordinator/macvlan-overlay-one/macvlan_overlay_one_test.go, test/e2e/coordinator/macvlan-underlay-one/macvlan_underlay_one_test.go
=> Add e2e about service spec.externalTrafficPolicy

test/Makefile
close https://github.com/spidernet-io/spiderpool/issues/3230
=> optimize makefile for e2e setup

cmd/spiderpool-agent/cmd/daemon.go, cmd/spiderpool-controller/cmd/daemon.go, test/Makefile.defs
robot cherry pick PR <https://github.com/spidernet-io/spiderpool/pull/3223> from Icarus9913,to branch release-v0.9,  action <https://github.com/spidernet-io/spiderpool/actions/runs/7983368477>  , commits 513902b8f2317595ba074788f6b0caaebc3f9b98
=> supplement pyroscope profile types

test/scripts/debugEnv.sh
=> Ignore local-path-storage log messages

.github/workflows/auto-cherrypick.yaml
=> automatically port the label from the initial cherry-picked PR

.github/workflows/auto-pr-ci.yaml
=> Add a low-k8s version of job to PR CI

docs/concepts/coordinator-zh_CN.md, docs/reference/plugin-ifacer.md, docs/usage/install/underlay/get-started-macvlan-zh_CN.md, docs/usage/install/underlay/get-started-macvlan.md, docs/usage/install/underlay/get-started-ovs-zh_CN.md, docs/usage/install/underlay/get-started-ovs.md, docs/usage/install/underlay/get-started-sriov-zh_CN.md, docs/usage/install/underlay/get-started-sriov.md
robot cherry pick PR <https://github.com/spidernet-io/spiderpool/pull/3270> from ty-dc,to branch release-v0.9,  action <https://github.com/spidernet-io/spiderpool/actions/runs/8109959530>  , commits e0ccf2f815150bdb1f0ca023fe2effbec6afabd1
=> Update document format

pkg/coordinatormanager/coordinator_informer.go
robot cherry pick PR <https://github.com/spidernet-io/spiderpool/pull/3269> from cyclinder,to branch release-v0.9,  action <https://github.com/spidernet-io/spiderpool/actions/runs/8112389254>  , commits 7f1901c66e40707bd44563a233a4c1b219d35bf8
=> Fix panic in spidercoordinator informer

.github/workflows/e2e-init.yaml
=> Free Disk Space for CI

pkg/coordinatormanager/coordinator_informer.go
robot cherry pick PR <https://github.com/spidernet-io/spiderpool/pull/3284> from cyclinder,to branch release-v0.8,  action <https://github.com/spidernet-io/spiderpool/actions/runs/8150469566>  , commits 6aa148d48f6e9a53869a8ad16c00dc77f3bc5ded
=> spidercoordinator: Enhance the edge case

go.mod, pkg/coordinatormanager/coordinator_informer.go
robot cherry pick PR <https://github.com/spidernet-io/spiderpool/pull/3291> from cyclinder,to branch release-v0.9,  action <https://github.com/spidernet-io/spiderpool/actions/runs/8169120963>  , commits 3f820f067722033caee52f5a187f01853874fa99
=> Spidercoordinator: sync kubeadm-config event to trigger the status update

pkg/networking/networking/route.go
robot cherry pick PR <https://github.com/spidernet-io/spiderpool/pull/3302> from ty-dc,to branch release-v0.9,  action <https://github.com/spidernet-io/spiderpool/actions/runs/8228754417>  , commits 2db9778a68d4d174c731bbe8bc79cbf91f083679
=> coordinator: rework GetDefaultRouteInterface to get pod's default route nic

go.mod, pkg/coordinatormanager/coordinator_informer.go
- release/bug 
cherry-pick 
Fixes https://github.com/spidernet-io/spiderpool/issues/3293
=> Spidercoordinator: Add kubeadm-config event to workQueue

docs/usage/spider-multus-config-zh_CN.md, docs/usage/spider-multus-config.md
=> Added docs for node NIC renaming

.github/workflows/build-image-base.yaml
=> Fixed the failure to obtain environment variables in build-image-base.yaml

docs/usage/install/underlay/get-started-macvlan-zh_CN.md, docs/usage/install/underlay/get-started-macvlan.md, docs/usage/install/underlay/get-started-ovs-zh_CN.md, docs/usage/install/underlay/get-started-ovs.md
docs: update installtion for spidercoordinator
Fixes #
=> docs: update installtion for spidercoordinator

charts/spiderpool/README.md, charts/spiderpool/templates/rdma-shared-dp/rdma-shared-dp.yaml, charts/spiderpool/values.yaml
- kind/feature
Fixes https://github.com/spidernet-io/spiderpool/issues/3331
=> chart: Support configure ifNames for rdmaSharedDevicePlugin

MAINTAINERS.md
as community advocator
Fixes #
=> add panpan0000 as maintainer

.github/workflows/lint-golang.yaml
=> Update codecov-action to v4

.github/workflows/e2e-init.yaml
=> When the kind cluster cannot be created, add the step of restarting docker and try again.

test/e2e/coordinator/macvlan-overlay-one/macvlan_overlay_one_test.go
=> Fix: check if err occurs during e2e create IPPool step

cmd/coordinator/cmd/command_add.go, cmd/coordinator/cmd/utils.go
robot cherry pick PR <https://github.com/spidernet-io/spiderpool/pull/3358> from cyclinder,to branch release-v0.8,  action <https://github.com/spidernet-io/spiderpool/actions/runs/8700802042>  , commits 9125833baa5b772b6f9cd9dc1ca6843205ad249a
=> coordinator: ensure hijickRoute's gw is from hostIPRouteForPod

.github/workflows/call-release-image.yaml
=> bump cosign-release to v2.2.3

pkg/ipam/allocate.go, test/e2e/ippoolcr/ippoolcr_test.go
=> Optimize IPPool multus affinity code comments

.github/workflows/auto-version-release.yaml, .github/workflows/call-release-version.yaml, docs/README-zh_CN.md, docs/README.md
=> CI:  update release version in readme

.github/workflows/auto-version-release.yaml, .github/workflows/call-release-version.yaml, docs/README-zh_CN.md
=> [chery-pick] CI:  update release version in readme

.github/workflows/auto-upgrade-ci.yaml
=> fix upgrade test

.github/workflows/auto-upgrade-ci.yaml, .github/workflows/auto-version-release.yaml
=> ci: optimize upgrade

docs/usage/install/cloud/get-started-aws-zh_CN.md, docs/usage/install/cloud/get-started-aws.md
=> docs: aws optimization

.github/workflows/auto-upgrade-ci.yaml, .github/workflows/auto-version-release.yaml, Makefile, test/Makefile
=> Add upgrade test for spiderpool

test/e2e/subnet/subnet_test.go
=> e2e fix: restart the spider-Agent to make the configuration take effect.

test/scripts/debugEnv.sh
=> fix: add kdoctor debug log

.github/workflows/call-release-version.yaml
=> fix: Ignore rc version when updating readme

docs/usage/install/underlay/get-started-ovs-zh_CN.md, docs/usage/install/underlay/get-started-ovs.md
=> [cherry-pick]: doc: optimize ovs

test/e2e/common/constant.go
=> e2e fix: increase the timeout for service accounts

test/e2e/subnet/subnet_test.go
Fixes #3435 #3450
After modifying spiderpool-config, for it to take effect, the agent and controller must be restarted.
=> e2e fix: extend the waiting time after restarting spiderpool-agent and add some logs

tools/scripts/changelog.sh
=> fix: Logic issues with releasing version x

test/e2e/spidercoordinator/spidercoordinator_test.go
=> fix: restarting the kcm Pod helps restore its labels

docs/usage/dra.md, docs/usage/dra_zh_CN.md
=> typo: dra docs

pkg/dra/dra-plugin/device_state.go
- release/bug 
DRA: fix error start of agent
Fixes https://github.com/spidernet-io/spiderpool/issues/3503
=> DRA: fix error start of agent

test/e2e/common/pod.go, test/e2e/spidercoordinator/spidercoordinator_test.go
add timeout for spidercoordinator case and debug infos.
Fixes https://github.com/spidernet-io/spiderpool/issues/3498
https://github.com/spidernet-io/spiderpool/actions/runs/9214146791/job/25349917016
=> E2E: add timeout for spidercoordinator case

docs/usage/rdma-ib-zh_CN.md, docs/usage/rdma-ib.md, docs/usage/rdma-roce-zh_CN.md, docs/usage/rdma-roce.md
robot cherry pick PR <https://github.com/spidernet-io/spiderpool/pull/3536> from corrtia,to branch release-v0.9,  action <https://github.com/spidernet-io/spiderpool/actions/runs/9397453835>  , commits a88ea059bf22baf4401c5a7d39496f30788ccef4
=> DOC-123: 更新了基于macvlan和ipvlan的RDMA网卡安装Spiderpool的命令

.github/workflows/auto-upgrade-ci.yaml, test/Makefile, test/e2e/annotation/annotation_test.go, test/scripts/debugEnv.sh
=> optimizate upgrade

charts/spiderpool/templates/role.yaml, charts/spiderpool/templates/role_binding.yaml
```
Error: The Artifacts is out of date! Please run 'make manifests'.
make: *** [Makefile:170: manifests-verify] Error 1
error, failed to check Kubebuilder SDK and yaml
```
the rbac files are auto-generated by controller-gen, we don't edit it. Or we can't pass the SDK check. so rebase https://github.com/spidernet-io/spiderpool/pull/3522.
Fixes https://github.com/spidernet-io/spiderpool/actions/runs/9544364352/job/26303312400?pr=3584
=> RBAC: rebase pull 3522

.github/workflows/auto-upgrade-ci.yaml, .github/workflows/auto-version-release.yaml, test/Makefile, test/scripts/debugEnv.sh
=> [cherrypick-release-v0.9] optimization upgrade

.github/workflows/auto-upgrade-ci.yaml
Fixes #3619 
Let the PR submitter pay attention to this upgrade CI issue himself.
=> the PR upgrade CI failed, there is no need to create an issue.

docs/usage/rdma-ib-zh_CN.md, docs/usage/rdma-ib.md, docs/usage/rdma-roce-zh_CN.md, docs/usage/rdma-roce.md
- kind/doc
sriov-operator require for the worker labels
Fixes #
=> docs: note label worker nodes for sriov-operator

.github/workflows/auto-upgrade-ci.yaml, .github/workflows/build-image-ci.yaml, test/Makefile
=> Optimize upgrade CI, and use the self-built image in the release branch

.github/workflows/lint-golang.yaml
=> to avoid codecov update failure, update codecov-action to v4

cmd/coordinator/cmd/utils.go
robot cherry pick PR <https://github.com/spidernet-io/spiderpool/pull/3588> from cyclinder,to branch release-v0.8,  action <https://github.com/spidernet-io/spiderpool/actions/runs/9609000879>  , commits 13c95f09d9040352c02750cb8d8d970feea319f5
=> add link-local IP to veth0 for istio

pkg/ip/ip.go, pkg/ip/ip_test.go, pkg/ippoolmanager/ippool_manager.go, pkg/subnetmanager/subnet_manager.go, pkg/subnetmanager/subnet_validate.go, test/e2e/common/spidersubnet.go
=> fix: it is so slow to create a Pod requiring IP from a super big CIDR

tools/scripts/changelog.sh
robot cherry pick PR <https://github.com/spidernet-io/spiderpool/pull/3663> from weizhoublue,to branch release-v0.8,  action <https://github.com/spidernet-io/spiderpool/actions/runs/9661909105>  , commits 5566f500756a0e5f31a5dc0b1e79083601f44f3f
=> fix: release note 

docs/usage/statefulset-zh_CN.md, docs/usage/statefulset.md, pkg/ipam/allocate.go, pkg/ipam/utils.go, test/e2e/affinity/affinity_test.go
robot cherry pick PR <https://github.com/spidernet-io/spiderpool/pull/3669> from lou-lan,to branch release-v0.9,  action <https://github.com/spidernet-io/spiderpool/actions/runs/9710884374>  , commits 2a50107c11a742109ca1c3f016243bb8fc4220e7
=> Fix: Statefulset pod should change IP when recreating with a changed pool in annotation

charts/spiderpool/templates/deleteHook.yaml
=> Optimize clean job to use host network

pkg/networking/gwconnection/connection.go
- release/none
Fixes https://github.com/spidernet-io/spiderpool/issues/3703
```
{"level":"ERROR","ts":"2024-07-08T20:22:10.982Z","logger":"coordinator","caller":"gwconnection/connection.go:101","msg":"gateway 192.50.12.1 is read packet 16:4a:ab:6e:9f:8b: i/o timeout, reason: %!v(MISSING)","Action":"ADD","ContainerID":"c6791ad7cf843b5c1b77b18f59c07ba9f7028af2e097d68c9113a6a2c654d855","Netns":"/var/run/netns/cni-f324806f-dbeb-4a1c-4429-02d685b11286","IfName":"net1","PodName":"dep-name-9c959ff9fb-6ccbb66b44-qmn9b","PodNamespace":"ns-ab3f67cc56"}
```
=> coordinator: improve error message for gateway detecting gateway

.github/workflows/auto-diff-k8s-ci.yaml, test/scripts/update-kindnode-version.sh
=> ci fix: Optimize robot to update kind/node version

.github/workflows/auto-diff-k8s-ci.yaml
=> CI: add pr reviewer

docs/usage/install/uninstall-zh_CN.md, docs/usage/install/uninstall.md, tools/scripts/cleanCRD.sh
robot cherry pick PR <https://github.com/spidernet-io/spiderpool/pull/3706> from ty-dc,to branch release-v1.0,  action <https://github.com/spidernet-io/spiderpool/actions/runs/9891803610>  , commits 0f4724d589c081ecd73d33e4b37fd0d738e1c3c1
=> Optimize clean scripts

docs/mkdocs.yml, docs/usage/install/uninstall-zh_CN.md, docs/usage/install/uninstall.md, tools/scripts/cleanCRD.sh
=> [cherry-pick] optimize clean scripts

tools/scripts/cleanCRD.sh
=> delete crd ovsnetworks.sriovnetwork.openshift.io of sriov-network-operator

test/e2e/kubevirt/kubevirt_test.go
=> [cherry-pick]e2e fix: skip About passt network core binding e2e

docs/concepts/blog.md
Translate zh-cn text into english
=> replace zh-cn text with english in blogs

test/e2e/kubevirt/kubevirt_test.go
=> [cherry-pick] e2e fix: skip About passt network core binding e2e

cmd/spiderpool-controller/cmd/clean.go, pkg/k8s/utils/utils.go, tools/scripts/cleanCRD.sh
=> remove CRD  installed by sriov-network-operator when uninstalling

docs/usage/install/overlay/get-started-cilium-zh_cn.md, docs/usage/install/overlay/get-started-cilium.md, test/scripts/install-default-cni.sh
robot cherry pick PR <https://github.com/spidernet-io/spiderpool/pull/3762> from ty-dc,to branch release-v1.0,  action <https://github.com/spidernet-io/spiderpool/actions/runs/10093142827>  , commits 2522f8355ccfc5fbcac993164a0e11f396c77815
=> Change the type of cilium bpf.vlanBypass to list

charts/spiderpool/README.md, charts/spiderpool/templates/pod.yaml, charts/spiderpool/values.yaml, cmd/spiderpool-init/cmd/client.go, cmd/spiderpool-init/cmd/root.go, test/scripts/debugEnv.sh, test/scripts/install-multus.sh
- release/bug 
Fixes https://github.com/spidernet-io/spiderpool/issues/3728
=> init-pod:  support helm wait and fix installation block when agent pods fails to run

charts/spiderpool/templates/daemonset.yaml, test/Makefile, test/e2e/coordinator/macvlan-overlay-one/macvlan_overlay_one_test.go
robot cherry pick PR <https://github.com/spidernet-io/spiderpool/pull/3758> from cyclinder,to branch release-v1.0,  action <https://github.com/spidernet-io/spiderpool/actions/runs/10175239550>  , commits cfae10b87019df0874547bd18c3b45cd5213b9fd
=>  pod launched by unexpected CNI when the health checking of the agent fails and multus.conf is lost

charts/spiderpool/README.md, charts/spiderpool/templates/pod.yaml, charts/spiderpool/values.yaml, cmd/spiderpool-init/cmd/client.go, cmd/spiderpool-init/cmd/root.go, test/scripts/debugEnv.sh, test/scripts/install-multus.sh
- release/bug 
Fixes https://github.com/spidernet-io/spiderpool/issues/3791
=> init-pod: fix installtion block for agent pods can't running

charts/spiderpool/templates/daemonset.yaml, test/Makefile, test/e2e/coordinator/macvlan-overlay-one/macvlan_overlay_one_test.go
=> pod launched by unexpected CNI when the health checking of the agent fails and multus.conf is lost 

.github/workflows/lint-golang.yaml
=> fix: unittest reports occasional upload failures

README-zh_CN.md, README.md
=> docs: removed long-term unmaintained versions from the readme file

README-zh_CN.md, README.md
=> cherry-pick: removed long-term unmaintained versions from the readme file

test/Makefile
Fixes https://github.com/spidernet-io/spiderpool/issues/3785
=> e2e: enhance getting docker subnet infos

charts/spiderpool/crds/spiderpool.spidernet.io_spiderclaimparameters.yaml, pkg/dra/dra-plugin/cdi.go, pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/spiderclaimparameters_types.go, test/e2e/dra/dra_test.go, test/e2e/spiderclaimparameter/spiderclaimparameter_test.go
=> DRA: remove rdmaAcc field of SpiderClaimParameter

docs/reference/spiderpool-agent.md
=> docs: fix typo in spiderpool-aget.md

charts/spiderpool/templates/role.yaml, pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/rbac.go, pkg/multuscniconfig/utils.go
=> rbac: remove permissions for patch/update nodes and webhook resources

cmd/coordinator/cmd/command_add.go, docs/reference/spiderpool-agent.md, pkg/networking/sysctl/sysctl.go
=> agent set rp_filter to 0 for the each node

cmd/coordinator/cmd/command_add.go, docs/reference/spiderpool-agent.md, pkg/multuscniconfig/utils.go, pkg/networking/sysctl/sysctl.go, test/e2e/reclaim/reclaim_test.go
agent can be set rp_filter to 0 for the each node
Fixes #
=> agent can be set rp_filter to 0 for the each node

test/Makefile, test/scripts/debugEnv.sh
=> Added debug log for open-kruise installation failure

tools/scripts/changelog.sh
Currently, the [Releases page](https://github.com/spidernet-io/spiderpool/releases) displays the "Totoal" (instead of "Total") section at the end of each release.
=> Fix a typo in changelog.sh

.github/workflows/auto-diff-k8s-ci.yaml, .github/workflows/e2e-init.yaml
=> fix: use latest kind binary and pending kind/node v1.31

.github/workflows/status.yaml, tools/scripts/e2ecover.sh
=> e2e fix: statistics of e2e completion rate exclude pending cases

api/v1/agent/models/coordinator_config.go, api/v1/agent/openapi.yaml, api/v1/agent/server/embedded_spec.go, cmd/coordinator/cmd/command_add.go, cmd/coordinator/cmd/utils.go, cmd/spiderpool-agent/cmd/coordinator.go, docs/usage/install/overlay/get-started-calico-zh_cn.md, docs/usage/install/overlay/get-started-calico.md, docs/usage/install/overlay/get-started-cilium-zh_cn.md, docs/usage/install/overlay/get-started-cilium.md, pkg/multuscniconfig/multusconfig_informer.go, pkg/multuscniconfig/utils.go, pkg/networking/networking/ip.go, pkg/networking/networking/route.go, test/doc/coordinator.md, test/e2e/common/constant.go, test/e2e/coordinator/macvlan-overlay-one/macvlan_overlay_one_suite_test.go, test/e2e/coordinator/macvlan-overlay-one/macvlan_overlay_one_test.go, test/scripts/debugEnv.sh
- release/bug
Fixes https://github.com/spidernet-io/spiderpool/issues/3953
=> coordinator: Fix error policy routing table when pod has multi nics

charts/spiderpool/crds/spiderpool.spidernet.io_spidermultusconfigs.yaml, docs/reference/crd-spidermultusconfig.md, docs/usage/spider-multus-config-zh_CN.md, docs/usage/spider-multus-config.md, pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/spidermultus_types.go, pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/zz_generated.deepcopy.go, pkg/multuscniconfig/multusconfig_informer.go, pkg/multuscniconfig/multusconfig_mutate.go, pkg/multuscniconfig/multusconfig_validate.go, test/doc/spidermultus.md, test/e2e/spidermultus/spidermultus_test.go
=> Add chainCNI support for spidermultusconfig

.github/workflows/auto-upgrade-ci.yaml, .github/workflows/e2e-init.yaml, Makefile, docs/develop/contributing.md
=> rename ci to be easy to understand

charts/spiderpool/templates/configmap.yaml, test/Makefile, test/scripts/preCheckClusterReady.sh
robot cherry pick PR <https://github.com/spidernet-io/spiderpool/pull/3988> from cyclinder,to branch release-v0.8,  action <https://github.com/spidernet-io/spiderpool/actions/runs/10677272462>  , commits 4ca5709474cd18317f8714122ebf2f0a401b8ab6
=> Fix：the chart value tuneSysctlConfig does not work

.github/workflows/e2e-init.yaml, Makefile, charts/spiderpool/templates/deleteHook.yaml, charts/spiderpool/templates/role.yaml, cmd/spiderpool-controller/cmd/clean.go, pkg/constant/k8s.go, pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/rbac.go, pkg/k8s/utils/utils.go, test/Makefile, test/Makefile.defs, test/scripts/debugEnv.sh
=> fix: cannot uninstall spiderpool when sriovOperatorConfig is installed

.github/workflows/auto-upgrade-ci.yaml
=> Optimize upgrade CI and clarify failed steps

.github/workflows/auto-upgrade-ci.yaml, .github/workflows/e2e-init.yaml, Makefile, test/Makefile, test/scripts/debugEnv.sh
Fixes #4027
cherry-pick #3925，clean 是属于新功能，不需合入到 release-v0.9。
基于 #3925 ，在 release-v0.9 上修改一些 CI 问题，如：
1. makefile 语法使用有误 -$(QUIET) make -C test uninstall_spiderpool，错误使用了 '-'，导致忽略了 uninstall_spiderpool 层级下的报错。
2. 明确 CI 卸载或者更新在哪一步失败了 ，调整 CI 结构
=> cherry-pick some CI changes

.github/workflows/update-golang-version.yaml
=> optimizate auto upgrade golang logic

.github/workflows/e2e-init.yaml, test/Makefile
Fixes #4048 
补充日志，在 setup kind 集群后，通过 helm 安装 spiderpool-controller 或者 open-kurise 等，但出现 pod 的 crash ，无法查看到 pod 的 logs
=> Optimize setup kind cluster debug log

pkg/ippoolmanager/ippool_manager.go, test/e2e/reclaim/reclaim_test.go
robot cherry pick PR <https://github.com/spidernet-io/spiderpool/pull/3926> from ty-dc,to branch release-v1.0,  action <https://github.com/spidernet-io/spiderpool/actions/runs/10933367572>  , commits 51c3e4b9494e771e9b4bfd5a5576dd5cfb8727c7
=> Added debug log of AllocatedIPCount of ippool

pkg/coordinatormanager/coordinator_validate.go, pkg/multuscniconfig/multusconfig_mutate.go, test/doc/spidermultus.md, test/e2e/spidermultus/spidermultus_test.go
robot cherry pick PR <https://github.com/spidernet-io/spiderpool/pull/4062> from cyclinder,to branch release-v1.0,  action <https://github.com/spidernet-io/spiderpool/actions/runs/10933291536>  , commits 603c57e04da85655a6f7672612f2463fad5cffda
=> Fix panic when creating spidermultusconfig with nil podRPFilter in validate webhook

docs/concepts/ipam-des-zh_CN.md, docs/concepts/ipam-des.md
=> typo: spec.disable description error

docs/usage/install/ai/get-started-macvlan-zh_CN.md, docs/usage/install/ai/get-started-macvlan.md
- fix indentations for 1-2-3 list, to use 4 spaces, specified by MkDocs
- Add minor changes about grammar, punctuations
=> [docs] Fix indentations in ai/get-started-macvlan

.github/workflows/auto-upgrade-ci.yaml, Makefile, docs/usage/install/upgrade-zh_CN.md, docs/usage/install/upgrade.md, test/Makefile
Fixes #4050 
在 PR #https://github.com/spidernet-io/spiderpool/pull/3772/files 中，ipam.spidersubnet.enable 被改为 ipam.spiderSubnet.enable，导致使用 --reuse-value 参数时，会升级失败。暂时通过 --set 显示设置 ipam.spiderSubnet.enable。
=> optimizate spiderpool upgrade CI

tools/scripts/cleanCRD.sh
Fixes #
改进脚本即可，代码中清理了的
https://github.com/spidernet-io/spiderpool/blob/bc053234a0a94dcdf180440c9ad31f35bfa73f1a/cmd/spiderpool-controller/cmd/clean.go#L139C1-L140C1
=> add delete spiderclaimparameters for cleanup scripts

test/scripts/install-default-cni.sh
robot cherry pick PR <https://github.com/spidernet-io/spiderpool/pull/4126> from ty-dc,to branch release-v1.0,  action <https://github.com/spidernet-io/spiderpool/actions/runs/11098077232>  , commits b5799109d59938728f34ee5f0ca670395a3dd261
=> fix cilium installation --set tunnel

.github/workflows/auto-upgrade-ci.yaml, Makefile, docs/usage/install/upgrade-zh_CN.md, docs/usage/install/upgrade.md, pkg/coordinatormanager/coordinator_validate.go, test/Makefile, test/doc/spidermultus.md, test/e2e/spidermultus/spidermultus_test.go, test/scripts/install-default-cni.sh
=> robot-cherrypick: optimizate spiderpool upgrade CI

cmd/spiderpool-controller/cmd/clean.go
=> fix: avoid failures when cleaning up spiderpool resources due to resourceVersion conflicts.

docs/usage/install/ai/get-started-macvlan-zh_CN.md, docs/usage/install/ai/get-started-macvlan.md, docs/usage/install/underlay/get-started-ovs-zh_CN.md, docs/usage/install/underlay/get-started-ovs.md
**Notice**:
"release/none"
"release/bug"
Fixes #4154 
=> fix: ovs docs formatting errors and AI docs typo

cmd/spiderpool-controller/cmd/clean.go
**Notice**:
"release/none"
"release/bug"
Fixes #4152
=> fix: optimize the cleanup code judgment of NotFound resources

test/scripts/install-ovs.sh
**Notice**:
"release/none"
"release/bug"
Fixes #4170
```
=========install openvswitch
debconf: delaying package configuration, since apt-utils is not installed
A dependency job for openvswitch-switch.service failed. See 'journalctl -xe' for details.
```
=> fix: Added retries to avoid openvswitch installation failures.

cmd/spiderpool-controller/cmd/daemon.go, pkg/multuscniconfig/multusconfig_validate.go, pkg/multuscniconfig/multusconfig_webhook.go, test/doc/spidermultus.md, test/e2e/spidermultus/spidermultus_test.go
robot cherry pick PR <https://github.com/spidernet-io/spiderpool/pull/4168> from ty-dc,to branch release-v0.9,  action <https://github.com/spidernet-io/spiderpool/actions/runs/11510480719>  , commits 709bfba247bfe5810c508e5278c9b67ee860e786
=> fix: same-name conflict check specified by multus.spidernet.io/cr-name

test/e2e/coordinator/macvlan-underlay-one/macvlan_underlay_one_test.go
**Notice**:
"release/none"
"release/bug"
Fixes #
=> fix: kdoctor log comparison failed.

test/e2e/reclaim/reclaim_test.go
**Notice**:
"release/none"
"release/bug"
Fixes #4197 
=> e2e fix: A conflict occurred while updating the IPPool resource.

test/e2e/spidermultus/spidermultus_test.go
**Notice**:
"release/none"
"release/bug"
Fixes #4213
=> e2e fix: error matching is more accurate.

pkg/podmanager/utils.go, pkg/podmanager/utils_test.go, test/Makefile
robot cherry pick PR <https://github.com/spidernet-io/spiderpool/pull/4245> from cyclinder,to branch release-v1.0,  action <https://github.com/spidernet-io/spiderpool/actions/runs/11607347306>  , commits ea7f44decf9f0ced29a86a4f6c4d1eb80a9f7553
=> Fix podwebhook cert don't update when spiderpool-controller restart

docs/usage/install/ai/get-started-macvlan-zh_CN.md, docs/usage/install/ai/get-started-macvlan.md, docs/usage/install/ai/get-started-sriov-zh_CN.md, docs/usage/install/ai/get-started-sriov.md, docs/usage/rdma-metrics-zh_CN.md, docs/usage/rdma-metrics.md
**Notice**:
"release/none"
"release/bug"
Fixes #
=> optimize rdma metrics and podwebhook docs

.github/workflows/auto-upgrade-ci.yaml, .github/workflows/build-image-ci.yaml, .github/workflows/e2e-init.yaml, .github/workflows/trivy-scan-image.yaml, test/Makefile
**Notice**:
"release/none"
"release/bug"
Fixes #4311
=> Fix TOOMANYREQUESTS failure in Trivy Action

.github/workflows/auto-upgrade-ci.yaml
**Notice**:
"release/none"
"release/bug"
Fixes #4314
=> After changing the image type to docker, updating CI should synchronize the changes.

test/scripts/install-ovs.sh
**Notice**:
"release/none"
"release/bug"
Fixes #4289
```
E: Failed to fetch http://deb.debian.org/debian/pool/main/a/apt/apt-utils_2.2.4_amd64.deb  Connection timed out [IP: 199.232.98.132 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```
=> fix: after the installation of openvswitch failed, retrying did not work.

charts/spiderpool/templates/daemonset.yaml, cmd/spiderpool-controller/cmd/daemon.go, pkg/podmanager/utils.go
**Notice**:
"release/none"
"release/bug"
Fixes https://github.com/spidernet-io/spiderpool/issues/4321
=> charts: Fix error nident in daemonset.yaml

test/e2e/reclaim/reclaim_test.go
robot cherry pick PR <https://github.com/spidernet-io/spiderpool/pull/4280> from ty-dc,to branch release-v1.0,  action <https://github.com/spidernet-io/spiderpool/actions/runs/12064166254>  , commits 3b9d8f65937656e7f0928835978640de0c32b0ee
=> fix: pod not-ready causes webhook call failure

docs/usage/spider-affinity-zh_CN.md, docs/usage/spider-affinity.md
robot cherry pick PR <https://github.com/spidernet-io/spiderpool/pull/4351> from windsonsea,to branch release-v1.0,  action <https://github.com/spidernet-io/spiderpool/actions/runs/12250956309>  , commits d1273ba6f365b4d5a7c39299e4d00801d8d3fba1
=> [Docs] Update spider-affinity to relocate code comments

pkg/ippoolmanager/ippool_manager.go, test/doc/annotation.md, test/e2e/annotation/annotation_test.go
**Notice**:
"release/none"
"release/bug"
Fixes #4380
=> Fix:  one NIC's IP pool shortage depleted IPs of other NICs in a multi-NIC setup.

pkg/ipam/allocate.go, pkg/ipam/utils.go, pkg/ippoolmanager/ippool_manager.go, pkg/workloadendpointmanager/workloadendpoint_manager.go, pkg/workloadendpointmanager/workloadendpoint_manager_test.go, test/doc/annotation.md, test/doc/ippoolcr.md, test/e2e/affinity/affinity_test.go, test/e2e/annotation/annotation_test.go
**Notice**:
"release/none"
"release/bug"
Fixes #4387 
=> Fix: statefulSet applications failed to create in multi-NIC scenarios.

pkg/ipam/allocate.go, pkg/ipam/utils.go, pkg/ippoolmanager/ippool_manager.go, pkg/workloadendpointmanager/workloadendpoint_manager.go, pkg/workloadendpointmanager/workloadendpoint_manager_test.go, test/doc/annotation.md, test/doc/ippoolcr.md, test/e2e/affinity/affinity_test.go, test/e2e/annotation/annotation_test.go
**Notice**:
"release/none"
"release/bug"
Fixes #4386
=> Fix: fail to create  statefulSet applications in multi-NIC scenarios.

.github/ISSUE_TEMPLATE/ci-failure.yaml, .github/ISSUE_TEMPLATE/usage.yaml, .github/workflows/auto-diff-k8s-ci.yaml, .github/workflows/auto-nightly-ci.yaml, .github/workflows/auto-update-authors.yaml, .github/workflows/auto-upgrade-ci.yaml, .github/workflows/call-release-changelog.yaml, .github/workflows/call-release-chart.yaml, .github/workflows/call-release-doc.yaml, .github/workflows/call-release-version.yaml, .github/workflows/call-update-githubpages.yaml, .github/workflows/update-cniplugins-version.yaml, .github/workflows/update-golang-version.yaml, CODEOWNERS, MAINTAINERS.md
**Notice**:
"release/none"
"release/bug"
Fixes #
=> remove maintainer: ty-dc

test/scripts/install-ovs.sh
**Notice**:
"release/none"
"release/bug"
Fixes #
=> ci fix: fails to run ovs

docs/concepts/blog-zh_CN.md, docs/concepts/blog.md
**Notice**:
"release/none"
"release/bug"
Fixes #
=> docs: updates blogs.md

Makefile, test/Makefile, test/Makefile.defs, test/scripts/install-ovs.sh
**Notice**:
"release/none"
"release/bug"
Fixes https://github.com/spidernet-io/spiderpool/issues/4419
=> e2e: fix openkruise installtion and debug ovs installtion

charts/spiderpool/README.md, charts/spiderpool/values.yaml
**Notice**:
"release/none"
"release/bug"
Fixes #
=> chart: update plugins image

test/Makefile
**Notice**:
"release/none"
"release/bug"
Fixes #
https://github.com/spidernet-io/spiderpool/actions/runs/12408389616/job/34688877976?pr=4420
=> e2e: debug

.github/workflows/auto-upgrade-ci.yaml, .github/workflows/build-image-base.yaml, .github/workflows/build-image-ci.yaml, .github/workflows/build-image-plugins.yaml, .github/workflows/call-release-changelog.yaml, .github/workflows/call-release-chart.yaml, .github/workflows/call-release-doc.yaml, .github/workflows/e2e-init.yaml, .github/workflows/lint-golang.yaml, .github/workflows/trivy-scan-image.yaml, .github/workflows/update-chart-readme.yml
**Notice**:
"release/none"
"release/bug"
Fixes #
As the following part of https://github.com/spidernet-io/spiderpool/pull/4437
Fixes https://github.com/spidernet-io/spiderpool/actions/runs/12491914214/job/34858519869?pr=4393
Ref to: https://github.com/actions/upload-artifact/issues/480
=> CI: FIx fail to upload multiple artifacts with the same name

.github/workflows/call-release-image.yaml
**Notice**:
"release/none"
"release/bug"
Fixes #
=> CI: Fix auto-version-release with upload-artifact failed

.github/workflows/auto-version-release.yaml
**Notice**:
"release/none"
"release/bug"
Fixes #
=> CI: Fix fail to download chart artifact

.github/workflows/auto-version-release.yaml
**Notice**:
"release/none"
"release/bug"
Fixes #
=> CI: Fix Download Chart Artifact

.github/workflows/auto-version-release.yaml
**Notice**:
"release/none"
"release/bug"
Fixes #
=> Fix CI Download Artifact

test/Makefile
**Notice**:
"release/none"
"release/bug"
Fixes https://github.com/spidernet-io/spiderpool/issues/4540
=> CI: Debug openkruise installtion

.github/workflows/lint-openapi.yaml
**Notice**:
"release/none"
"release/bug"
Fixes https://github.com/spidernet-io/spiderpool/actions/runs/12909415573/job/35997026565?pr=4560
https://github.com/puppeteer/puppeteer/issues/12818#issuecomment-2415915338
=> CI: FIx lint openapi yaml

test/Makefile, test/Makefile.defs
**Notice**:
"release/none"
"release/bug"
Fixes https://github.com/spidernet-io/spiderpool/issues/4584
=> CI: Fix ImagePullBackOff for kruise instation

.github/workflows/call-lint-chart.yaml, test/Makefile.defs
**Notice**:
"release/none"
"release/bug"
Fixes https://github.com/spidernet-io/spiderpool/issues/4627
Fixes https://github.com/spidernet-io/spiderpool/issues/4626
Fixes https://github.com/spidernet-io/spiderpool/issues/4608
=> CI: make open-kruise version to 1.7.2

pkg/ippoolmanager/ippool_webhook.go, pkg/subnetmanager/subnet_webhook.go
**Notice**:
"release/none"
"release/bug"
Fixes https://github.com/spidernet-io/spiderpool/issues/4548
=> webhook: prevent delete ippool with allocated IPs

charts/spiderpool/templates/tls.yaml
**Notice**:
"release/none"
"release/bug"
Fixes #
=> Update charts for ippool/subnet ValidatingWebhook

.github/workflows/auto-pr-ci.yaml, .github/workflows/auto-upgrade-ci.yaml, .github/workflows/auto-version-release.yaml, .github/workflows/build-image-base.yaml, .github/workflows/build-image-ci.yaml, .github/workflows/build-image-plugins.yaml, .github/workflows/call-release-changelog.yaml, .github/workflows/call-release-chart.yaml, .github/workflows/call-release-doc.yaml, .github/workflows/call-release-image.yaml, .github/workflows/call-update-githubpages.yaml, .github/workflows/e2e-init.yaml, .github/workflows/lint-golang.yaml, .github/workflows/lint-yaml.yaml, .github/workflows/trivy-scan-image.yaml, .github/workflows/update-chart-readme.yml
* Ensure kernel sends GARPs to avoid communication failures (#4649)
* Bump github actions deps
---------
**Notice**:
"release/none"
"release/bug"
Fixes #
=> Bump gh-actions deps

.github/workflows/auto-pr-ci.yaml, .github/workflows/e2e-init.yaml
**Notice**:
"release/none"
"release/bug"
Fixes #
=> CI:  Fix fail to upload artifact for same name

cmd/spiderpool/cmd/command_add.go, pkg/multuscniconfig/multusconfig_validate.go, pkg/networking/networking/packet.go, test/e2e/spidermultus/spidermultus_test.go
**Notice**:
"release/none"
"release/bug"
Fixes #
=> IPAM sends GARPS to updating arp cache table

charts/spiderpool/files/grafana-rdma-node.json
robot cherry pick PR <https://github.com/spidernet-io/spiderpool/pull/4706> from lou-lan,to branch release-v1.0,  action <https://github.com/spidernet-io/spiderpool/actions/runs/13622215274>  , commits d5a36097a80dffa34b30577912deb22f6d80d755
=> Fix RDMA multicast metric in node dashboard

charts/spiderpool/files/grafana-rdma-cluster.json, charts/spiderpool/files/grafana-rdma-node.json, charts/spiderpool/files/grafana-rdma-pod.json, charts/spiderpool/files/grafana-rdma-workload.json
robot cherry pick PR <https://github.com/spidernet-io/spiderpool/pull/4710> from weizhoublue,to branch release-v1.0,  action <https://github.com/spidernet-io/spiderpool/actions/runs/13627654814>  , commits 245f6c8333f64c909bfd3058c2615ec4782b45a4
=> chart: optimize rdma titles

pkg/gcmanager/scanAll_IPPool.go
…o get IP
**Notice**:
"release/none"
"release/bug"
Fixes #
=> fix: retrieve the endpoint for deleted stateless pod

docs/usage/spider-multus-config-zh_CN.md, docs/usage/spider-multus-config.md, pkg/constant/k8s.go, pkg/multuscniconfig/utils.go
**Notice**:
"release/none"
"release/bug"
Fixes https://github.com/spidernet-io/spiderpool/issues/4719
=> SpiderMultusConfig: Fix error json tag for min/maxTxRateMbps (#4716)

pkg/podownercache/pod_owner_cache.go, pkg/podownercache/pod_owner_cache_test.go
robot cherry pick PR <https://github.com/spidernet-io/spiderpool/pull/4713> from lou-lan,to branch release-v1.0,  action <https://github.com/spidernet-io/spiderpool/actions/runs/13712938001>  , commits c1eeeff4c2292cca0d9fc3cb653c1a5cd76ffede
=> Update getFinalOwner method to handle not found error

pkg/gcmanager/pod_cache.go, pkg/gcmanager/scanAll_IPPool.go
**Notice**:
"release/none"
"release/bug"
Fixes #
=> Fix ENV EnableGCStatelessTerminatingPod(Not)ReadyNode doesn't works

test/Makefile.defs
**Notice**:
"release/none"
"release/bug"
Fixes #
=> e2e: bump k8s version to 1.32

tools/scripts/updateLatestCniPluginVersion.sh
**Notice**:
"release/none"
"release/bug"
Fixes #
=> cni version: get the newest one

.github/grafana-check.yaml, .github/workflows/lint-grafana-file.yaml, charts/spiderpool/files/grafana-rdma-cluster.json, charts/spiderpool/files/grafana-rdma-node.json, charts/spiderpool/files/grafana-rdma-pod.json, charts/spiderpool/files/grafana-rdma-workload.json, docs/usage/rdma-metrics-zh_CN.md, docs/usage/rdma-metrics.md, pkg/rdmametrics/ethtool/ethtool.go, pkg/rdmametrics/metrics.go, pkg/rdmametrics/metrics_test.go, pkg/rdmametrics/oteltype/types.go
**Notice**:
"release/none"
"release/bug"
Fixes #4708
=> Add pause and discards stats for RDMA metrics

test/Makefile, test/Makefile.defs, test/e2e/common/node.go, test/e2e/spidercoordinator/spidercoordinator_suite_test.go, test/scripts/install-default-cni.sh
**Notice**:
"release/none"
"release/bug"
Fixes https://github.com/spidernet-io/spiderpool/issues/4813
Fixes https://github.com/spidernet-io/spiderpool/issues/4821
=> e2e: Fix cilium fail to running with ipv6 only

test/Makefile, test/e2e/common/node.go, test/e2e/spidercoordinator/spidercoordinator_suite_test.go, test/scripts/install-default-cni.sh
**Notice**:
"release/none"
"release/bug"
Fixes https://github.com/spidernet-io/spiderpool/issues/4836
=> e2e: Fix cilium fail to running with ipv6 only (#4824)

.github/workflows/auto-diff-k8s-ci.yaml, .github/workflows/e2e-init.yaml, test/Makefile, test/Makefile.defs
**Notice**:
"release/none"
"release/bug"
Fixes #
=> CI: make k8s version to v1.32.3

.github/workflows/auto-nightly-ci.yaml, .github/workflows/auto-pr-ci.yaml, test/e2e/annotation/annotation_test.go
**Notice**:
"release/none"
"release/bug"
Fixes https://github.com/spidernet-io/spiderpool/issues/4842
=> CI: Retry update resources with the conflict error

.github/workflows/auto-nightly-ci.yaml
**Notice**:
"release/none"
"release/bug"
Fixes #
=> CI: ubuntu20-04 has been depreted

charts/spiderpool/README.md, charts/spiderpool/values.yaml
**Notice**:
"release/none"
"release/bug"
Fixes #
=> Update cni latest plugin

docs/usage/install/ai/get-started-macvlan-zh_CN.md, docs/usage/install/ai/get-started-macvlan.md, docs/usage/install/ai/get-started-sriov-zh_CN.md, docs/usage/install/ai/get-started-sriov.md, tools/scripts/setNicAddr.sh, tools/scripts/setNicRdmaMode.sh
**Notice**:
"release/none"
"release/bug"
Fixes #
=> doc: set rdma nic

pkg/podownercache/pod_owner_cache_test.go
**Notice**:
"release/none"
"release/bug"
Fixes #4866
Remove redundant async.
https://github.com/spidernet-io/spiderpool/blob/c1eeeff4c2292cca0d9fc3cb653c1a5cd76ffede/pkg/podownercache/pod_owner_cache_test.go#L71
=> Fix unit test of pod owner cache

charts/spiderpool/README.md, charts/spiderpool/templates/deployment.yaml, charts/spiderpool/values.yaml, cmd/spiderpool-controller/cmd/config.go, docs/concepts/ipam-des-zh_CN.md, docs/concepts/ipam-des.md, docs/reference/spiderpool-controller.md, pkg/gcmanager/gc_manager.go, pkg/gcmanager/scanAll_IPPool.go
robot cherry pick PR <https://github.com/spidernet-io/spiderpool/pull/4889> from cyclinder,to branch release-v1.0,  action <https://github.com/spidernet-io/spiderpool/actions/runs/15151807669>  , commits 0cada92884a2d019b9cad78093044ee15c97b275
=> ipam: add GC option for running pods with empty podIPs

charts/spiderpool/files/grafana-rdma-node.json, docs/reference/metrics.md, pkg/rdmametrics/metrics.go, pkg/rdmametrics/tos.go, pkg/rdmametrics/tos_test.go
**Notice**:
"release/none"
"release/bug"
Fixes #4815
1. Call netlink list rdma device
2. Read `/sys/class/infiniband/mlx5_0/tc/1/traffic_class` get traffic class value
=> Add node rdma device traffic class to metrics

tools/scripts/setNicAddr.sh
**Notice**:
"release/none"
"release/bug"
Fixes #
**Release note**:
```release-note
```
=> Add setNicAddr.sh for rhel7

Makefile, test/scripts/debugEnv.sh, test/scripts/install-kubevirt.sh
**Notice**:
"release/none"
"release/bug"
Fixes https://github.com/spidernet-io/spiderpool/issues/5177
**Release note**:
```release-note
```
=> e2e: fix kubevirt vm can't running

charts/spiderpool/templates/configmap.yaml, images/spiderpool-agent/Dockerfile, images/spiderpool-base/install-others.sh, test/scripts/debugEnv.sh, test/scripts/install-kubevirt.sh
**Notice**:
"release/none"
"release/bug"
Fixes #
**Release note**:
```release-note
```
=> Using jq to parse the default CNI for improved script robustness
