- cmd/spiderpool-agent/cmd/command_root.go
- cmd/spiderpool-controller/cmd/command_root.go
- cmd/spiderpoolctl/cmd/command_root.go
No need to keep the 'completion' command for CLI
> hide cobra CLI completion command

- pkg/ipam/ipam.go
- pkg/types/k8s.go
- Return resIPs in execAllocate() when serializing Pod IP allocation fails.
- Change the type of vlan field in pod IP allocation annotation to int.
> fix:Failed to rollback IP when serializing Pod IP allocation annotations

- test/doc/annotation.md
- test/doc/configmap.md
- test/doc/editcrd.md
1. fix case A00004：
- the pod annotation has the highest priority over namespace and global default ippool, with namespace annotation having the second highest priority
2. add case for editcrd.md
- D00006
- D00007
> E2E: add test cases according to the documentation

- charts/spiderpool/templates/deployment.yaml
- pkg/ipam/ipam.go
- pkg/ipam/tools.go
- pkg/ippoolmanager/ippool_manager.go
- pkg/reservedipmanager/reservedip_manager.go
- pkg/workloadendpointmanager/workloadendpoint_manager.go
- test/Makefile
- Update SWE incrementally.
- Fix log always shows "Use IP pools from Namespace annotation".
- Refactor filterPoolCandidates() function.
- Validate "ippools" annotation, make sure that the interface of the pod annotation contains that requested by runtime.
> fix:IP leakage caused by IP rollback failure of incomplete IP allocation

- .github/workflows/lint-license.yaml
fix CI issue: https://github.com/spidernet-io/spiderpool/runs/7249093688?check_suite_focus=true
> ci: change apache/skywalking-eyes to tag version

- test/e2e/common/pod.go
- test/e2e/labelselector/labelselector_suite_test.go
- test/e2e/labelselector/labelselector_test.go
about: test case L00001 L00002 L00003 L00004 L00005 L00006
test case:
L00001 --- succeed to run deployment/pod who is bound to an ippool set with matched nodeSelector
L00002 --- fail to run deployment/pod who is bound to an ippool set with no-matched nodeSelector
L00003 --- succeed to run deployment/pod who is bound to an ippool set with matched namesapceSelector
L00004 --- fail to run deployment/pod who is bound to an ippool set with no-matched namesapceSelector
L00005 --- succeed to run deployment/pod who is bound to an ippool set with matched podSelector
L00006 --- fail to run deployment/pod who is bound to an ippool set with no-matched podSelector
> E2E:fail to run pod who is bound to an ippool set with no-matched selector

- cmd/spiderpool-agent/cmd/config.go
- cmd/spiderpool-agent/cmd/crd_manager.go
- cmd/spiderpool-agent/cmd/daemon.go
- cmd/spiderpool-controller/cmd/crd_manager.go
- cmd/spiderpool-controller/cmd/daemon.go
- cmd/spiderpool/cmd/command_add.go
- cmd/spiderpool/cmd/command_test.go
- pkg/constant/ip.go
- pkg/constant/k8s.go
- pkg/ipam/ipam.go
- pkg/ipam/tools.go
- pkg/ippoolmanager/ippool_manager.go
- pkg/limiter/queue.go
- pkg/podmanager/pod_manager.go
- pkg/reservedipmanager/reservedip_manager.go
- pkg/workloadendpointmanager/workloadendpoint_manager.go
fix:IP leakage caused by too many conflicts when update ippool in high concurrency case
- Introduce a limiter to reduce IPAM concurrency of a single node.
- Refactor function UpdateIPAllocation.
- Do not create Informer for IPPool, Endpoint and ReservedIP. Use API Server clinet to read and write CR to ensure data consistency. These changes also apply to Node, NS and Pod.
- Update annotations with 'fresh' Pod.
> fix:IP leakage caused by too many conflicts when update ippool in high concurrency case

- pkg/gcmanager/pod_cache.go
Init slice capacity firstly to avoid expansion. This change will improve performance and decrease the lock holding duration.
> IP GC podEntry improvement

- test/e2e/reliability/reliability_test.go
ci failure when restart node
this pr fixed various CI failures caused by restarting the host without ready
related issue link:
#474 ,
#458, related logs:
https://github.com/spidernet-io/spiderpool/runs/7512876703?check_suite_focus=true#step:22:1250
> Fixed CI failure caused by node not ready

- pkg/namespacemanager/namespace_manager.go
- pkg/nodemanager/node_manager.go
- pkg/podmanager/pod_manager.go
Remove the Add Index section of NewManager.
In the previous Pr, all the resources that need to be operated are added to the disabled array, so now the client will obtain information directly from the API Server, which initially supports the field selector for Name and Namespace fields.
Thus, the extra index is no longer needed.
@iiiceoo
> Chopped indexe in node，namespace，pod manager

- README.md
- go.mod
- go.sum
- test/e2e/assignip/assignip_test.go
- test/e2e/common/pod.go
- test/e2e/common/tools.go
- test/e2e/ippool/job_pod_test.go
- test/e2e/reclaim/reclaim_test.go
- vendor/github.com/spidernet-io/e2eframework/framework/framework.go
- vendor/github.com/spidernet-io/e2eframework/framework/serviceaccounts.go
- vendor/modules.txt
case G00005: a dirty IP record (pod name is wrong) in the IPPool should be auto clean by Spiderpool 
case G00007: a dirty IP record (pod name is right but container ID is wrong) in the IPPool should be auto clean by Spiderpool
fixed:
#534
#535
> E2E: case G00005, G00007 a dirty IP record in the IPPool shoud be auto clean by Spiderpool

- .github/.spelling
- LICENSE
- cmd/spiderpoolctl/cmd/command_ip.go
- docs/usage/install.md
- test/Makefile
- test/Makefile.defs
- test/e2e/reliability/reliability_test.go
- test/scripts/debugEnv.sh
- test/yamls/kind-config.tmpl
fix https://github.com/spidernet-io/spiderpool/issues/586
> fix: spiderpool-controller encounter "too many open files" error

- api/v1/agent/models/ipam_add_args.go
- api/v1/agent/models/route.go
- api/v1/agent/openapi.yaml
- api/v1/agent/server/embedded_spec.go
- charts/spiderpool/crds/spiderpool.spidernet.io_spiderendpoints.yaml
- cmd/spiderpool/cmd/cni_types.go
- cmd/spiderpool/cmd/command_add.go
- cmd/spiderpool/cmd/command_test.go
- pkg/constant/errors.go
- pkg/constant/ip.go
- pkg/constant/k8s.go
- pkg/ipam/convert.go
- pkg/ipam/ipam.go
- pkg/ipam/ipam_config.go
- pkg/ipam/tools.go
- pkg/ipam/types.go
- pkg/k8s/apis/v1/workloadendpoint_types.go
- pkg/k8s/apis/v1/zz_generated.deepcopy.go
- pkg/types/k8s.go
- test/e2e/annotation/annotation_test.go
- Add verification to some annotations of Pod that are responsible for IP pool selection.
- Add 'CleanGateway' field in SpiderEndpoint to mark the default gateway effectiveness in multi-NIC case.
- Group custom routes specified in Pod annotation by NIC.
> feat:Group the routes in IP allocation result by NIC

- .github/workflows/auto-pr-ci.yaml
- Reduce test time and allow only performance tests to be run in dual stacks.
Fixes #
```
None
```
> E2E: Reduce test time and allow only performance tests to be run in dual stacks.

- go.mod
- go.sum
- test/e2e/common/pod.go
- test/e2e/ippoolcr/ippoolcr_test.go
- vendor/github.com/spidernet-io/e2eframework/framework/kind.go
- vendor/modules.txt
case D00002: Add a route with `routes` and `gateway` fields in the ippool spec, which only takes effect on the new pod and does not on the old pods
case D00003:  Failed to add wrong IPPool gateway and route to an IPPool CR
> E2E: case D00002 edit ippool route and gateway

- test/e2e/affinity/affinity_test.go
Fixed : #718 
failed to run pod who is bound to an ippool set with matched NodeAffinity NamespaceAffinity and PodAffinity
when ippool name not existed  in the podList of the podIPPoolAnnotations，it will return error.
> fix issue 718

- .github/.spelling
- charts/spiderpool/README.md
- charts/spiderpool/templates/configmap.yaml
- charts/spiderpool/templates/role.yaml
- charts/spiderpool/templates/webhook.yaml
- charts/spiderpool/values.yaml
- cmd/spiderpool-agent/cmd/config.go
- cmd/spiderpool-controller/cmd/config.go
- cmd/spiderpool-controller/cmd/daemon.go
- pkg/constant/k8s.go
- pkg/ip/cidr.go
- pkg/ip/ip.go
- pkg/ip/iprange.go
- pkg/ip/utils.go
- pkg/ippoolmanager/ippool_informer.go
- pkg/ippoolmanager/ippool_manager.go
- pkg/ippoolmanager/ippool_validate.go
- pkg/ippoolmanager/ippool_webhook.go
- pkg/ippoolmanager/utils.go
- pkg/k8s/apis/spiderpool.spidernet.io/v1/rbac.go
- pkg/reservedipmanager/reservedip_validate.go
- pkg/reservedipmanager/reservedip_webhook.go
- pkg/subnetmanager/subnet_manager.go
- pkg/subnetmanager/subnet_validate.go
- pkg/subnetmanager/subnet_webhook.go
- Add SubnetManager to provide standard Get and List methods for SpiderSubnet.
- Provides basic field verification when creating SpiderSubnet CR.
- Merge the 'ips' and 'excludeIPs' field of SpiderSubnet, SpiderIPPool and SpiderReservedIP, when its CR is created or updated.
> feat:Add webhook of SpiderSubnet

- test/e2e/affinity/affinity_test.go
- test/e2e/common/spiderpool.go
- test/e2e/reclaim/reclaim_test.go
- test/e2e/reliability/reliability_test.go
- test/e2e/reservedip/reservedip_suite_test.go
- test/e2e/reservedip/reservedip_test.go
/issue-bug pr/release/none-required
- add e2e case L00008 for spiderpool
- Successfully restarted statefulSet/pod with matching podSelector, ip remains the same
- add e2e case A00009 for spiderpool
- Modify the annotated IPPool for a specified Deployment pod; Modify the annotated IPPool for a specified StatefulSet pod
#684
> E2E: add test case L00008 && A00009 for spiderpool

- test/doc/cidr.md
add cidr case
- Multiple automatic creation and recycling of ippools, eventually the free IPs in the subnet should be restored to its initial state
- Multiple manual creation and recycling of ippools, eventually the free IPs in the subnet should be restored to its initial state
> E2E：Add case on CIDR IP leakage

- pkg/ipam/config.go
- pkg/ipam/ipam.go
> Ignore pool selection rules for IPv4/6 IPAM when IPv4/6 is disabled, instead of returning an error

- tools/scripts/cleanCRD.sh
> fix:Missing resource type when cleaning SpiderEndpoint CRs in cleanCRD.sh

- test/e2e/annotation/annotation_test.go
- test/e2e/common/spiderpool.go
- test/e2e/common/tools.go
- test/e2e/ippoolcr/ippoolcr_test.go
- Fix: When the ipv6 address is `fd00:015d::1`, but in the pod it is` fd00:15d::1`, 
- in this case, using "ip -6 r | grep 'default via fd00:015d::1'" does not retrieve the content, so os/exec will return an error when executed
#860 
#850 
> fix: ipv6 address validity issue

- pkg/ippoolmanager/ippool_validate.go
- pkg/subnetmanager/subnet_informer.go
- pkg/subnetmanager/subnet_validate.go
- In the webhook of SpiderIPPool and SpiderSubnet, old CR is no longer used to calculate the removed IP addresses.
- When removing some non free IP ranges from SpiderSubnet, the name of the IPPool to which they belong will now be notified in the rejection message.
- Optimized the judgment of removing SpiderSubnet finalizer.
> fix:Failed to remove free IP addresees in SpiderSubnet

- cmd/spiderpool-agent/cmd/crd_manager.go
- pkg/ippoolmanager/ippool_informer.go
- pkg/ippoolmanager/ippool_manager.go
- pkg/ippoolmanager/ippool_webhook.go
- pkg/k8s/apis/spiderpool.spidernet.io/v1/types_string.go
1. Remove scale IPPool function retries, and let the error requeue. This will avoid some bad data update.
2. Add client disable cache for SpiderSubnet
> discard to retry scale IPPool and all error requeue

- cmd/spiderpool-agent/cmd/config.go
- cmd/spiderpool-agent/cmd/daemon.go
- cmd/spiderpool-agent/cmd/runtime_status.go
- cmd/spiderpool-agent/cmd/unix_server.go
- cmd/spiderpool-controller/cmd/config.go
- cmd/spiderpool-controller/cmd/crd_manager.go
- cmd/spiderpool-controller/cmd/daemon.go
- cmd/spiderpool-controller/cmd/runtime_status.go
fix spiderpool-agent OOM
https://github.com/spidernet-io/spiderpool/issues/917
With the previous sources codes, we'll new a golang http client every liveness probe. And we do not disable 'KeepAlive' and set 'Timeout' for this http client. 
After checking the golang source codes, the golang will use 'KeepAlive' by default.
Once a http client sends a request it will start 2 goroutines 'readLoop' and 'writeLoop', and the server endpoint will start 1 goroutine to handle with the 'tcp/udp' connection. 
Here's the source codes:
https://github.com/golang/go/blob/e09bbaec69a8ff960110e13eabb3bef5331ecb0c/src/net/http/server.go#L3072 …
> fix spiderpool-agent oom

- cmd/spiderpool-controller/cmd/config.go
- cmd/spiderpool-controller/cmd/daemon.go
- pkg/ippoolmanager/config.go
- pkg/ippoolmanager/ippool_informer.go
- pkg/ippoolmanager/ippool_manager.go
- pkg/ippoolmanager/ippool_validate.go
- pkg/ippoolmanager/types/interface.go
- pkg/reservedipmanager/reservedip_manager.go
- pkg/reservedipmanager/utils.go
- pkg/subnetmanager/subnet_informer.go
- pkg/subnetmanager/subnet_manager.go
1. separate controller to v4/v6 to accelerate auto-ippool event to accelerate V4/V6 IPPool generates IPs from each subnet
2. fix ippool status allocatedIPCount update
3. use workqueue for all IPPool status count calculate
> separate controller to v4/v6 to accelerate auto-ippool event

- pkg/ipam/ipam.go
Once we use statefulset dual stack and allocated IPv4 successfully but failed to allocated IPv6.
In this case, the SpiderEndpoint object is exist but the status current IP allocation was rolled back and no data. 
We should continue process it 
---
fix bug 
https://github.com/spidernet-io/spiderpool/issues/1034
> fix statefulset ip allocation retrieve

- pkg/subnetmanager/subnet_informer.go
> fix:Panic happens occasionally when setting the label of the owner SpiderSubnet to which the SpiderIPPool belongs

- cmd/spiderpool-controller/cmd/config.go
- cmd/spiderpool-controller/cmd/daemon.go
- go.mod
- pkg/ippoolmanager/ippool_informer.go
- pkg/ippoolmanager/ippool_manager.go
- pkg/subnetmanager/config.go
- pkg/subnetmanager/controllers/cronjob_informer.go
- pkg/subnetmanager/controllers/daemonset_informer.go
- pkg/subnetmanager/controllers/deployment_informer.go
- pkg/subnetmanager/controllers/job_informer.go
- pkg/subnetmanager/controllers/replicaset_informer.go
- pkg/subnetmanager/controllers/statefulset_informer.go
- pkg/subnetmanager/controllers/utils.go
- pkg/subnetmanager/subnet_controller.go
- pkg/subnetmanager/subnet_manager.go
- pkg/subnetmanager/types/interface.go
1. Fix subnet create ippool asynchronous multile ippools issue, change auto-created ippool name with uuid.
2. Add workqueue for application controller, in which case we can create different IPPools asynchronously.(The same IPPool will be processed synchronously)
3. In the dual stack, we created 40 app and it cost almost 50s to create empty IPPools
fix bug
https://github.com/spidernet-io/spiderpool/issues/1088
> fix subnet create ippool asynchronous multile ippools issue

- cmd/spiderpool-controller/cmd/config.go
- pkg/ippoolmanager/ippool_informer.go
- pkg/ippoolmanager/ippool_manager.go
- pkg/subnetmanager/subnet_controller.go
- pkg/subnetmanager/subnet_informer.go
1.add more workers for IPPool and App controller
2.decrease the requeue delay duration
3.fix application controller error handler
After test, we will cost 36s to create empty auto-created IPPools and flush the autoDesiredIPNumber for 40 deployments in dual stack. And it will cost 77s for subnet to allocate IPs for these auto-created IPPools.
Signed-off-by: Icarus9913 icaruswu66@qq.com
1.fix bug
2.improve subnet controller performance
https://github.com/spidernet-io/spiderpool/issues/1102
https://github.com/spidernet-io/spiderpool/issues/1100
> improve subnet controller performance

- docs/usage/install.md
> docs: Fix typo 'cleanCRD.sh' -> './cleanCRD.sh'

- test/doc/reservedip.md
- test/e2e/subnet/subnet_test.go
The test case involves the following: 
1、check that manually created ippools will automatically avoid excludeIPs for subnets
2、how does modifying subnet routes and gateways affect manually created ippools
3、Add and delete ip in the subnet
> E2E: add some cases about updating routes and gateways and excludeIPs.

- pkg/ippoolmanager/ippool_informer.go
- pkg/ippoolmanager/ippool_manager.go
- pkg/ippoolmanager/types/interface.go
- pkg/ippoolmanager/utils.go
- pkg/subnetmanager/controllers/utils.go
For auto-create IPPool workqueue enqueue cases:
1. The IPPool's IPs number is not equal with the auto-desired IP number, we'll try to scale it.
2. The IPPool's allocated IPs are empty, we will check whether the IPPool should be deleted or not.
fix bug
https://github.com/spidernet-io/spiderpool/issues/1129
> add auto-created ippool gc

- .github/.spelling
- docs/develop/upgrade.md
- docs/mkdocs.yml
- docs/usage/spider-subnet.md
- pkg/ippoolmanager/ippool_informer.go
- pkg/subnetmanager/controllers/utils.go
⚠️⚠️⚠️ This change is  make it incompatible with the previous release version
(The ipam and spiderpool-controller will use this label to find the application corresponding auto-created IPPool, once we change it. It's incompatible with the previous version spiderpool)
⚠️⚠️⚠️ For upgrade pre-steps, please check [upgrade.md](https://github.com/spidernet-io/spiderpool/blob/b73c976609b0f7bf7ca4581db2973cb6ab4aa6ce/docs/develop/upgrade.md)
The correlative PR: https://github.com/spidernet-io/spiderpool/pull/1135 implements auto-created IPPool garbage collect, it will use the IPPool label `ipam.spidernet.io/owner-application` to trace back the corresponding application.
But the current function implementation just use '-' to assemble the application identification.
```go 
// AppLabelValue will …
```
> change the label of auto-created ippool for GC needs

- pkg/ippoolmanager/ippool_informer.go
> fix: The field `status.allocatedIPCount` of SpiderIPPool was incorrectly updated to -1

- test/doc/annotation.md
- test/doc/cidr.md
- test/e2e/annotation/annotation_suite_test.go
- test/e2e/annotation/annotation_test.go
- test/e2e/reservedip/reservedip_test.go
This pr will add e2e case I00011 and A00010
I00011: The subnet automatically creates an ippool and allocates IP, and should consider reservedIP 
A00010: "Successfully run pods with multi-NIC ippools annotations
none
none
> E2E: The subnet automatically creates an ippool and allocates IP, and should consider reservedIP

- pkg/workloadendpointmanager/workloadendpoint_manager.go
robot cherry pick pr <https://github.com/spidernet-io/spiderpool/pull/1190> to branch release-v0.3,  action <https://github.com/spidernet-io/spiderpool/actions/runs/3728543354>  , commits 5a0b45eb7755376f6216fd36b5030ad32defdd56
> fix: The normal IP addresses are recycled by mistake when multiple Pods with the same namespace and name are created in a short time

- .github/.spelling
- charts/spiderpool/README.md
- charts/spiderpool/templates/configmap.yaml
- charts/spiderpool/values.yaml
- cmd/spiderpool-agent/cmd/config.go
- cmd/spiderpool-agent/cmd/daemon.go
- cmd/spiderpool-controller/cmd/config.go
- cmd/spiderpool-controller/cmd/daemon.go
- cmd/spiderpool-init/cmd/root.go
- docs/concepts/allocation.md
- docs/concepts/annotation.md
- docs/concepts/config.md
- docs/develop/upgrade.md
- docs/example/spider-subnet/cluster-default-subnet-deployment.yaml
- docs/example/spider-subnet/multiple-interfaces.yaml
- docs/usage/spider-subnet.md
- pkg/constant/k8s.go
- pkg/ipam/ipam.go
- pkg/singletons/singleton.go
- pkg/subnetmanager/app_controller.go
- pkg/subnetmanager/controllers/utils.go
- pkg/subnetmanager/subnet_manager.go
- pkg/subnetmanager/types/interface.go
- pkg/types/k8s.go
- pkg/types/types_string.go
- test/Makefile
- test/e2e/reservedip/reservedip_test.go
- test/e2e/subnet/subnet_test.go
- test/scripts/installTestPod.sh
⚠️⚠️⚠️ This change is make it incompatible with the previous release version
(We add another label for auto-created IPPool, which ipam and spiderpool-controller will rely on it.)
⚠️⚠️⚠️ For upgrade pre-steps, please check [upgrade.md](https://github.com/spidernet-io/spiderpool/blob/b73c976609b0f7bf7ca4581db2973cb6ab4aa6ce/docs/develop/upgrade.md)
1. Add cluster default subnet support. Once we use SpiderSubnet feature, we can set no other annotations for the application and it will use SpiderSubnet with ClusterDefaultSubnet which is specified in the configmap. (only support single Interface)
2. Add SpiderSubnet multiple Interface support.
3. Update SpiderSubnet usage document.
new feature
> Add ClusterDefaultSubnet and SpiderSubnet multiple interfaces support

- pkg/subnetmanager/app_controller.go
- pkg/subnetmanager/subnet_manager.go
- pkg/subnetmanager/types/interface.go
For auto-created IPPool, I think there's no need to inherit the application matchLabel(podAffinity).
Because for IPAM or spiderpool-controller components, we just use the label to search the IPPool and no need podAffinity to do a filter. 
fix bug
https://github.com/spidernet-io/spiderpool/issues/1252
> fix potential panic with SpiderSubnet feature

- pkg/subnetmanager/app_controller.go
- pkg/subnetmanager/subnet_manager.go
- pkg/subnetmanager/types/interface.go
After PR [#1242](https://github.com/spidernet-io/spiderpool/pull/1242), we still decide to add application match label for auto-created IPPool.
Here's a usage case:
Once we set the `ipam.spidernet.io/ippool-reclaim` with `true`, we can still use this IPPool after the application was deleted.
And we can use the `podAffinity` to bind another application with the corresponding match labels.
fix bug
https://github.com/spidernet-io/spiderpool/pull/1260#issue-1522348860
> auto-created IPPool podAffinity adjustment

- docs/usage/third-party-controller.md
- pkg/ipam/ipam.go
- test/e2e/kruise/kruise_test.go
This PR will add third-party controller SpiderSubnet feature support.
It will run good with cluster default subnet, specified subnet with single/multiple interfaces.
new feature
https://github.com/spidernet-io/spiderpool/issues/1139
> add third party controller application support with SpiderSubnet feature

- cmd/spiderpool-agent/cmd/daemon.go
- pkg/ippoolmanager/ippool_mutate.go
- pkg/ippoolmanager/ippool_webhook_test.go
> fix: Occasionally failed to set the correct SpiderSubnet owner ref in the unit test of SpiderIPPool

- pkg/gcmanager/pod_cache.go
With the previous investigation, the zap logger would cost extra time duration in the sensitive situation within a lock. So, I just let all logger print out of the lock scope.
improvement
https://github.com/spidernet-io/spiderpool/issues/1290
> improve IP GC long time lock keeping issue

- cmd/spiderpool-controller/cmd/config.go
- cmd/spiderpool-controller/cmd/daemon.go
- pkg/ippoolmanager/ippool_informer.go
- pkg/metric/metrics_instance.go
- pkg/subnetmanager/app_controller.go
- pkg/subnetmanager/config.go
- pkg/subnetmanager/controllers/controller.go
- pkg/subnetmanager/controllers/utils.go
- pkg/subnetmanager/subnet_manager.go
1. Decouple application operation for creating auto-created IPPools with SubnetManager.
2. Remove deleting stale auto-created ippool operation with SpiderSubnet feature
3. Add auto-created IPPool creation/mark operation conflicts and ippool informer operation conflicts metrics
> SpiderSubnet feature app operator refactor

- charts/spiderpool/templates/role.yaml
- pkg/ipam/ipam.go
- pkg/ippoolmanager/ippool_manager.go
- pkg/k8s/apis/spiderpool.spidernet.io/v1/rbac.go
- pkg/subnetmanager/subnet_manager.go
In the previous version, we'll try to get All corresponding IPPools and delete them if one orphan pod was deleting in SpiderSubnet feature.
Now, we can just use DeleteAll method to delete them directly. That can decrease several Network requests. 
> aggreate orphan pod auto-created IPPools deletion operation with SpiderSubnet feature

- cmd/spiderpool-agent/cmd/config.go
- cmd/spiderpool-agent/cmd/daemon.go
- cmd/spiderpool-controller/cmd/config.go
- cmd/spiderpool-controller/cmd/crd_manager.go
- cmd/spiderpool-controller/cmd/daemon.go
- pkg/ipam/ipam.go
- pkg/ipam/utils.go
- pkg/ippoolmanager/ippool_informer.go
- pkg/ippoolmanager/ippool_manager.go
- pkg/subnetmanager/app_controller.go
- pkg/subnetmanager/subnet_manager.go
- test/e2e/reservedip/reservedip_test.go
1.modify ipam fetch subnet auto-created IPPool retry times and retry duration (Previously, the ipam component will leave 6s for those pods that use SpiderSubnet feature. The IPPool informer will scale the IPPools one by one to avoid conflict. So, if someone create multiple applications in a short time, some IPPool will wait for the previous IPPool scaled up.)
2.add IPPool informer resync filter for watching SpiderSubnet object corresponding IPPools. (In the previous version, we will enqueue SpiderSubnet corresponding IPPools once the SpiderSubnet changed. For the design, we make the IPPool and SpiderSubnet asynchronous because there's one situation that the SpiderSubnet's IPs are used out and the Auto-created IPPool allocation will fail immediately. And in the asynchronous architecture, …
> modify ipam fetch subnet IPPool retry operation times and duration

- pkg/ippoolmanager/ippool_manager.go
> fix: The Pod UID of the record in the SpiderIPPool is not updated after the StatefulSet's Pod is recreated

- pkg/applicationcontroller/app_controller.go
In the application controller, we found the `deployment.APIVersion` is empty string once we get the deployment object yaml. 
Consequently, we can just set it with `appsv1.SchemeGroupVersion.String()` directly
> fix application controller empty APIVersion string

- pkg/applicationcontroller/app_controller.go
- pkg/applicationcontroller/applicationinformers/utils.go
- pkg/constant/k8s.go
- pkg/ipam/allocate.go
- pkg/ipam/utils.go
- pkg/ippoolmanager/ippool_informer.go
- pkg/ippoolmanager/utils.go
- pkg/podmanager/pod_manager.go
- pkg/subnetmanager/subnet_informer.go
- pkg/subnetmanager/subnet_manager.go
1. In issue https://github.com/spidernet-io/spiderpool/issues/1486, I found that the IPPool-informer regards the openKruise StatefulSet as Kubernetes appsv1 Statefulset. 
If one pod's top controller is StatefulSet, we should make sure that the StatefulSet object is `apps/v1` group version
2. I removed the IPPool label `ipam.spidernet.io/owner-application`  and add one annotation `ipam.spidernet.io/application`.  Only the Application auto-created IPPools (SpiderSubnet feature) will hold this annotation, and it records the corresponding application apiVersion, kind, namespace, name. The format of this value is "{apiVersion}:{appKind}:{appNS}:{appName}"
> add apiversion check for statefulset pod

- pkg/ipam/release.go
> fix: The field deletionGracePeriodSeconds of Pod may be nil in K8s <=1.22

- cmd/spiderpool-controller/cmd/daemon.go
- pkg/applicationcontroller/app_controller.go
- pkg/ipam/pool_selections.go
- pkg/subnetmanager/subnet_manager.go
In SpiderSubnet feature, we'll acquire IPs from SpiderSubnet object to apply the auto-created IPPool. But there are 2 API operations in the whole operation, so if the first API operation succeed but the second failed,  just like the issue mentioned. We need to correct the SpiderSubnet status.
fix bug
https://github.com/spidernet-io/spiderpool/issues/1520
> fix auto-pool shrink failure issue

- cmd/spiderpool-controller/cmd/config.go
- pkg/gcmanager/gc_manager.go
- pkg/gcmanager/scanAll_IPPool.go
1. Set the default IP GC trace pod workers to 1.
2. In the past IP GC scan all architecture, we scan the IPPools one by one and this will cost a long time. So, I make the IPPools into IPv4 IPPools and IPv6 IPPools with 2 goroutines, and each IPPools will still be scanned one by one because I'm afraid that If I set up one goroutine for each IPPool will lead to too many goroutines. 
> modify default IP GC workers and make IP GC scan all dual stack concurrency

- pkg/subnetmanager/subnet_informer.go
Add one more check after we checked the application not exist in SpiderSubnet informers. When the application doesn't exist, we still need to check whether the IPPool exists and decide to update the SpiderSubnet status allocations.
fix bug
> fix: Subnet status IPPool allocations disappears but the IPPool still exist

- cmd/spiderpool-controller/cmd/daemon.go
- cmd/spiderpool-controller/cmd/runtime_status.go
- pkg/election/lease_election.go
- pkg/election/lease_election_test.go
- pkg/election/mock/lease_election_mock.go
- pkg/gcmanager/gc_manager.go
- pkg/gcmanager/pod_informer.go
I supplement spiderpool-controller readiness probe. 
For those backup spiderpool-controller pod, after it detects there's a master in the cluster it will be ready.
For the master spiderpool-controller pod, only it gets the master elector and wait for IP GC informer factory cache synced, it will be ready.
> supplement spiderpool controller readiness probe

- cmd/spiderpool-controller/cmd/config.go
- cmd/spiderpool-controller/cmd/daemon.go
- pkg/gcmanager/gc_manager.go
- pkg/gcmanager/tracePod_worker.go
I added limiter to IP GC trace pod worker function, this could make it use several workers and concurrency.
Additionally, I improved the trace pod worker IP release operation, the previous codes would release IP one by one. But now, it would release those different IPPool IPs  concurrently.
Reference PR: https://github.com/spidernet-io/spiderpool/pull/1525
> add limiter for IP GC pod informer architecture

- cmd/spiderpool-controller/cmd/config.go
The leader election are the common component not only belongs to IP GC.  So, we need change the envName from `SPIDERPOOL_GC_LEADER_DURATION` to `SPIDERPOOL_LEADER_DURATION`.
> modify spiderpool-controller leader election env configuration

- cmd/spiderpool/cmd/cni_types.go
According to the [CNI Spec](https://github.com/containernetworking/cni/blob/spec-v1.0.0/SPEC.md), compared with the previous versions, the additional features are aimed at Main CNI not IPAM. 
So, we can just support CNI V1.0.0 directly.
new feature
> support CNI V1.0.0

- docs/mkdocs.yml
Update nav list manually:
- Divide `Usage` into 3 chapters: quick start, installation, and usage
- Sort `Concepts` in the alphabetical order
Current `usage` has too many pages, which can be divided into several channels.
Fix #1586
> [doc] update nav list

- cmd/spiderpool-controller/cmd/config.go
- pkg/gcmanager/gc_manager.go
- pkg/gcmanager/pod_cache.go
- pkg/gcmanager/pod_informer.go
- pkg/gcmanager/tracePod_worker.go
The spiderpool with the previous version, the IP GC `pod informer` mechanism will only try to release IP once.
In a big cluster, for instance if you have one deployment with 1000 replicas and you gonna delete the deployment. There will be one situation the CNI cmdDel was called with IP GC `pod informer` worker are concurrent. (The kubernetes controller would not delete the whole 1000 pods at the same time.)
In this case, the `pod informer` worker release IP will also meet conflict and we need the IP GC `scan all` mechanism to release the legacy IPs in the end.
So, I just let the IP GC `pod informer` worker release operation several times when it meets conflict. This will make IP GC more efficient.
> make IP GC pod informer mechanism requeue if it failed to release IP

- pkg/ippoolmanager/ippool_subnet_validate.go
- pkg/ippoolmanager/ippool_webhook_test.go
For the auto-created IPPool with SpiderSubnet feature, it's allow to change the Spec.IPs by yourself in the previous version. But it's a little strange to do that, because the spiderpool-controller will turn it back with the auto desired IP number later.
So, I think we should forbidden modifying auto-created IPPool by hand.
fix bug
https://github.com/spidernet-io/spiderpool/issues/1609
> forbidden modifying auto-created IPPool by hand

- cmd/spiderpool-controller/cmd/runtime_status.go
- pkg/gcmanager/gc_manager.go
Because of the inaccurate IP GC health check, the spiderpool-controller readiness probe check leads to inadequate ready.
fix bug
https://github.com/spidernet-io/spiderpool/issues/1612
> fix IP GC health inaccurate check

- charts/spiderpool/templates/role.yaml
- cmd/spiderpool-controller/cmd/daemon.go
- pkg/applicationcontroller/applicationinformers/utils.go
- pkg/ipam/pool_selections.go
- pkg/ippoolmanager/ippool_informer.go
- pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/rbac.go
- pkg/subnetmanager/subnet_informer.go
- pkg/subnetmanager/subnet_manager.go
- test/e2e/kruise/kruise_test.go
- vendor/k8s.io/client-go/dynamic/dynamicinformer/informer.go
- vendor/k8s.io/client-go/dynamic/dynamicinformer/interface.go
- vendor/k8s.io/client-go/dynamic/dynamiclister/interface.go
- vendor/k8s.io/client-go/dynamic/dynamiclister/lister.go
- vendor/k8s.io/client-go/dynamic/dynamiclister/shim.go
- vendor/modules.txt
This pr will make third-party controller use SpiderSubnet feature to create auto-created IPPools can be deleted if the application deleted
new feature
> support third-party auto-created pool delete

- pkg/ippoolmanager/ippool_validate.go
- pkg/ippoolmanager/ippool_webhook_test.go
- pkg/subnetmanager/subnet_validate.go
- pkg/subnetmanager/subnet_webhook_test.go
- test/e2e/subnet/subnet_test.go
> fix: SpiderSubnet or SpiderIPPool can use `spec.routes` to configure duplicate routes or default route

- pkg/ippoolmanager/ippool_mutate.go
- pkg/reservedipmanager/reservedip_mutate.go
- pkg/subnetmanager/subnet_mutate.go
> fix: The log of merging `spec.ips` and `spec.excludeIPs` in the mutating webhook is not accurate

- .github/workflows/build-image-base.yaml
- .github/workflows/build-image-ci.yaml
- .github/workflows/call-release-image.yaml
The multi-architecture image produced by build-push-action will contain an image of the unknown architecture.
The solution is: https://github.com/docker/build-push-action/issues/820#issuecomment-1484092146
https://github.com/docker/build-push-action/issues/820
> fix build-push-action produces unknown arch

- charts/spiderpool/templates/deployment.yaml
- cmd/spiderpool-agent/cmd/runtime_status.go
- cmd/spiderpool-controller/cmd/runtime_status.go
- pkg/gcmanager/gc_manager.go
With several e2e failed, I checked the spiderpool-controller restart readiness check is not accurate. The spiderpool-controller counts on leader election. If one spiderpool-controller elects the IP GC pod informer will start, and the other backup spiderpool-controller will pass readiness check as soon as possible.
For example, the spiderpool-controller pods ran good in the first round. And I delete them with force and the new pods will run. But the round 2 spiderpool-controller pods found leader(round 1 leader not expired) and all passed the readiness check. You know, the round 2 spiderpool-controller pods also need to wait for the round 1 leader expired and try to work. 
So, I just add readiness initialDelaySeconds to wait for a leader duration.
Signed-off-by: Icarus9913 …
> add readiness initialDelaySeconds for spiderpool-controller

- .github/ISSUE_TEMPLATE/bug_report.md
/kind cleanup
When new a issue , shows the wrong message , like above pic..
> fix issue template

- pkg/ip/iprange.go
- pkg/ip/iprange_test.go
- pkg/ippoolmanager/ippool_validate.go
- pkg/ippoolmanager/ippool_webhook_test.go
- pkg/subnetmanager/subnet_validate.go
- pkg/subnetmanager/subnet_webhook_test.go
Added some validations for `spec.gateway` to avoid gateway addresses being used by an unrelated Pod.
Close #1646 
> fix: The gateway addresses of SpiderSubnet and SpiderIPPool conflict with `spec.ips`

- pkg/ip/iprange.go
- pkg/ip/iprange_test.go
- pkg/ippoolmanager/ippool_validate.go
- pkg/ippoolmanager/ippool_webhook_test.go
- pkg/subnetmanager/subnet_validate.go
- pkg/subnetmanager/subnet_webhook_test.go
robot cherry pick pr <https://github.com/spidernet-io/spiderpool/pull/1671> to branch release-v0.4,  action <https://github.com/spidernet-io/spiderpool/actions/runs/4716239395>  , commits 88328ae4f619b211c4f3e6101f0b46b41a8ec350
> title:	fix: The gateway addresses of SpiderSubnet and SpiderIPPool conflict with `spec.ips`

- pkg/ippoolmanager/ippool_informer.go
- pkg/subnetmanager/subnet_informer.go
The reason of the panic is wrong golang defer usage.
```golang
defer func() {
if err == nil {
attr := attribute.String(constant.KindSpiderIPPool, pool.Name)
metric.IPPoolTotalIPCounts.Add(ctx, *pool.Status.TotalIPCount, attr)
metric.IPPoolAvailableIPCounts.Add(ctx, (*pool.Status.TotalIPCount)-(*pool.Status.AllocatedIPCount), attr)
}
}()
```
At the top of the function, the `*pool.Status.TotalIPCount` is nil even I set value for it later.
fix bug
close #1682
> fix metric record

- charts/spiderpool/crds/spiderpool.spidernet.io_spiderippools.yaml
- pkg/applicationcontroller/app_controller.go
- pkg/applicationcontroller/applicationinformers/utils.go
- pkg/applicationcontroller/applicationinformers/utils_test.go
- pkg/constant/k8s.go
- pkg/gcmanager/gc_manager.go
- pkg/ipam/allocate.go
- pkg/ipam/pool_selections.go
- pkg/ippoolmanager/ippool_informer.go
- pkg/ippoolmanager/ippool_webhook_test.go
- pkg/ippoolmanager/utils.go
- pkg/ippoolmanager/utils_test.go
- pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/spiderippool_types.go
- pkg/subnetmanager/subnet_manager.go
- pkg/types/k8s.go
- test/e2e/kruise/kruise_test.go
⚠ BREAKING CHANGES
This is a new feature for SpdiderSubnet.
In the past, one deployment created with SpiderSubnet feature and we set `ipam.spidernet.io/ippool-reclaim` to keep the IPPool after the deployment object deleted. In this situation, we can use `ipam.spidernet.io/ippool` or `ipam.spidernet.io/ippools` annotation to reuse this IPPool. But in this way, the pool will switch to `normal IPPool` from `Auto IPPool`. 
In order to reuse this IPPool and still make it as a `Auto IPPool` for the same ns,name application. Just for instance, one deployment deployed and the administrator set the Firewall at first. But later the deployment upgrades and wanna redeploy, it will cost a lot to rebuild the IPPool. Because if we try to reuse the previous IPPool with `ipam.spidernet.io/ippool`, it'll …
> SpiderSubnet auto-created IPPool reuse

- .github/workflows/call-release-image.yaml
robot cherry pick pr <https://github.com/spidernet-io/spiderpool/pull/1732> to branch release-v0.5,  action <https://github.com/spidernet-io/spiderpool/actions/runs/4819166725>  , commits 203f5d8bce78e845c0036567e6489ceb2cc2f670
> title:	typo ci

- pkg/applicationcontroller/app_controller.go
- pkg/applicationcontroller/applicationinformers/utils.go
- pkg/constant/k8s.go
- pkg/ipam/pool_selections.go
- pkg/ippoolmanager/ippool_informer.go
- pkg/ippoolmanager/ippool_informer_test.go
- pkg/ippoolmanager/ippool_webhook_test.go
- pkg/ippoolmanager/utils.go
- pkg/ippoolmanager/utils_test.go
- pkg/subnetmanager/subnet_manager.go
- test/e2e/kruise/kruise_test.go
Change auto-created IPPool application NamespacedName label because of value max length limitation. 
In the past,  we would assemble the auto pool corresponding application APIVersion, kind, NS and name to one string. But the kubernetes limit the label value max length to 63.
And I realized the kubernetes metadata name length also limits to 63. So I separate it.
fix bug
close #1747
> fix Auto IPPool label value over maximum length limit

- test/e2e/common/spiderpool.go
> e2e fix: add curl command max time for webhook service health check

- pkg/constant/k8s.go
- pkg/ippoolmanager/ippool_validate.go
- pkg/ippoolmanager/ippool_webhook_test.go
- vendor/k8s.io/apimachinery/pkg/apis/meta/v1/validation/validation.go
- vendor/modules.txt
Add IPPool podAffinity validation, the auto-created IPPool has its special podAffinity(labelSelector) and the user don't need to modify it. And the normal IPPool follow the kubernetes standard labelSelector rules.
fix bug
close #1805
> add ippool podAffinity validation

- cmd/spiderpool-controller/cmd/daemon.go
- pkg/coordinatormanager/coordinator_informer.go
The coordinator should collect the CIDR of the cluster from the
cmd parameters of the kube-controller-manager instead of the
CM kubeadm-config.
Signed-off-by: iiiceoo <iiiceoo@foxmail.com>
> fix: Update the collection method of cluster CIDR

- cmd/spiderpool-agent/cmd/daemon.go
- cmd/spiderpool-controller/cmd/daemon.go
We need new a variable in the goroutines rather than reuse the same error varibale.
fix bg
close #1831
> fix spiderpool-agent daemon data race

- pkg/lock/lock_debug.go
I found lots of e2e failure because of lock detection. 
So, I suggest to change the lock detection duration from 0.2 seconds to 0.5 seconds.
> update lock detect SelfishThresholdSec duration to 0.5 seconds

- pkg/gcmanager/scanAll_IPPool.go
I make the `monitorGCSignal` initial scan all signal sending runs in goroutine. And it surely not blocks the for loop.
fix bug
close #1882
> fix IP GC scan all running unhealthy

- Makefile
- cmd/spiderpool-controller/cmd/daemon.go
Just new the singleton http.client at first. This can avoid the singleton http.client `set` and `get` at the same time.
fix bug
close #1908
> fix spiderpool-controller startup potential datarace

- pkg/gcmanager/pod_cache.go
In the IP-GC pod-informer architecture, we'll trace all terminating pod. But there are also some HostNetwork Pod and these pods never use Spiderpool IPs. Consequently, there's no need for us to record these pods.
> IP-GC improvement with discarding tracing hostnetwork pod

- charts/spiderpool/crds/spiderpool.spidernet.io_spidermultusconfigs.yaml
- pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/spidermultus_types.go
- pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/zz_generated.deepcopy.go
- pkg/multuscniconfig/multusconfig_informer.go
- pkg/multuscniconfig/utils.go
There's a bug about the multus-config CNI configuration master name faults.
And I reuse the ifacer cmd struct rather than a custom one
fix bug
close #1969
> fix multus-config CNI configuration master name faults and ifacer incorresponding configuration

- cmd/coordinator/cmd/command_add.go
- pkg/networking/ipchecking/ipchecking.go
---
---
---
If  the feature: `IP Conflict detection` is enabled, we must make sure that the `ARP/NDP` client is initialized in the main goroutine and in the pod's netns, not a new goroutine.
```
test-multus-8950a5d744]: error adding container to network "test-multus-8950a5d744": failed to ip checking: failed to init arp client: listen packet 0a:d7:2d:a6:81:62: bind: no such device
```
```
error adding container to network "test-multus-0e130ba0ac": failed to ip checking: failed …
```
> fix failed to init arp client

- pkg/ippoolmanager/ippool_mutate.go
- pkg/ippoolmanager/ippool_webhook_test.go
- test/e2e/annotation/annotation_test.go
The IPPool should inherits subnet gateway, routes, vlan if not specified
fix bug
close https://github.com/spidernet-io/spiderpool/issues/1958
> ippool inherits subnet properties 

- pkg/multuscniconfig/multusconfig_informer.go
- pkg/multuscniconfig/multusconfig_validate.go
---
---
---
spidermultusconfig: improve parameters validate
```
{"level":"INFO","ts":"2023-07-27T08:41:12.249Z","logger":"Coordinator-Informer","caller":"coordinatormanager/coordinator_informer.go:284","msg":"Succeed to SYNC","CoordinatorName":"default","Operation":"PROCESS"}
E0727 08:41:12.337796       1 runtime.go:79] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 268 …
```
> spidermultusconfig: improve parameters validate

- charts/spiderpool/crds/spiderpool.spidernet.io_spidercoordinators.yaml
- charts/spiderpool/crds/spiderpool.spidernet.io_spidermultusconfigs.yaml
- cmd/coordinator/cmd/cni_types.go
- cmd/coordinator/cmd/command_add.go
- cmd/spiderpool-init/cmd/root.go
- docs/develop/contributing.md
- pkg/coordinatormanager/coordinator_informer.go
- pkg/coordinatormanager/coordinator_mutate.go
- pkg/coordinatormanager/coordinator_validate.go
- pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/spidercoordinator_types.go
- pkg/multuscniconfig/multusconfig_validate.go
- pkg/networking/networking/ip.go
- test/e2e/coordinator/macvlan-overlay-one/macvlan_overlay_one_test.go
- test/e2e/spidermultus/spidermultus_test.go
- test/scripts/config-network.sh
- test/scripts/install-multus.sh
(1)
CoordinatorSpec is used by SpiderCoordinator and SpiderMultusConfig
in spidermultusconfig CRD , podCIDRType should not be required, which could be merged from SpiderCoordinator CR
but in SpiderCoordinator CRD, podCIDRType should be required
so just use webhook to check for SpiderCoordinator, but not CRD 
(2) all other fieds in CoordinatorSpec is dangerous
in spidermultusconfig CRD , if leave some fields to be empty, and they will be to default value and ignore the SpiderCoordinator, which make SpiderCoordinator to be meaningless
so just use webhook to set default value for SpiderCoordinator, but not CRD 
(3) coordinator cooperator with ifacer when overlay mode
miss arp for node IP from vxlan interface
> fix: spidermultusconfig 

- docs/usage/install/cloud/get-started-alibaba-zh_CN.md
Both sets of applications in this article use the busybus mirror, but need to use the curl command to access the clusterIP. busybus does not have this command. In addition, when the application is accessed through a public network load balancer, it is expected that the page can display content. It is more convenient to use nginx.
The application test-app-1 uses the busybox image for ping.
The application test-app-2 uses the nginx mirror for curl.
update busybox to nginx
> docs fix: update busybox to nginx

- test/e2e/annotation/annotation_test.go
- test/e2e/common/spiderpool.go
- test/e2e/common/spidersubnet.go
1. We use ginkgo. When using timestamp as a random variable, because it runs multiple it (4 in ci) concurrently, there is a very small probability that the same name will appear, resulting in the creation failure.
2. Improve ipv6 address abbreviation using api
#2034 
#1820 
> e2e fix: use api to abbreviate ipv6 addresses and fix subnet creation  failure due to duplicate names

- test/doc/annotation.md
- test/doc/ippoolcr.md
- test/doc/metric.md
- test/doc/spidermultus.md
Supplement e2e case
```
None
```
> e2e docs: add new e2e case for spiderpool

- test/doc/spidermultus.md
- test/e2e/spidermultus/spidermultus_test.go
e2e: add use case for changing multus properties via spidermultus annotation
```
None
```
> e2e: add use case for changing multus properties via spidermultus annotation

- pkg/multuscniconfig/multusconfig_informer.go
- pkg/multuscniconfig/multusconfig_validate.go
- test/doc/spidermultus.md
---
---
---
spidermultusconfig: validate customcniconfig if is valid
https://github.com/spidernet-io/spiderpool/issues/2151
> spidermultusconfig: validate customcniconfig if is valid

- README-zh_CN.md
- README.md
- docs/README-zh_CN.md
- docs/README.md
add blog [Spiderpool v0.6.0：公有云场景下统一的云原生 Underlay 网络方案](https://mp.weixin.qq.com/s/A22i4U1MAq_91a3MKZdnag) for spiderpool
```
None
```
> add new blog for spiderpool

- pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/types_string.go
> fix potential panic with CRD string method

- test/Makefile
There are some problems with the script
1. The cleanCRD.sh script runs in kind and needs to specify kubeconfig
2. exit 0 exited early.
3. Process optimization
```
export KUBECONFIG=$(E2E_KUBECONFIG)
```
> fix ci cleanup script

- pkg/applicationcontroller/applicationinformers/utils.go
Refer to DNS (RFC 1123), the subdomain's max length is 253. But we made mistake and regard it as length 63.
Actually the `finalizer name`, `annotation key` and `label key` max length is 63
> optimize the autopool name length to 253

- docs/mkdocs.yml
- docs/reference/crd-spidermultusconfig.md
- docs/usage/spider-multus-config.md
- pkg/multuscniconfig/multusconfig_informer.go
- pkg/multuscniconfig/multusconfig_validate.go
- pkg/multuscniconfig/multusconfig_webhook.go
- test/e2e/spidermultus/spidermultus_test.go
1. add customized net-attach-def name with empty string or over max length string validation in webhook
2. add customized CNI version validation in webhook
3. now it's invalid to change the Multus net-attach-def name. 
- change the SpiderMultusConfig annotation to customize net-attach-def name is invalid
- update a SpiderMultusConfig resource to add annotation to customize net-attach-def name is invalid
enhancement
close #2169
> add SpiderMultusConfig annotation validation in webhook

- test/doc/spidermultus.md
- test/e2e/spidermultus/spidermultus_test.go
Add spidermultus e2e for spiderpool, the use case involves some unusual scenarios.
```
None
```
> add spidermultus e2e for spiderpool

- pkg/ipam/pool_selections.go
In dual stack environment, support only ipv4 or ipv6 address in SpiderSubnet feature
> single IP support in dual stack with SpiderSubnet feature

- .github/workflows/e2e-init.yaml
- .github/workflows/lint-license.yaml
- Makefile
- docs/develop/contributing.md
- docs/usage/install/underlay/get-started-kind-zh_CN.md
- docs/usage/install/underlay/get-started-kind.md
- pkg/ippoolmanager/ippool_subnet_validate.go
- pkg/ippoolmanager/ippool_validate.go
- pkg/ippoolmanager/ippool_webhook_test.go
- pkg/subnetmanager/subnet_informer.go
- pkg/subnetmanager/subnet_informer_test.go
- pkg/subnetmanager/subnet_validate.go
- pkg/subnetmanager/subnet_webhook_test.go
- test/Makefile.defs
- test/doc/subnet.md
- test/e2e/affinity/affinity_test.go
- test/e2e/annotation/annotation_test.go
- test/e2e/ippoolcr/ippoolcr_test.go
In the past version, it's invalid to create a orphan IPPool in SpiderSubnet feature, which means you have to create a SpiderSubnet resource firstly.
Now, I make it compatible to create orphan SpiderIPPool resource with SpiderSubnet feature
> feature : SpiderSubnet could take over orphan IPPool

- pkg/multuscniconfig/multusconfig_informer.go
The Annotations property may be a nil map, and I ignored to initial it.
fix bug
close #2224
> fix SpiderMultusConfig potential panic

- test/doc/spidermultus.md
- test/e2e/spidermultus/spidermultus_test.go
add spidermultusconfig e2e for spiderpool
1. Create ipvlan, sriov type Spidermultus
2.invalid json format
```
None
```
> e2e: add spidermultusconfig e2e for spiderpool

- charts/spiderpool/README.md
- charts/spiderpool/templates/multus-daemonset.yaml
- charts/spiderpool/values.yaml
After stop or uninstall multus, there are some CNI configuration legacies in your host machine. I use the kubernetes preStop to clean up them.
enhancement
#2182
> add multus pre-stop to remove multus CNI configuration

- charts/spiderpool/README.md
- charts/spiderpool/templates/_helpers.tpl
- charts/spiderpool/templates/grafanaDashboard.yaml
- charts/spiderpool/templates/prometheusrule.yaml
- charts/spiderpool/templates/servicemonitor.yaml
- charts/spiderpool/values.yaml
1. remove grafanaDashboard irrevevant labels
2. add default hijackCIDR "169.254.0.0/16". (The local listen IP address for NodeLocal DNSCache can be any address that can be guaranteed to not collide with any existing IP in your cluster. It's recommended to use an address with a local scope, for example, from the 'link-local' range '169.254.0.0/16' for IPv4 or from the 'Unique Local Address' range in IPv6 'fd00::/8'.)
reference:
close https://github.com/spidernet-io/spiderpool/issues/2300
> charts default value adjustment

- charts/spiderpool/crds/spiderpool.spidernet.io_spidermultusconfigs.yaml
- docs/reference/crd-spidermultusconfig.md
- pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/spidermultus_types.go
- pkg/multuscniconfig/multusconfig_informer.go
- pkg/multuscniconfig/utils.go
- test/doc/spidermultus.md
You can set spidermultusconfig.spec.disableIPAM to true, and multus NAD does not include the IPAM configuration.
---
---
---
In some special cases, CNI does not require ipam, Now you can set spidermultusconfig.spec.disableIPAM to true, and multus NAD does not include the IPAM configuration.
https://github.com/spidernet-io/spiderpool/issues/2133
> spidermultusconfig: IPAM can be disabled

- pkg/multuscniconfig/multusconfig_informer.go
- pkg/multuscniconfig/utils.go
IPAM field need to be a pointer, Or it can't be ignored while json unmarshal
---
---
---
IPAM field need to be a pointer, Or it can't be ignored while json unmarshal
> spidermultusconfig: make IPAM field to pointer

- go.mod
- go.sum
- pkg/networking/networking/route.go
- vendor/github.com/vishvananda/netlink/chain.go
- vendor/github.com/vishvananda/netlink/chain_linux.go
- vendor/github.com/vishvananda/netlink/conntrack_linux.go
- vendor/github.com/vishvananda/netlink/filter.go
- vendor/github.com/vishvananda/netlink/filter_linux.go
- vendor/github.com/vishvananda/netlink/handle_unspecified.go
- vendor/github.com/vishvananda/netlink/ipset_linux.go
- vendor/github.com/vishvananda/netlink/link.go
- vendor/github.com/vishvananda/netlink/link_linux.go
- vendor/github.com/vishvananda/netlink/neigh_linux.go
- vendor/github.com/vishvananda/netlink/netlink_unspecified.go
- vendor/github.com/vishvananda/netlink/nl/conntrack_linux.go
- vendor/github.com/vishvananda/netlink/nl/ipset_linux.go
- vendor/github.com/vishvananda/netlink/nl/nl_linux.go
- vendor/github.com/vishvananda/netlink/nl/route_linux.go
- vendor/github.com/vishvananda/netlink/nl/tc_linux.go
- vendor/github.com/vishvananda/netlink/nl/xfrm_linux.go
- vendor/github.com/vishvananda/netlink/nl/xfrm_state_linux.go
- vendor/github.com/vishvananda/netlink/qdisc.go
- vendor/github.com/vishvananda/netlink/qdisc_linux.go
- vendor/github.com/vishvananda/netlink/route_linux.go
- vendor/github.com/vishvananda/netlink/rule.go
- vendor/github.com/vishvananda/netlink/rule_linux.go
- vendor/github.com/vishvananda/netlink/xfrm_policy_linux.go
- vendor/github.com/vishvananda/netlink/xfrm_state.go
- vendor/github.com/vishvananda/netlink/xfrm_state_linux.go
- vendor/modules.txt
In latest netlink, For netlink.RouteList function, we can't check the route.dst == nil to determine if it is the default route or not. Now if it is the default route, its route.Dst is no longer nil, but an empty address.
---
---
---
Due to https://github.com/spidernet-io/spiderpool/actions/runs/6167611725/job/16738949668?pr=2326, After we import the cilium public library, the version of netlink needs to be upgraded.
https://github.com/vishvananda/netlink/commit/acdc658b8613655d …
> coordinator: bump netlink version

- test/doc/ifacer.md
- test/e2e/common/spidersubnet.go
- test/e2e/ifacer/ifacer_suite_test.go
- test/e2e/ifacer/ifacer_test.go
New case:
1. Supplemented that ifacer can be created normally
2. The sub-interface exists, skip creation
3. When the sub-interface with the same name is down, it is automatically set to true.
4. After the sub-interface is deleted, restart the Pod and it will automatically recover.
other:
1. Wrong suite naming
2. Wrong logical judgment.
> e2e: add ifacer e2e for spiderpool

- pkg/applicationcontroller/app_controller.go
- pkg/applicationcontroller/app_controller_test.go
- pkg/applicationcontroller/applicationcontroller_suite_test.go
- pkg/podmanager/pod_manager.go
- pkg/podmanager/pod_manager_test.go
In the SpiderSubnet feature, I noticed a situation that spiderpool can't handle with it well.
The RedisCluster -> StatefulSet -> Pod. If we set SpiderSubnet auto pool annotations for it, the pod would not up successfully. With what #2349  describes.
All in all, the `GetTopController` method need to be improved. So I commit a PR #2347 
But I noticed that in the RedisCluster situation, the pod will lose the StatefulSet static IP feature. So I abandon that PR.
Finally, I made a decision. If a third-party controller controls the pod directly, I'll regard the third-party controller is the top controller no matter any other controllers controls the third-party controller.
And If some third-party controller controls the native kubernetes controller like StatefulSet (RedisCluster situation), I'll …
> improve GetTopController method

- .github/workflows/e2e-init.yaml
The github action fails with
```text
debugEnv.sh : E2E_KUBECONFIG /home/runner/work/spiderpool/spiderpool/test/.cluster/spiderpool1009142437/.kube/config 
output debug information to /home/runner/work/spiderpool/spiderpool/test/e2edebugLog.txt
Failed to compile affinity:
compile: writing output: write $WORK/b907/_pkg_.a: no space left on device
k8s.io/client-go/listers/events/v1: mkdir /tmp/go-build580983046/b917/: no space left on device
k8s.io/client-go/listers/events/v1beta1: mkdir /tmp/go-build580983046/b919/: no space left on device
k8s.io/client-go/listers/extensions/v1beta1: mkdir /tmp/go-build580983046/b922/: no space left on device
k8s.io/client-go/listers/flowcontrol/v1alpha1: mkdir /tmp/go-build580983046/b925/: no space left on device …
```
> optimize github action no disk space left

- .github/workflows/auto-diff-k8s-ci.yaml
add kubernetes 1.28 version support to e2e
```
NONE
```
> add kubernetes 1.28 version support to e2e

- .github/workflows/auto-version-release.yaml
- .github/workflows/call-release-chart.yaml
There will be a release-chart operation in ci, but we don't want ci to update the chart every time. The field `submit` is required for control.
> Fix ci calling release-chart error

- test/doc/ippoolcr.md
- test/e2e/ippoolcr/ippoolcr_test.go
Add e2e regarding ippool.spec.multusName affinity.
```
NONE
```
> Add e2e regarding ippool.spec.multusName affinity.

- cmd/coordinator/cmd/utils.go
- test/Makefile
- test/doc/coordinator.md
- test/e2e/common/constant.go
- test/e2e/coordinator/macvlan-overlay-one/macvlan_overlay_one_test.go
- Add and improve the e2e use case of the NIC where the default route is located. Assist in verifying the repair status of the PR #2411 
The changes are as follows:
1. Add a new case. Without setting any annotations or PodDefaultRouteNIC (default situation), the default route should be on net1.
2. Change the existing use case, specify PodDefaultRouteNIC as eth0, and check that the default route should be on eth0
```
NONE
```
> Add and improve the e2e use case of the NIC where the default route is located

- test/doc/ippoolcr.md
- test/e2e/ippoolcr/ippoolcr_test.go
e2e: add nodeName affinity e2e for spiderpool
```
NONE
```
> e2e: add nodeName affinity e2e for spiderpool

- .github/workflows/build-image-plugins.yaml
- images/plugins/.dockerignore
- images/plugins/Dockerfile
- images/plugins/entrypoint.sh
We put all plugins of ovs, cni bin and rdma into the image of ghcr.io/spidernet.io/plugins.
---
---
---
We put all plugins of ovs, cni bin and rdma into the image of ghcr.io/spidernet.io/plugins.
> docker-image: build new image for all plugins 

- cmd/spiderpool-agent/cmd/crd_manager.go
- cmd/spiderpool-controller/cmd/crd_manager.go
- go.mod
controller-runtime framework add stack print for no logger initialization: https://github.com/kubernetes-sigs/controller-runtime/pull/2357
```golang
if logFullfilled.CompareAndSwap(false, true) {
stack := debug.Stack()
stackLines := bytes.Count(stack, []byte{'\n'})
sep := []byte{'\n', '\t', '>', ' ', ' '}
fmt.Fprintf(os.Stderr,
"[controller-runtime] log.SetLogger(...) was never called; logs will not be displayed.\nDetected at:%s%s", sep,
// prefix every line, so it's clear this is a stack trace related to the above message
bytes.Replace(stack, []byte{'\n'}, sep, stackLines-1),
)
SetLogger(logr.New(NullLogSink{}))
}
}
```
And the controller-runtime would set null logger for its usage. So, I just pre-do it in spiderpool to avoid debug stack print.
Signed-off-by: Icarus9913 …
> set logger for controller-runtime framework

- pkg/ippoolmanager/ippool_manager.go
- pkg/ippoolmanager/ippool_manager_test.go
- pkg/ippoolmanager/utils.go
- pkg/ippoolmanager/utils_test.go
As issue #2517 described, we need try to circulate traversal the whole IPPool allocated IPs to find the previous allocated IP address once the whole IPPool IP addresses used out.
It might reduce performance, but this is the simplest and cause less impaction to solve this problem.
And we only do this when we meet IP addresses used out case. In other case, the spiderpool-agent component still find new free IP address to allocate for the pod and the spiderpool-controller component will use GC scanAll to release the previous IP addresses.
fix bug
close #2517
> fix ipam block with ip address used out

- pkg/gcmanager/scanAll_IPPool.go
- pkg/ipam/allocate.go
- pkg/ippoolmanager/ippool_manager.go
- pkg/ippoolmanager/ippool_manager_test.go
As #2526 described, we met this situation because of wrong IP GC scanAll for StatefulSet pod. 
So, we just ignore to release the IP once the GC scanAll meet StatefulSet pod restarts
- release/bug 
fix bug
close #2526
> fix: statefulset duplicate IP issue 

- pkg/gcmanager/scanAll_IPPool.go
- pkg/ipam/allocate.go
- pkg/ippoolmanager/ippool_manager.go
- pkg/ippoolmanager/ippool_manager_test.go
As https://github.com/spidernet-io/spiderpool/issues/2526 described, we met this situation because of wrong IP GC scanAll for StatefulSet pod. But in the main branch I already fixed it with kubevirt static IP support. 
So, this pr is an enhancement for logs and add verification for IPPool IP update.
enhancement
> optimize codes to verify IP update

- cmd/spiderpool-agent/cmd/config.go
- cmd/spiderpool-agent/cmd/daemon.go
- pkg/ipam/config.go
- test/e2e/common/spiderpool.go
- test/e2e/common/spidersubnet.go
- test/e2e/subnet/subnet_test.go
> cleanup: remove configmap obsolete fields

- charts/spiderpool/templates/daemonset.yaml
- cmd/spiderpool-agent/cmd/config.go
- cmd/spiderpool-agent/cmd/daemon.go
- pkg/ipam/allocate.go
- pkg/ipam/config.go
- pkg/ippoolmanager/ippool_manager.go
- pkg/ippoolmanager/ippool_manager_test.go
- pkg/ippoolmanager/utils.go
- pkg/ippoolmanager/utils_test.go
- test/e2e/common/spiderpool.go
- test/e2e/common/spidersubnet.go
- test/e2e/subnet/subnet_test.go
⚠️⚠️⚠️ If you update release v0.7 to v0.7.1, please update the spiderpool-agent yaml rather than just update the image directly! 
Because I added the additional ENV parameters for spiderpool-agent:
```text
- name: SPIDERPOOL_POD_NAME
valueFrom:
fieldRef:
fieldPath: metadata.name
- name: SPIDERPOOL_POD_NAMESPACE
valueFrom:
fieldRef:
fieldPath: metadata.namespace
``` 
cherry-pick
close https://github.com/spidernet-io/spiderpool/issues/2547
close https://github.com/spidernet-io/spiderpool/issues/2521
> cherrypick 2518, 2514 and 2544 to release v0.7

- cmd/coordinator/cmd/utils.go
- docs/concepts/coordinator-zh_CN.md
- docs/concepts/coordinator.md
- docs/usage/underlay_cni_service-zh_CN.md
- docs/usage/underlay_cni_service.md
- pkg/networking/networking/route.go
- test/e2e/coordinator/macvlan-overlay-one/macvlan_overlay_one_test.go
In multi-NIC mode, all routes for each NIC, including both the routes for the cluster and service subnet are retained in both the main table and a new policy routing table, except for the default route. The default route for each NIC can only exist in a unique policy routing table.
- In multi-NIC mode, The KubeVirt project aims to include the routes for each network interface in the main table. all routes for each NIC, including both the routes for the cluster and service subnet are retained in both the main table and a new policy routing table, except for the default route. The default route for each NIC can only exist in a unique policy routing table. 
- By default, the first network interface with the default route is selected …
> coordinator: improve tuning polocy of routes to support kubevirt

- charts/spiderpool/templates/daemonset.yaml
The previous spiderpool-agent container volumeMounts cni-bin-path is `host//opt/cni/bin`.
It works well but displays ugly
> fix path typo in spiderpool-agent yaml

- cmd/coordinator/cmd/command_add.go
- cmd/spiderpool-init/cmd/root.go
- release/bug
- kind/bug
init-pod: don't init multus CR if multus is disable
Fixes #
> init-pod: don't init multus CR if multus is disable

- test/e2e/common/spiderpool.go
- test/e2e/common/spidersubnet.go
- release/bug 
e2e-fix: Avoid random subnets from overlapping with the subnets of clusters calico and cilium
Fixes #2615 
> e2e-fix: Avoid random subnets from overlapping with the subnets of clusters calico and cilium

- test/Makefile.defs
- test/scripts/install-default-cni.sh
- release/bug 
e2e-fix: specify the calico version manually when failed to retrieve it specify the calico version manually when failed to retrieve it
close #2718
> e2e-fix: Use the default calico version when getting the calico version fails

- cmd/spiderpool/cmd/command_add.go
- pkg/ipam/pool_selections.go
- pkg/ipam/utils.go
- test/doc/annotation.md
- test/e2e/annotation/annotation_test.go
1. Once multiple NICs use spiderpool as IPAM, if you use annotaion `ipam.spidernet.io/ippools`, you have to specify the same correct IPPool slice for multiple NICs. Add strong validation in this PR.
For instance, if you have 2 NICs and use `ipam.spidernet.io/ippools` to specify the IPPools, you need to specify each NIC corresponding IPPools
```text
// Bad
ipam.spidernet.io/ippools: '[{"interface": "net1","ipv4": ["ens6-v4"],"ipv6":["ens6-v6"]}]'
---
// Good
ipam.spidernet.io/ippools: '[{"interface": "eth0","ipv4": ["ens5-v4"],"ipv6":["ens5-v6"]},{"interface": "net1","ipv4": ["ens6-v4"],"ipv6":["ens6-v6"]}]'
```
2. Add validation for same NICs name in `ipam.spidernet.io/ippools`. 
```text
// Bad
ipam.spidernet.io/ippools: '[{"interface": "eth0","ipv4": …
```
> add validation for IPAM IPPools annotation usage

- test/doc/coordinator.md
- test/e2e/coordinator/macvlan-overlay-one/macvlan_overlay_one_test.go
- test/e2e/coordinator/macvlan-underlay-one/macvlan_underlay_one_test.go
> e2e: Optimize and add e2e use cases for 'ip rule'

- pkg/coordinatormanager/coordinator_informer.go
If obtaining the CIDR information of the cluster fails, we should update its status to NotReady. This prevents the normal creation of pods. Otherwise, the pod will use the incorrect CIDR. Causing communication issues.
Fixes https://github.com/spidernet-io/spiderpool/issues/2928
> spidercoordinator: It should update the status to NotReady if any errors occur

- .github/workflows/auto-version-release.yaml
- .github/workflows/build-image-base.yaml
- .github/workflows/build-image-ci.yaml
- .github/workflows/build-image-plugins.yaml
- .github/workflows/call-clean-ghcr.yaml
- .github/workflows/call-lint-chart.yaml
- .github/workflows/call-release-chart.yaml
- .github/workflows/call-release-image.yaml
- .github/workflows/call-update-githubpages.yaml
- .github/workflows/ci-image-gc-by-pr.yaml
- .github/workflows/lint-golang.yaml
- .github/workflows/lint-license.yaml
- .github/workflows/lint-spell.yaml
Fixes #https://github.com/spidernet-io/spiderpool/issues/877
> CI workflow: Updated obsolete method set-output.

- cmd/spiderpool-agent/cmd/daemon.go
- cmd/spiderpool-controller/cmd/daemon.go
Once we disable kubevirt static IP feature, the spiderpool-agent pod can not start successfully.
fix bug
close #2966
> fix:  spiderpool-agent crashes when kubevirt static IP feature is off 

- test/doc/spidercoodinator.md
- test/e2e/common/constant.go
- test/e2e/common/mode.go
- test/e2e/coordinator/macvlan-overlay-one/macvlan_overlay_one_test.go
- test/e2e/spidercoordinator/spidercoordinator_suite_test.go
- test/e2e/spidercoordinator/spidercoordinator_test.go
- test/scripts/install-default-cni.sh
> e2e: Add spidercoodinator e2e for spiderpool

- charts/spiderpool/templates/daemonset.yaml
- kind/bug
chart: make Values.multus.multusCNI.uninstall to sense
Fixes https://github.com/spidernet-io/spiderpool/issues/2972
> fix chart: Values.multus.multusCNI.uninstall does not take effect

- api/v1/agent/models/coordinator_config.go
- api/v1/agent/openapi.yaml
- api/v1/agent/server/embedded_spec.go
- charts/spiderpool/crds/spiderpool.spidernet.io_spidercoordinators.yaml
- charts/spiderpool/crds/spiderpool.spidernet.io_spidermultusconfigs.yaml
- cmd/coordinator/cmd/cni_types.go
- cmd/coordinator/cmd/command_add.go
- cmd/spiderpool-agent/cmd/coordinator.go
- docs/concepts/coordinator-zh_CN.md
- docs/concepts/coordinator.md
- docs/reference/crd-spidercoordinator.md
- pkg/coordinatormanager/coordinator_mutate.go
- pkg/coordinatormanager/coordinator_validate.go
- pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/spidercoordinator_types.go
- pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/zz_generated.deepcopy.go
- pkg/multuscniconfig/multusconfig_mutate.go
- pkg/networking/networking/ip.go
We can configure the txqueuelen of pod's interface by configuring txQueueLen filed. the default value is 0, this means that it is not configured, and its value should be a non-0 integer.
- kind/feature
coordinator: Add a new filed "numQueusNum"
Fixes https://github.com/spidernet-io/spiderpool/issues/2062
> coordinator: Add a new filed "txQueueLen"

- README-zh_CN.md
- README.md
- docs/README-zh_CN.md
- docs/README.md
The docs is built with MkDocs with an indentation of 4 spaces by default for bullets.
Indent from 2 spaces to 4 spaces in the `/docs` folder.
> Minor changes about bullets indentations and punctuations in docs/readme

- pkg/ippoolmanager/ippool_mutate.go
- pkg/subnetmanager/subnet_informer.go
- test/e2e/ippoolcr/ippoolcr_test.go
In the past versions, if you create a SpiderSubnet resource first and create a corresponding subnet SpiderIPPool resource later, the SpiderIPPool would inherit the SpiderSubnet `gateway, routes`. But if you create an orphan SpiderIPPool first, then the SpiderIPPool resources wouldn't inherit the SpiderSubnet properites.
And in this PR, I supplement a e2e case which validate 2 situations:
1. create SpiderSubnet first, and create the corresponding SpiderIPPool later.
2. create SpiderIPPool first, and create the corresponding SpiderSubnet later. 
fix bug
close #3009
> fix inherit subnet properties for ippool failure 

- docs/usage/spider-subnet-zh_CN.md
- docs/usage/spider-subnet.md
- pkg/ipam/pool_selections.go
- test/doc/subnet.md
- test/e2e/subnet/subnet_test.go
The SpiderSubnet feature doesn't support orphan pod(pod without any controller), So once the user use it wrongly, we should return the exact error information
fix bug
close #2951
> single POD without controller is forbidden to use  SpiderSubnet feature

- pkg/ipam/pool_selections.go
> [cherrypick]single POD without controller is forbidden to use SpiderSubnet feature

- test/doc/metric.md
- test/doc/reliability.md
- test/e2e/common/constant.go
- test/e2e/reliability/reliability_suite_test.go
- test/e2e/reliability/reliability_test.go
> Add e2e for active-standby switching of spidercontroller

- test/doc/ippoolcr.md
- test/e2e/ippoolcr/ippoolcr_test.go
> Add e2e about nodeName,namespaceName priority

- .github/workflows/auto-cherrypick.yaml
- .github/workflows/call-release-chart.yaml
- .github/workflows/call-release-doc.yaml
- .github/workflows/call-update-githubpages.yaml
> [release-v0.7]cherry-pick PRs submitted by robots can be verified.

- test/Makefile
robot cherry pick PR <https://github.com/spidernet-io/spiderpool/pull/3066> from ty-dc,to branch release-v0.8,  action <https://github.com/spidernet-io/spiderpool/actions/runs/7487328147>  , commits 38266fd9ab7df1cae5673a0b346d816facef5ff3
> e2e fix: The kind image name is wrong.

- cmd/ifacer/cmd/cmd_add.go
robot cherry pick PR <https://github.com/spidernet-io/spiderpool/pull/3088> from ty-dc,to branch release-v0.8,  action <https://github.com/spidernet-io/spiderpool/actions/runs/7523903858>  , commits d990b825a0df1ef9617239009b817701fbf64929
> fix: the parent interface is down, set it to up before creating the vlan sub-interface

- test/e2e/ippoolcr/ippoolcr_test.go
The spiderpool-controller component ENV `SPIDERPOOL_IPPOOL_INFORMER_RESYNC_PERIOD` and `SPIDERPOOL_SUBNET_INFORMER_RESYNC_PERIOD` all default to 300s. And this e2e case will create the SpiderIPPool, SpiderSubnet resource concurrently, this e2e case timeout duration is 5 minutes and do not hit the Subnet informer resync operation.
e2e case improvement
https://github.com/spidernet-io/spiderpool/issues/3114
> fix ippool inherits subnet attributes e2e case

- cmd/spiderpool-init/cmd/client.go
In the spiderpool-init `WaitPodListReady` method, it'll continue without any time sleep and hit lots of api if met an error or other situations. 
So I added time sleep in some judgement conditions.
> optimize spiderpool-init restart spiderpool-agent codes

- docs/usage/install/overlay/get-started-calico-zh_cn.md
- docs/usage/install/overlay/get-started-calico.md
- docs/usage/install/overlay/get-started-cilium-zh_cn.md
- docs/usage/install/overlay/get-started-cilium.md
- pkg/coordinatormanager/coordinator_informer.go
- test/doc/spidercoodinator.md
- test/e2e/spidercoordinator/spidercoordinator_test.go
If the kube-controller-manager Pod is running as systemd process rather than Pod, In this case, We can't get the CIDR from the KCM Pod. We can get the CIDR from the kubeadm-config configMap.
- release/bug 
Kube-controller-pod is running as systemd process rather than a pod, We can't get the cluster CIDR in this case.
1. We get the clusterCIDR from kubeadm-config ConfigMap first.
2. If kubeadm-config ConfigMap does exist in cluster, we can get it from kube-controller-manager.
Fixes https://github.com/spidernet-io/spiderpool/issues/3054
> Spidercoordinator: It able to get CIDR from kubeadm-config

- .github/workflows/e2e-init.yaml
CI: make k8s 1.29 to default, we need to test the serviceCIDR resource.
Fixes #
> CI: make k8s 1.29 to default

- pkg/coordinatormanager/coordinator_informer.go
- test/Makefile
- test/scripts/install-default-cni.sh
- test/yamls/global-kind.yaml
> enable coordinate to support serviceCIDR according to a matched k8s version.

- cmd/spiderpool-controller/cmd/daemon.go
- pkg/constant/k8s.go
- pkg/coordinatormanager/coordinator_informer.go
- pkg/coordinatormanager/service_cidr_informer.go
Before fetch the kubernetes `ServiceCIDR` resource, we need to check whether the current kubernetes registered the `networking v1alpha1 ServiceCIDR` API resources.
> add kubernetes serviceCIDR APIResource register validation

- charts/spiderpool/templates/deployment.yaml
- charts/spiderpool/templates/tls.yaml
- cmd/spiderpool-controller/cmd/config.go
- cmd/spiderpool-controller/cmd/daemon.go
Do not register the coordinator `webhook` and do not set up coordinator `informer` when using the helm charts to install spiderpool with `--coordinator.enbaled=false`
fix bug
close #3181
> use helm charts value control coordinator components startup

- pkg/coordinatormanager/coordinator_informer.go
- test/scripts/install-default-cni.sh
Fixes #3180 
Fixes #3210 
**Additional information**
1. In the original logic, the judgment of kubeadm-config was incorrect.
2. When kubeadm-config does not exist, obtain podCIDR and serviceCIDR from kube-controller-manager Pod. Due to different ways of deploying the cluster, there may be two types: Spec.Containers[0].Command and Spec.Containers[0].Args. Scenarios, such as the RKE2 cluster is Spec.Containers[0].Args and not Spec.Containers[0].Command, resulting in a judgment error and an empty serviceCIDR returned, resulting in the inability to create a Pod.
> fix the logic of obtaining kubeadm-config to avoid being unable to create Pods

- cmd/spiderpool-agent/cmd/daemon.go
- cmd/spiderpool-controller/cmd/daemon.go
- test/Makefile.defs
1. supplement pyroscope profile types in go code
2. change pyroscope image from `pyroscope/pyroscope` to `grafana/pyroscope`
> supplement pyroscope profile types

- cmd/spiderpool-controller/cmd/crd_manager.go
- cmd/spiderpool-controller/cmd/daemon.go
- cmd/spiderpool-controller/cmd/runtime_status.go
- pkg/constant/k8s.go
- pkg/openapi/webhook_checker.go
- test/e2e/reclaim/reclaim_test.go
There's a e2e case that we will restart kubelet, we need to keep the whole cluster back to ready after restart.
So, in this case we use the ginkgo `Defercleanup` to make sure the node ready, and the node's spiderpool-controller webhook server ready.
> optimize e2e kubelet restart case

- test/scripts/install-default-cni.sh
Failed to install cilium in the kind.
Reference: https://github.com/spidernet-io/spiderpool/pull/3168#issuecomment-1925300944
> fix e2e cilium installation failure with IPv6

- pkg/coordinatormanager/coordinator_informer.go
In issue #3180, users encountered an issue where getting the serverCIDR failed in the rke2 cluster. The version they are using is v0.9.1, which has been fixed in PR #3211. But since new features are added to the main branch, the problem still needs to be fixed in main based on the new features.
The problem is as follows:
When kubeadm-config does not exist, get the podCIDR and serviceCIDR from the kube-controller-manager Pod. Due to different cluster deployment methods, there may be two types: Spec.Containers[0].Command and Spec.Containers[0].Args. For example, if the RKE2 cluster uses Spec.Containers[0].Args instead of Spec.Containers[0].Command, serviceCIDR will not be obtained, resulting in the inability to create …
> Support getting serviceCIDR from spec.Containers[0].Args of kube-controller-manager Pod

- pkg/coordinatormanager/coordinator_informer.go
Fix panic in spidercoordinator informer: if the serviceCIDR resource can't be list, the serviceCIDRLister should be nil, in the case, we update the service cidr of the spidercoordinator.status from k8s service cidr.
Fixes https://github.com/spidernet-io/spiderpool/issues/3263
> Fix panic in spidercoordinator informer

- pkg/coordinatormanager/coordinator_informer.go
- release/bug 
Consider a successful fetch of the kube-controller-manager podList, but maybe the podList is empty, which may result in a panic.
Fixes https://github.com/spidernet-io/spiderpool/issues/3285
> spidercoordinator: Enhance the edge case

- pkg/multuscniconfig/multusconfig_informer.go
- pkg/multuscniconfig/utils.go
- kind/bug
Fixes https://github.com/spidernet-io/spiderpool/issues/3282
> spidermultusconfig: add missing filed for generateCoordinatorCNIConf

- go.mod
- pkg/coordinatormanager/coordinator_informer.go
- release/bug 
we should watch the kubeadm-config configMap
Fixes https://github.com/spidernet-io/spiderpool/issues/3290
Fixes https://github.com/spidernet-io/spiderpool/issues/3292
> Spidercoordinator: sync kubeadm-config event to trigger the status update

- pkg/networking/networking/route.go
Fixes #3296
In IPv6 mode, a non-existent network card is set through PodDefaultRouteNIC, but the Pod has an IPv6 default route, but a null value is returned, thus skipping the synchronization of the default route and making the Pod successfully created. However, the creation should fail at this time and prompt "net2 don't exist in pod"
> coordinator: rework GetDefaultRouteInterface to get pod's default route nic

- pkg/ippoolmanager/ippool_validate.go
- pkg/ippoolmanager/ippool_webhook.go
- pkg/ippoolmanager/ippool_webhook_test.go
- pkg/subnetmanager/subnet_validate.go
- pkg/subnetmanager/subnet_webhook.go
- pkg/subnetmanager/subnet_webhook_test.go
Refer to #3321 , the user get an `InternalError` type error after send a create IPPool/Subnet resource API request, which leads to wrong type assertion.
The reason why we keep returning the `AlreadyExist` by ourself is that considering the lots of taxing operations in the IPPool/Subnet Webhook. So, if we meet resource already first we just return it and ignore the other operations.
fix bug
close #3321
> supplement right AlreadyExist error return for IPPool/Subnet webhook

- charts/spiderpool/README.md
- charts/spiderpool/templates/configmap.yaml
- charts/spiderpool/templates/pod.yaml
- charts/spiderpool/values.yaml
- cmd/spiderpool-agent/cmd/config.go
- cmd/spiderpool-agent/cmd/daemon.go
- cmd/spiderpool-controller/cmd/config.go
- cmd/spiderpool-controller/cmd/daemon.go
- docs/usage/install/upgrade-zh_CN.md
- docs/usage/install/upgrade.md
- docs/usage/spider-subnet-zh_CN.md
- docs/usage/spider-subnet.md
- pkg/applicationcontroller/applicationinformers/utils.go
- pkg/applicationcontroller/applicationinformers/utils_test.go
- pkg/ipam/config.go
- pkg/ipam/pool_selections.go
- pkg/ippoolmanager/ippool_informer.go
- pkg/types/k8s.go
- test/Makefile
- test/doc/subnet.md
- test/e2e/subnet/subnet_test.go
1. allow the user to create SpiderSubnet resource based on a switch `EnabledSpiderSubnet`
2. add a switch to control auto-pool application with `ipam.spidernet.io/subnet` and `ipam.spidernet.io/subnets` annotation. (This switch should based on enable `EnabledSpiderSubnet`)
new feature
close #3238
> subnet feature: support to turn on or off the feature of managing automatic-ippool

- cmd/spiderpool-agent/cmd/crd_manager.go
- cmd/spiderpool-controller/cmd/crd_manager.go
- docs/concepts/coordinator.md
- docs/usage/spider-ippool-zh_CN.md
- docs/usage/spider-ippool.md
- docs/usage/spider-subnet-zh_CN.md
- docs/usage/spider-subnet.md
- pkg/constant/k8s.go
- pkg/ipam/pool_selections.go
- pkg/ipam/utils.go
- pkg/ippoolmanager/ippool_manager.go
- pkg/ippoolmanager/ippool_manager_suite_test.go
- pkg/ippoolmanager/ippool_manager_test.go
- pkg/ippoolmanager/utils.go
- pkg/ippoolmanager/utils_test.go
- pkg/reservedipmanager/reservedip_manager.go
- pkg/reservedipmanager/reservedip_manager_suite_test.go
- test/doc/annotation.md
- test/e2e/annotation/annotation_test.go
With the following ways of specifying IPPools(Pod Annotation, Namespace Annotation, CNI configuration file), you can also use wildcards `*`, `?` and `[]` to match the desired IPPools. 
For example: 
`ipam.spidernet.io/ippool: '{"ipv4": ["demo-v4-ippool1", "backup-ipv4*"]}'`
> feature: support wildcard match for IPPool

- cmd/coordinator/cmd/command_add.go
- cmd/coordinator/cmd/utils.go
- release/bug 
Avoiding the GW properly comes from the nodelocaldns's IP when coordinator creates the hijack routes in the pod. 
There are some os where `ip r get` may return src as the address of the node's nodelocaldns, which should be avoided.
Fixes https://github.com/spidernet-io/spiderpool/issues/3359
> coordinator: ensure hijickRoute's gw is from hostIPRouteForPod

- .github/workflows/call-release-image.yaml
```
Generating ephemeral keys...
Retrieving signed certificate...
Error: signing [ghcr.io/spidernet-io/spiderpool/spiderpool-controller@sha256:c3d04a50b918ca8eb8026399febb45b7a3a5e730910b1eeb49b43f534faf0663]: getting signer: getting key from Fulcio: getting CTFE public keys: updating local metadata and targets: error updating to TUF remote mirror: invalid key
remote status:{
"mirror": "https://sigstore-tuf-root.storage.googleapis.com",
"metadata": {
"root.json": {
"version": 9,
"len": 6766,
"expiration": "12 Sep 24 06:53 UTC",
"error": ""
},
"snapshot.json": {
"version": 135,
"len": 2302,
"expiration": "30 Apr 24 16:06 UTC",
"error": ""
},
"targets.json": {
"version": 9,
"len": …
```
> bump cosign-release to v2.2.3

- .github/workflows/auto-upgrade-ci.yaml
- Makefile
- docs/usage/install/upgrade-zh_CN.md
- docs/usage/install/upgrade.md
- test/Makefile
> Add upgrade test for spiderpool

- test/e2e/subnet/subnet_test.go
- test/scripts/debugEnv.sh
> fix: confirm that the SpiderSubnet AutoPool feature is really disabled

- docs/usage/install/underlay/get-started-ovs-zh_CN.md
- docs/usage/install/underlay/get-started-ovs.md
> doc: optimize ovs

- test/doc/spidercoodinator.md
- test/e2e/spidercoordinator/spidercoordinator_test.go
> E2E: testing if neither kubeadm-config nor kube-controller-manager no found

- test/e2e/spidercoordinator/spidercoordinator_test.go
Fixes #3474
kube-controller-manager after changing tags, but not restarting as expected. So it failed.
> e2e fix: the kube-controller-manager Pod runs successfully when the label is kube-controller-manager1.

- .github/workflows/auto-diff-k8s-ci.yaml
- test/scripts/update-kindnode-version.sh
> CI: Add k8s 1.30 version compatibility test

- .github/workflows/auto-update-authors.yaml
- AUTHORS
- Makefile
- tools/scripts/extractAuthors.sh
> ci: Add automatic update of spiderpool authors

- charts/spiderpool/templates/role.yaml
- charts/spiderpool/templates/role_binding.yaml
- release/bug
This PR removes unnecessary RBAC permissions for the DaemonSet agent and Pod init to avoid potential security risks. Technically, this PR does:
1. Create a separate `ClusterRole` for each workload
2. Remove some unnecessary permissions applied by the DaemonSet agent and Pod init
This PR minimizes the deletion of permissions to avoid affecting the normal function of the APP. However, there should still be some unnecessary RBAC permissions (such as for the Deployment controller).
Also, this PR DOES NOT include changing the kubebuilder annotation in: `pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/rbac.go`
Fixes #3420
Fixes #3361
The removed permission from the …
> fix(charts): Remove unnecessary sensitive permissions for DaemonSet agent and Pod init

- charts/spiderpool/templates/role.yaml
- pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/rbac.go
- release/bug 
avoiding too high permissions leading to potential CVE risks, see these issues below
Fixes https://github.com/spidernet-io/spiderpool/issues/3420
Fixes https://github.com/spidernet-io/spiderpool/issues/3361
> RBAC: avoiding too high permissions leading to potential CVE risks

- cmd/coordinator/cmd/utils.go
- release/bug 
The iptables redirect module uses the IP address of the incoming interface as the dst to modify the packet, but if the interface is not configured with an IP address, the packet will be dropped. 
NOTE: this is for istio sidecar
Fixes https://github.com/spidernet-io/spiderpool/issues/3568
> add link-local IP to veth0 for istio

- .github/workflows/auto-upgrade-ci.yaml
- .github/workflows/build-image-ci.yaml
- Makefile
- test/e2e/common/constant.go
> Optimize upgrade CI, and use the self-built image in the release branch

- docs/usage/statefulset-zh_CN.md
- docs/usage/statefulset.md
- pkg/ipam/allocate.go
- pkg/ipam/utils.go
- test/e2e/affinity/affinity_test.go
Fix https://github.com/spidernet-io/spiderpool/issues/3543
> Fix: Statefulset pod should change IP when recreating with a changed pool in annotation

- .github/workflows/auto-upgrade-ci.yaml
- .github/workflows/auto-version-release.yaml
- .github/workflows/build-image-base.yaml
- .github/workflows/build-image-ci.yaml
- .github/workflows/build-image-plugins.yaml
- .github/workflows/call-release-changelog.yaml
- .github/workflows/call-release-chart.yaml
- .github/workflows/call-release-doc.yaml
- .github/workflows/call-update-githubpages.yaml
- .github/workflows/e2e-init.yaml
- .github/workflows/trivy-scan-image.yaml
Fixes #3676
Because pr https://github.com/spidernet-io/spiderpool/pull/3426 updated actions/upload-artifact, but actions/download-artifact lagged behind it by a large version, which caused CI to fail
> fix: CI failed to download the file

- .github/workflows/auto-upgrade-ci.yaml
- .github/workflows/auto-version-release.yaml
- .github/workflows/build-image-base.yaml
- .github/workflows/build-image-ci.yaml
- .github/workflows/build-image-plugins.yaml
- .github/workflows/call-release-changelog.yaml
- .github/workflows/call-release-chart.yaml
- .github/workflows/call-release-doc.yaml
- .github/workflows/call-release-image.yaml
- .github/workflows/call-update-githubpages.yaml
- .github/workflows/e2e-init.yaml
- .github/workflows/lint-golang.yaml
- .github/workflows/lint-yaml.yaml
- .github/workflows/trivy-scan-image.yaml
- .github/workflows/update-chart-readme.yml
Fixes #
The dependency checker robot updated actions/upload-artifact for us, which was great, but it introduced some new issues. We had to roll it back.
```
##[debug]Body: {
##[debug]  "code": "already_exists",
##[debug]  "msg": "an artifact with this name already exists on the workflow run"
##[debug]}
Error: Failed to CreateArtifact: Received non-retryable error: Failed request: (409) Conflict: an artifact with this name already exists on the workflow run
```
refer to: https://github.com/marketplace/actions/upload-a-build-artifact
```
Breaking Changes
On self hosted runners, additional [firewall rules](https://github.com/actions/toolkit/tree/main/packages/artifact#breaking-change …
```
> Revert build(deps): bump actions/download-artifact and actions/upload-artifact from 3 to 4

- docs/usage/install/uninstall-zh_CN.md
- docs/usage/install/uninstall.md
- tools/scripts/cleanCRD.sh
Fixes #3696 
```
➜  spiderpool git:(fix/3696) kubectl delete ns spiderpool-ns              
namespace "spiderpool-ns" deleted
➜  spiderpool git:(fix/3696) kubectl get MutatingWebhookConfiguration -A
NAME                    WEBHOOKS   AGE
spiderpool-controller   5          76s
➜  spiderpool git:(fix/3696) bash ./tools/scripts/cleanCRD.sh
mutatingwebhookconfiguration.admissionregistration.k8s.io "spiderpool-controller" deleted
validatingwebhookconfiguration.admissionregistration.k8s.io "spiderpool-controller" deleted
spiderippool.spiderpool.spidernet.io/ippool-test patched
No resources found
spidercoordinator.spiderpool.spidernet.io/default patched
No resources found …
```
> Optimize clean scripts

- cmd/coordinator/cmd/utils.go
- docs/usage/install/overlay/get-started-calico-zh_cn.md
- docs/usage/install/overlay/get-started-calico.md
- docs/usage/install/overlay/get-started-cilium-zh_cn.md
- docs/usage/install/overlay/get-started-cilium.md
- pkg/networking/networking/route.go
- test/doc/coordinator.md
- test/e2e/coordinator/macvlan-overlay-one/macvlan_overlay_one_test.go
Add a from policy route for pod's eth0, which make sure that packets received from eth0 are forwarded out of eth0. fix to the problem of inconsistent routes.
here is the case: a pod owns multiple cards with eth0(calico 172.16.1.0/24) and eth1( 192.168.1.0/24 macvlan), and a node with an IP 192.168.1.10 visits the the pod's calico ip for the nodePort reason or health check. Finally, the reply packet does not go through eth0 
- release/bug
Fixes #3683 
Pod routing table
```
root@demo1-7fbdd6cc66-bwgtn:/# ip r
default via 169.254.1.1 dev eth0
10.7.0.0/16 dev net1 proto kernel scope link src 10.7.168.202
10.7.168.71 dev eth0 scope link src 10.233.74.111
10.233.0.0/18 via 10.7.168.71 …
```
> fix: fail to access NodePort when pod owning multiple network cards

- test/e2e/reclaim/reclaim_test.go
> e2e fix: spiderpoolcontroller Pod termination failed

- charts/spiderpool/README.md
- charts/spiderpool/values.yaml
- images/spiderpool-plugins/Dockerfile
> fix: Missing GLIBC dynamic dependency makes ovs binary unavailable

- test/e2e/kubevirt/kubevirt_test.go
Fixes #3740 
Kubevirt removed support for passt network core binding in v1.3, refer to https://kubevirt.io/user-guide/release_notes/#deprecation
The reason for removal is: "Network Core Binding has not yet reached GA level",
but the feature has not been abandoned? Temporarily pending e2e, follow up later.
> e2e fix: skip About passt network core binding e2e

- docs/usage/install/overlay/get-started-cilium-zh_cn.md
- docs/usage/install/overlay/get-started-cilium.md
- test/scripts/install-default-cni.sh
Fixes #3760 
cilium released a new version, and the type of bpf.vlanBypass was changed to list.
```
Error: values don't meet the specifications of the schema(s) in the following chart(s):
cilium:
- bpf.vlanBypass: Invalid type. Expected: [null,array], given: integer
```
> Change the type of cilium bpf.vlanBypass to list

- charts/spiderpool/templates/daemonset.yaml
- test/Makefile
- test/e2e/coordinator/macvlan-overlay-one/macvlan_overlay_one_test.go
- release/bug 
the prestop of the agent's container would clean up the multus cni config(00-multus.conf), If the container restart but not pod restarts, the config file wouldn't be re-generated, which can cause the multus doesn't work.
the pr moves the multus-cni from init-container to container, and choose the it as the first containers.
Fixes https://github.com/spidernet-io/spiderpool/issues/3755
1. restart the multus-cni container, the 00-multus.conf would be re-generated.
```
root@spider-worker:/# crictl ps
CONTAINER           IMAGE               CREATED              STATE               NAME                     ATTEMPT             POD ID              POD
a4d9d4af2fe69 …
```
>  pod launched by unexpected CNI when the health checking of the agent fails and multus.conf is lost

- cmd/coordinator/cmd/utils.go
- docs/usage/install/overlay/get-started-calico-zh_cn.md
- docs/usage/install/overlay/get-started-calico.md
- docs/usage/install/overlay/get-started-cilium-zh_cn.md
- docs/usage/install/overlay/get-started-cilium.md
- pkg/networking/networking/route.go
- test/e2e/coordinator/macvlan-overlay-one/macvlan_overlay_one_test.go
Add a from policy route for pod's eth0, which make sure that packets received from eth0 are forwarded out of eth0. fix to the problem of inconsistent routes.
- release/bug 
Fixes https://github.com/spidernet-io/spiderpool/issues/3725
> fix: fail to access NodePort when pod owning multiple network card

- charts/spiderpool/templates/daemonset.yaml
- test/Makefile
Fixes https://github.com/spidernet-io/spiderpool/issues/3807
> pod launched by unexpected CNI when the health checking of the agent fails and multus.conf is lost 

- .github/workflows/e2e-init.yaml
Fixes #3847 
在原本的代码中，清理磁盘空间比较简单，
```
sudo rm -rf "/usr/local/share/boost"
sudo rm -rf "$AGENT_TOOLSDIRECTORY"
echo "=========after clean up, the left CI disk space"
```
并未清理出足够的空间，新的 CI 中，我们借助于 jlumbroso/free-disk-space@main ，帮助深度清理 vm 磁盘，可以留出足够的空间帮助运行 CI。
如下是，清理后，并且运行了部署 kind 集群后的可用空间
> fix: Optimize CI machine disk cleanup method to avoid no space left

- docs/reference/spiderpool-agent.md
robot cherry pick PR <https://github.com/spidernet-io/spiderpool/pull/3855> from cyclinder,to branch release-v0.9,  action <https://github.com/spidernet-io/spiderpool/actions/runs/10313762347>  , commits 942cac8ec75b1ea6b13f72a53bd74bafb5b62284
> docs: fix typo in spiderpool-aget.md

- cmd/coordinator/cmd/command_add.go
- docs/reference/spiderpool-agent.md
- pkg/networking/sysctl/sysctl.go
- test/e2e/reclaim/reclaim_test.go
agent can be set rp_filter to 0 for each node by default
Fixes #
> agent can be set rp_filter to 0 for each node

- cmd/coordinator/cmd/command_add.go
- docs/reference/spiderpool-agent.md
- pkg/networking/sysctl/sysctl.go
agent can be set rp_filter to 0 for each node by default.
Fixes #
> agent can be set rp_filter to 0 for the each node

- charts/spiderpool/crds/spiderpool.spidernet.io_spidermultusconfigs.yaml
- docs/reference/crd-spidermultusconfig.md
- docs/usage/spider-multus-config-zh_CN.md
- docs/usage/spider-multus-config.md
- pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/spidermultus_types.go
- pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/zz_generated.deepcopy.go
- pkg/multuscniconfig/multusconfig_informer.go
- pkg/multuscniconfig/multusconfig_mutate.go
- pkg/multuscniconfig/multusconfig_validate.go
- test/doc/spidermultus.md
- test/e2e/spidermultus/spidermultus_test.go
Add chainCNI support for spidermultusconfig, In this way, we use a plugin like `tuning` to help configure the kernel parameters of the pod.
Fixes https://github.com/spidernet-io/spiderpool/issues/3919
```
root@worker-node-1:/home/cyclinder/spiderpool/charts# cat test-chain-cni.yaml
apiVersion: spiderpool.spidernet.io/v2beta1
kind: SpiderMultusConfig
metadata:
name: test-chaincni
namespace: kube-system
spec:
cniType: macvlan
coordinator:
detectGateway: false
detectIPConflict: false
hostRPFilter: 1
hostRuleTable: 500
mode: auto
podDefaultRouteNIC: net1
podMACPrefix: ""
tunePodRoutes: true
txQueueLen: 0
disableIPAM: false
enableCoordinator: true
chainCNIJsonData: …
```
> Add chainCNI support for spidermultusconfig

- api/v1/agent/models/coordinator_config.go
- api/v1/agent/openapi.yaml
- api/v1/agent/server/embedded_spec.go
- cmd/coordinator/cmd/command_add.go
- cmd/coordinator/cmd/utils.go
- cmd/spiderpool-agent/cmd/coordinator.go
- docs/usage/install/overlay/get-started-calico-zh_cn.md
- docs/usage/install/overlay/get-started-calico.md
- docs/usage/install/overlay/get-started-cilium-zh_cn.md
- docs/usage/install/overlay/get-started-cilium.md
- pkg/networking/networking/ip.go
- pkg/networking/networking/route.go
- test/doc/coordinator.md
- test/e2e/coordinator/macvlan-overlay-one/macvlan_overlay_one_suite_test.go
- test/e2e/coordinator/macvlan-overlay-one/macvlan_overlay_one_test.go
- test/e2e/reclaim/reclaim_test.go
- test/scripts/debugEnv.sh
- release/bug 
- No longer rely on the API to get the rule number of the NIC, getting it through the API may cause the number to be wrong, which can avoid the wrong policy route when there is more than 1 secondary nics.
- New a netlink.Route object without use of raw object when adding the route, which can avoid netlink return "invalid argument" error.
Fixes https://github.com/spidernet-io/spiderpool/issues/3877
> coordinator: fix wrong policy route when there is more than 1 secondary nics

- api/v1/agent/models/coordinator_config.go
- api/v1/agent/openapi.yaml
- api/v1/agent/server/embedded_spec.go
- cmd/coordinator/cmd/command_add.go
- cmd/coordinator/cmd/utils.go
- cmd/spiderpool-agent/cmd/coordinator.go
- docs/usage/install/overlay/get-started-calico-zh_cn.md
- docs/usage/install/overlay/get-started-calico.md
- docs/usage/install/overlay/get-started-cilium-zh_cn.md
- docs/usage/install/overlay/get-started-cilium.md
- pkg/networking/networking/ip.go
- pkg/networking/networking/route.go
- test/doc/coordinator.md
- test/e2e/coordinator/macvlan-overlay-one/macvlan_overlay_one_suite_test.go
- test/e2e/coordinator/macvlan-overlay-one/macvlan_overlay_one_test.go
- test/scripts/debugEnv.sh
- release/bug 
Fixes https://github.com/spidernet-io/spiderpool/issues/3954
> coordinator: Fix error policy routing table when pod has multi nics

- charts/spiderpool/templates/configmap.yaml
- test/Makefile
- test/scripts/preCheckClusterReady.sh
- release/bug 
Fixes https://github.com/spidernet-io/spiderpool/issues/3987
> Fix：the chart value tuneSysctlConfig does not work

- cmd/spiderpool-agent/cmd/config.go
- cmd/spiderpool-agent/cmd/daemon.go
- cmd/spiderpool-controller/cmd/config.go
- cmd/spiderpool-controller/cmd/daemon.go
- go.mod
- go.sum
- vendor/go.uber.org/automaxprocs/LICENSE
- vendor/go.uber.org/automaxprocs/internal/cgroups/cgroup.go
- vendor/go.uber.org/automaxprocs/internal/cgroups/cgroups.go
- vendor/go.uber.org/automaxprocs/internal/cgroups/cgroups2.go
- vendor/go.uber.org/automaxprocs/internal/cgroups/doc.go
- vendor/go.uber.org/automaxprocs/internal/cgroups/errors.go
- vendor/go.uber.org/automaxprocs/internal/cgroups/mountpoint.go
- vendor/go.uber.org/automaxprocs/internal/cgroups/subsys.go
- vendor/go.uber.org/automaxprocs/internal/runtime/cpu_quota_linux.go
- vendor/go.uber.org/automaxprocs/internal/runtime/cpu_quota_unsupported.go
- vendor/go.uber.org/automaxprocs/internal/runtime/runtime.go
- vendor/go.uber.org/automaxprocs/maxprocs/maxprocs.go
- vendor/go.uber.org/automaxprocs/maxprocs/version.go
- vendor/modules.txt
fix https://github.com/spidernet-io/spiderpool/issues/3993, Update GOMAXPROCS configuration
- Replace manual GOMAXPROCS setting with maxprocs package for improved handling.
- Log a warning if setting GOMAXPROCS fails.
- Ensure min value is used when setting max procs from configuration.
> Update GOMAXPROCS configuration

- .github/workflows/e2e-init.yaml
- Makefile
- charts/spiderpool/templates/deleteHook.yaml
- charts/spiderpool/templates/role.yaml
- cmd/spiderpool-controller/cmd/clean.go
- pkg/constant/k8s.go
- pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/rbac.go
- pkg/k8s/utils/utils.go
- test/Makefile
- test/Makefile.defs
- test/scripts/debugEnv.sh
Fixes #3865
fix #3865 
在原本 clean 流程中，会去删除 sriovoperatorconfigs.sriovnetwork.openshift.io CRD，但当引入 sriovoperatorconfigs 后，如果该 CRD 被删除，helm uninstall sriovoperatorconfigs 会去清理 default 配置，但由于找不到对应的 CRD，从而导致 helm uninstall 失败。为了清理能够成功，能删除 sriov webhook、spiderpool-webhook等（避免再次安装spiderpool 失败），在 clean 中跳过 sriovoperatorconfigs.sriovnetwork.openshift.io CRD 不要删除它。
fix #3958 
在 pr #3880 中的 rbac 删除权限被移除了，导致 clean 删除 webhook 会失败，残留 webhook 会导致再次安装 spiderpool 失败
fix #3960 
在 https://github.com/spidernet-io/spiderpool/pull/3811 将 spiderpool-init 由 Pod 修改为 Job，并启用了 "helm.sh/hook": post-install 功能，但是该功能启用 ，job 运行完成后，它的默认删除机制是 "helm.sh/hook-delete-policy": before-hook-creation ， …
> fix: cannot uninstall spiderpool when sriovOperatorConfig is installed

- .github/workflows/auto-upgrade-ci.yaml
- .github/workflows/e2e-init.yaml
- Makefile
- test/Makefile
- test/scripts/debugEnv.sh
Fixes #4027 
cherry-pick https://github.com/spidernet-io/spiderpool/pull/3925，clean 是属于新功能，不需合入到 release-v0.8。
基于 https://github.com/spidernet-io/spiderpool/pull/3925 ，在 release-v0.8 上修改一些 CI 问题，如：
1. makefile 语法使用有误 -$(QUIET) make -C test uninstall_spiderpool，错误使用了 '-'，导致忽略了 uninstall_spiderpool 层级下的报错。
2. 明确 CI 卸载或者更新在哪一步失败了 ，调整 CI 结构
> cherry-pick some CI changes

- pkg/coordinatormanager/coordinator_validate.go
- pkg/multuscniconfig/multusconfig_mutate.go
- test/doc/spidermultus.md
- test/e2e/spidermultus/spidermultus_test.go
- release/bug 
Fixes https://github.com/spidernet-io/spiderpool/issues/4061
> Fix panic when create spidermultusconfig with nil podRPFilter in validate webhook

- pkg/ippoolmanager/ippool_manager.go
- test/e2e/reclaim/reclaim_test.go
Fixes #https://github.com/spidernet-io/spiderpool/issues/3771
SpiderIPPool's AllocatedIPCount statistics are aligned with SpiderSubnet, and some debug logs are added.
> Added debug log of AllocatedIPCount of ippool

- pkg/coordinatormanager/coordinator_validate.go
- test/doc/spidermultus.md
- test/e2e/spidermultus/spidermultus_test.go
- release/bug 
Fix wrong validate for unicast podMACPrefix when creating spiderMultusConfig
Fixes #
> Fix wrong validate for unicast podMACPrefix when creating spiderMultusConfig

- pkg/coordinatormanager/coordinator_validate.go
- pkg/multuscniconfig/multusconfig_mutate.go
- test/doc/spidermultus.md
- test/e2e/spidermultus/spidermultus_test.go
Fixes https://github.com/spidernet-io/spiderpool/issues/4077
> Fix panic  in validate webhook for creating spidermultusconfig

- test/scripts/install-default-cni.sh
Fixes #4125 
https://docs.cilium.io/en/v1.15/operations/upgrade/#helm-options
The tunnel option (deprecated in Cilium 1.14) has been removed. To enable native-routing mode, set routing-mode=native (previously tunnel=disabled). To configure the tunneling protocol, set tunnel-protocol=vxlan|geneve (previously tunnel=vxlan|geneve).
> fix cilium installation --set tunnel

- cmd/spiderpool-controller/cmd/clean.go
robot cherry pick PR <https://github.com/spidernet-io/spiderpool/pull/4130> from ty-dc,to branch release-v1.0,  action <https://github.com/spidernet-io/spiderpool/actions/runs/11247885218>  , commits 08f5cbdd34df9af161c2afc5bd1daf27cffbdfd2
> fix: avoid failures when cleaning up spiderpool resources due to resourceVersion conflicts.

- cmd/spiderpool-controller/cmd/clean.go
robot cherry pick PR <https://github.com/spidernet-io/spiderpool/pull/4156> from ty-dc,to branch release-v1.0,  action <https://github.com/spidernet-io/spiderpool/actions/runs/11285383726>  , commits 6a708dd9fa86f9bfeb629ad28ce1890403fdc984
> fix: optimize the cleanup code judgment of NotFound resources

- test/scripts/install-ovs.sh
robot cherry pick PR <https://github.com/spidernet-io/spiderpool/pull/4171> from ty-dc,to branch release-v0.9,  action <https://github.com/spidernet-io/spiderpool/actions/runs/11396118963>  , commits 59da75a69f83c91866e8c2851dd7129358431a46
> fix: Added retries to avoid openvswitch installation failures.

- cmd/spiderpool-controller/cmd/daemon.go
- pkg/multuscniconfig/multusconfig_validate.go
- pkg/multuscniconfig/multusconfig_webhook.go
- test/doc/spidermultus.md
- test/e2e/spidermultus/spidermultus_test.go
**Notice**:
"release/none"
"release/bug"
Fixes #4167
Fixed #4183
> fix: same-name conflict check specified by multus.spidernet.io/cr-name

- test/scripts/install-default-cni.sh
**Notice**:
"release/none"
"release/bug"
Fixes #4231 
spiderpool 尝试修改 felixconfigurations 的 chainInsertMode 为 true 适配 egressGateway。 但在 calico 最新版本中缺少 felixconfigurations 的 default 资源，故失败。
当前 e2e 没有 egressGateway 相关，暂时注释。
> e2e fix: the latest version of calico cannot find the felixconfigurations resource

- pkg/podmanager/utils.go
- pkg/podmanager/utils_test.go
- test/Makefile
**Notice**:
"release/none"
"release/bug"
Fixes https://github.com/spidernet-io/spiderpool/issues/4243
> Fix podwebhook cert don't update when spiderpool-controller restart

- cmd/spiderpool-agent/cmd/daemon.go
- cmd/spiderpool-controller/cmd/crd_manager.go
- cmd/spiderpool-init/cmd/client.go
- docs/concepts/arch-zh_CN.md
- docs/concepts/coordinator-zh_CN.md
- docs/concepts/coordinator.md
- docs/usage/network-topology-zh_CN.md
- docs/usage/network-topology.md
- docs/usage/route-zh_CN.md
- pkg/coordinatormanager/coordinator_validate.go
- pkg/gcmanager/scanAll_IPPool.go
- pkg/ip/cidr.go
- pkg/multuscniconfig/multusconfig_validate.go
**Notice**:
"release/none"
"release/bug"
Fixes #4203
> fix: scanAll typo

- charts/spiderpool/templates/servicemonitor.yaml
https://github.com/spidernet-io/spiderpool/blob/main/charts/spiderpool/templates/servicemonitor.yaml#L31
ServiceMonitor has dup key was `namespaceSelector `.
> Remove ServiceMonitor dup namespaceSelector

- .github/workflows/build-image-ci.yaml
- .github/workflows/e2e-init.yaml
- .github/workflows/trivy-scan-image.yaml
- Makefile
**Notice**:
"release/none"
"release/bug"
Fixes #
ref: https://github.com/spidernet-io/egressgateway/pull/1547
ref: https://github.com/spidernet-io/spiderpool/actions/runs/11824927030/job/32947826649?pr=4276
> Fix TOOMANYREQUESTS failure in Trivy Action

- test/scripts/install-ovs.sh
robot cherry pick PR <https://github.com/spidernet-io/spiderpool/pull/4293> from ty-dc,to branch release-v1.0,  action <https://github.com/spidernet-io/spiderpool/actions/runs/12047502529>  , commits e6ecafd64f99bf416b5b2e8385da191b0c2c192b
> fix: after the installation of openvswitch failed, retrying did not work.

- test/e2e/reclaim/reclaim_test.go
**Notice**:
"release/none"
"release/bug"
Fixes #4277 
1. 在重启工作节点后，新的 Pod 必须先运行，才会终结旧的 spiderpool-controller Pod，而由于端口占用的问题，新的 spiderpool-controller pod 永远不会 running，一直都是 Pending 的。故将 spiderpool-controller deploy 的 maxSurge 设置为 0 后，让 Pod 先终结在运行新的  spiderpool-controller Pod 。但是它会依次重启每一个副本 Pod，在用例原本逻辑中，只检查了 worker 节点上的 Pod webhook 。导致有概率出现 control-plane 上的 Pod 还没有 1/1，而是 0/1。影响其他 case 创建 Pod。
2. 优化 deferCleanup 和 BeforeEach，将一些代码顺序变更。
> fix: pod not-ready causes webhook call failure

- docs/usage/install/ai/get-started-macvlan-zh_CN.md
- docs/usage/install/ai/get-started-macvlan.md
- docs/usage/install/ai/get-started-sriov-zh_CN.md
- docs/usage/install/ai/get-started-sriov.md
**Notice**:
"release/none"
"release/bug"
Fixes #
> docs typo: annotations is incorrectly written as labels

- docs/usage/spider-affinity-zh_CN.md
- docs/usage/spider-affinity.md
Moved the code comments after the code block.
把代码注释放到代码段之后，也许更通用？
> [Docs] Update spider-affinity to relocate code comments

- pkg/ippoolmanager/ippool_manager.go
- test/doc/annotation.md
- test/e2e/annotation/annotation_test.go
**Notice**:
"release/none"
"release/bug"
Fixes https://github.com/spidernet-io/spiderpool/issues/4295
问题现象：
在 pod 使用 多 underlay 网卡时，若第一张网卡分配 IP 成功，第二张网卡因为ip不足而分配失败，会导致 pod 重启，而在重启后，第一张网卡会再次分配新的 ip .... 如此往复，会导致第一张网卡的 ip 池 ip 耗尽，同一个 Pod 的 UID 在池中被重复记录，导致该池资源被耗尽，无法为其他 Pod 提供地址分配。
```
kubectl get sp default-v4-ippool -ojsonpath={.status.allocatedIPs} | jq 
{
"172.18.40.10": {
"pod": "default/ippool-test-app-58b7766c7c-mvwpf",
"podUid": "4009cb83-bd17-4b08-92f0-2ea0cd3d64fc"
},
"172.18.40.11": {
"pod": "default/ippool-test-app-58b7766c7c-5jp5d",
"podUid": "4e57d4ee-fd3f-44fa-8c80-1db2c6ae0e98"
},
"172.18.40.12": {
"pod": "default/ippool-test-app-58b7766c7c-gw8hd",
"podUid": …
```
> Fix:  one NIC's IP pool shortage depleted IPs of other NICs in a multi-NIC setup.

- pkg/ipam/allocate.go
- pkg/ipam/utils.go
- pkg/ippoolmanager/ippool_manager.go
- pkg/workloadendpointmanager/workloadendpoint_manager.go
- pkg/workloadendpointmanager/workloadendpoint_manager_test.go
- test/doc/annotation.md
- test/doc/ippoolcr.md
- test/doc/spidercclaimparameter.md
- test/doc/spiderclaimparameter.md
- test/e2e/affinity/affinity_test.go
- test/e2e/annotation/annotation_test.go
**Notice**:
"release/none"
"release/bug"
Fixes #4362
```bash
Warning  FailedCreatePodSandBox  13s   kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "a0d4fe8eb1b4d9a115997df44488c4b297d5cb845234dd069f6db8decb282b98": plugin type="multus" name="multus-cni-network" failed (add): [default/test-sts-0/07793483-79f5-47ff-acdd-4a67d697ef85:macvlan-vlan100]: error adding container to network "macvlan-vlan100": spiderpool IP allocation error: [POST /ipam/ip][500] postIpamIpFailure  failed to retrieve the existing IP allocation: failed to update SpiderEndpoint allocation details NIC name net1, error: Operation cannot be fulfilled on …
```
> Fix: statefulSet applications failed to create in multi-NIC scenarios.

- pkg/ipam/allocate.go
- pkg/ipam/utils.go
- pkg/ippoolmanager/ippool_manager.go
- pkg/workloadendpointmanager/workloadendpoint_manager.go
- pkg/workloadendpointmanager/workloadendpoint_manager_test.go
- test/doc/annotation.md
- test/doc/ippoolcr.md
- test/doc/spidercclaimparameter.md
- test/doc/spiderclaimparameter.md
- test/e2e/affinity/affinity_test.go
- test/e2e/annotation/annotation_test.go
**Notice**:
"release/none"
"release/bug"
Fixes #4388 
> Fix:  fail to create statefulSet applications in multi-NIC scenarios.

- Makefile
- test/Makefile
- test/Makefile.defs
- test/scripts/install-ovs.sh
**Notice**:
"release/none"
"release/bug"
Fixes https://github.com/spidernet-io/spiderpool/issues/4396
Fixes https://github.com/spidernet-io/spiderpool/issues/4397
1. openkruise 1.7.3 安装失败，临时回退到 1.7.2
2. auto-nightly-ci , auto-pr-ci 使用 ubuntu-latest systemd start openvswitch 失败，临时回退到 ubuntu-22.04。待成功后恢复为 24.04
> e2e: fix openkruise installtion and debug ovs installtion

- .github/workflows/auto-upgrade-ci.yaml
- .github/workflows/auto-version-release.yaml
- .github/workflows/build-image-base.yaml
- .github/workflows/build-image-ci.yaml
- .github/workflows/build-image-plugins.yaml
- .github/workflows/call-release-changelog.yaml
- .github/workflows/call-release-chart.yaml
- .github/workflows/call-release-doc.yaml
- .github/workflows/call-update-githubpages.yaml
- .github/workflows/e2e-init.yaml
- .github/workflows/trivy-scan-image.yaml
**Notice**:
"release/none"
"release/bug"
Fixes #
https://github.com/spidernet-io/spiderpool/actions/runs/12490834656/job/34856097904?pr=4393
> Github Action: Fix fail to download artifact

- .github/workflows/auto-upgrade-ci.yaml
- .github/workflows/build-image-ci.yaml
- .github/workflows/build-image-plugins.yaml
- .github/workflows/call-release-changelog.yaml
- .github/workflows/call-release-doc.yaml
- .github/workflows/trivy-scan-image.yaml
**Notice**:
"release/none"
"release/bug"
Fixes #
https://github.com/spidernet-io/spiderpool/actions/runs/12494179476/job/34863564883?pr=4393
> CI: use merge-multiple for download-artifact

- .github/workflows/trivy-scan-image.yaml
- cmd/coordinator/cmd/cni_types.go
- cmd/coordinator/cmd/command_add.go
- docs/concepts/coordinator-zh_CN.md
- docs/concepts/coordinator.md
- test/e2e/coordinator/macvlan-overlay-one/macvlan_overlay_one_test.go
Detect IP conflicts before gateway detection to  fix gateway detection could potentially update the arp table causing communication fail
**Notice**:
"release/none"
"release/bug"
Fixes https://github.com/spidernet-io/spiderpool/issues/4475
> Detect IP conflicts before gateway detection to fix communication fail

- cmd/coordinator/cmd/cni_types.go
- cmd/coordinator/cmd/command_add.go
- docs/concepts/coordinator-zh_CN.md
- docs/concepts/coordinator.md
- test/e2e/coordinator/macvlan-overlay-one/macvlan_overlay_one_test.go
Detect IP conflicts before gateway detection to fix gateway detection could potentially update the arp table causing communication fail
**Notice**:
"release/none"
"release/bug"
Fixes https://github.com/spidernet-io/spiderpool/issues/4484
> Detecting IP conflicts takes place before gateway detection, avoiding communication failure

- .github/workflows/update-chart-readme.yml
**Notice**:
"release/none"
"release/bug"
Fixes #
> CI: fix upload charts artifact

- pkg/ippoolmanager/ippool_manager.go
**Notice**:
"release/none"
"release/bug"
Fixes #
> optimize the amount  of ip usage 

- test/scripts/install-default-cni.sh
**Notice**:
"release/none"
"release/bug"
Fixes https://github.com/spidernet-io/spiderpool/issues/4634
https://github.com/cilium/cilium/pull/37436 will fix it. Before that happens, we have a workaround to fix it.
> CI: fix cilium multiPoolPreAllocation installtion

- cmd/spiderpool/cmd/command_add.go
- pkg/networking/networking/packet.go
**Notice**:
"release/none"
"release/bug"
Fixes https://github.com/spidernet-io/spiderpool/issues/4650
正常情况下，IPAM 分配 IP 给 CNI， CNI 将 IP 地址配置到网卡之后，最后设置状态为 UP。当网卡的链路地址改变或状态改变时，内核会发送免费 ARP，宣告其地址。
https://github.com/spidernet-io/spiderpool/pull/4588 为了修复检测失败时因为错误的 ARP 缓存表导致通信失败，在 IPAM 执行冲突检测。这会提前将网卡 UP，执行完冲突检测之后，返回 IP 地址给 CNI，CNI 将地址配置到网卡，最 后UP 网卡的时候，网卡已经是 UP 的状态，所以这不会触发内核发送免费 ARP 通告其地址。这会导致当 Pod 以相同的 IP 重启后，与其通信过的其他主机不会主动更新 ARP 缓存表导致通信失败。
此 PR 通过在 IPAM 做完冲突检测之后，将网卡的状态设置为 Down，以便 CNI 可以在 UP 网卡时触发免费ARP。
Normally, IPAM assigns IP to the CNI, and the CNI configures the IP address to the NIC before finally setting the status to UP. the kernel sends a free ARP announcing the address of the NIC when its link …
> Ensure kernel sends GARPs to avoid communication failures

- docs/example/qos/rdma-qos.sh
- docs/usage/install/ai/get-started-macvlan-zh_CN.md
- docs/usage/install/ai/get-started-macvlan.md
- docs/usage/install/ai/get-started-sriov-zh_CN.md
- docs/usage/install/ai/get-started-sriov.md
- docs/usage/roce-qos-zh_CN.md
- docs/usage/roce-qos.md
- docs/usage/spider-multus-config-zh_CN.md
- docs/usage/spider-multus-config.md
**Notice**:
"release/none"
"release/bug"
Fixes #
> Docs: add mtu size configuration and RDMA QoS

- charts/spiderpool/crds/spiderpool.spidernet.io_spidermultusconfigs.yaml
- docs/reference/crd-spidermultusconfig.md
- pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/spidermultus_types.go
- pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/zz_generated.deepcopy.go
- pkg/multuscniconfig/multusconfig_informer.go
- pkg/multuscniconfig/multusconfig_mutate.go
- pkg/multuscniconfig/multusconfig_validate.go
- pkg/multuscniconfig/utils.go
- test/doc/spidermultus.md
- test/e2e/spidermultus/spidermultus_test.go
**Notice**:
"release/none"
"release/bug"
Fixes https://github.com/spidernet-io/spiderpool/issues/4422
SpiderMultusConfig: Add mtu size support for macvlan and ipvlan
> SpiderMultusConfig: Add mtu size support for macvlan / ipvlan / sriov

- charts/spiderpool/files/grafana-rdma-cluster.json
- charts/spiderpool/files/grafana-rdma-node.json
- charts/spiderpool/files/grafana-rdma-pod.json
- charts/spiderpool/files/grafana-rdma-workload.json
一些描述需要精简，避免冗长
需要体现 400g bandwidth 等信息，错开使用 throughout 的关键字
标题的首字母 大写
一些语法问题
> chart: optimize rdma titles

- pkg/gcmanager/scanAll_IPPool.go
robot cherry pick PR <https://github.com/spidernet-io/spiderpool/pull/4729> from weizhoublue,to branch release-v1.0,  action <https://github.com/spidernet-io/spiderpool/actions/runs/13778567019>  , commits 1f0cb696daca74ccf923e81d67068e462396efc4
> fix: retrieve the endpoint for deleted stateless pod

- pkg/gcmanager/pod_cache.go
- pkg/gcmanager/scanAll_IPPool.go
This PR fixes an issue: When users set the spiderpool-agent variable `EnableGCStatelessTerminatingPodOn(Not)ReadyNode` to false, Spiderpool still performs garbage collection on stateless applications that have been deleted and exceeded the maximum deletion timeout period.
**Notice**:
"release/none"
"release/bug"
Fixes #
> IPAM fix: ENV EnableGCStatelessTerminatingPod(Not)ReadyNode=false does not work

- pkg/gcmanager/pod_cache.go
- pkg/gcmanager/scanAll_IPPool.go
robot cherry pick PR <https://github.com/spidernet-io/spiderpool/pull/4784> from cyclinder,to branch release-v1.0,  action <https://github.com/spidernet-io/spiderpool/actions/runs/14326483526>  , commits 97f19cf9601af16b7db01a88daa857fa1c26121c
> Fix ENV EnableGCStatelessTerminatingPod(Not)ReadyNode doesn't works

- charts/spiderpool/README.md
- charts/spiderpool/templates/deployment.yaml
- charts/spiderpool/values.yaml
- cmd/spiderpool-controller/cmd/config.go
- docs/concepts/ipam-des-zh_CN.md
- docs/concepts/ipam-des.md
- docs/reference/spiderpool-controller.md
- pkg/gcmanager/gc_manager.go
- pkg/gcmanager/scanAll_IPPool.go
**Notice**:
"release/none"
"release/bug"
Fixes https://github.com/spidernet-io/spiderpool/issues/4888
- 提供环境变量：`SPIDERPOOL_GC_ENABLE_STATELESS_RUNNING_POD_ON_EMPTY_POD_STATUS_IPS`，默认为 false，意味不会 GC 调那些 status.podIPs 为空但 Running 的 Pod。当设置为 true, 则会 GC。
- Provide environment variable:  `SPIDERPOOL_GC_ENABLE_STATELESS_RUNNING_POD_ON_EMPTY_POD_STATUS_IPS`, default is false, meaning it will not GC pods that are Running but have empty status.podIPs. When set to true, it will GC these pods.
This configuration controls Spiderpool's Pod GC strategy:
When false (default): Spiderpool will not GC pods that are Running but have empty status.podIPs
When true: Spiderpool will GC these pods
This feature is used to …
> ipam: add GC option for running pods with empty podIPs

- charts/spiderpool/templates/daemonset.yaml
- cmd/spiderpool-agent/cmd/config.go
- cmd/spiderpool-agent/cmd/metrics_server.go
- pkg/constant/k8s.go
- pkg/podownercache/pod_owner_cache.go
- pkg/podownercache/pod_owner_cache_test.go
robot cherry pick PR <https://github.com/spidernet-io/spiderpool/pull/4881> from cyclinder,to branch release-v1.0,  action <https://github.com/spidernet-io/spiderpool/actions/runs/15151774569>  , commits 8d94cf625f198745c6cd84ca7a3775c9087b3f34
> Add node name filter for pod owner cache to track local pods only

- pkg/rdmametrics/ethtool/ethtool.go
**Notice**:
"release/none"
"release/bug"
Fix metrics miss data from ethtool #4899
会统计 vport unicast/multicast packets 等信息，这部分信息缺失导致有些面板无数据。
```
rx_vport_broadcast_bytes: 22680
tx_vport_broadcast_packets: 4
tx_vport_broadcast_bytes: 240
rx_vport_rdma_unicast_packets: 784938807
rx_vport_rdma_unicast_bytes: 834059487938
tx_vport_rdma_unicast_packets: 969440866
tx_vport_rdma_unicast_bytes: 1032643415900
rx_vport_rdma_multicast_packets: 0
rx_vport_rdma_multicast_bytes: 0
tx_vport_rdma_multicast_packets: 0
tx_vport_rdma_multicast_bytes: 0
```
> Fix metrics miss vport data from ethtool

- charts/spiderpool/README.md
- charts/spiderpool/templates/configmap.yaml
- charts/spiderpool/values.yaml
- cmd/spiderpool-controller/cmd/daemon.go
- docs/concepts/ipam-des-zh_CN.md
- docs/concepts/ipam-des.md
- pkg/gcmanager/gc_manager.go
- pkg/gcmanager/scanAll_IPPool.go
- pkg/gcmanager/tracePod_worker.go
- pkg/ipam/allocate.go
- pkg/types/k8s.go
- pkg/workloadendpointmanager/workloadendpoint_manager.go
- test/Makefile
- test/e2e/annotation/annotation_test.go
**Notice**:
"release/none"
"release/bug"
Fixes https://github.com/spidernet-io/spiderpool/issues/4916
本 PR 主要涉及以下两个改动：
1. 修复 endpoint 残留导致 新 Pod 无法启动的问题。
- 对于无状态应用，分配 IP 时检查 Pod 其 endpoint 是否 uid 一致，不一致则清理掉 endpoint。有状态应用无改动。
- 如果 Pod 已经超过最大优雅删除时间，可能其 IP 资源已经通过 CNI Del 回收。在之前 GC 不会处理这种情况，该 PR 为了保障一些极端情况下 endpoint 不会回收，通过 trace_worker 中将 与 pod  uuid 不一致的 endpoint 清理掉。
- 在全局 GC 提供定时清理那些 Pod 已经不存在的 endpoint. 该功能可通过一个 flag 决定是否开启
2. 修复可能存在 endpoint 被清理导致丢失的问题。
- 在分配 IP时，如果不能复用 IP 分配，并且 endpoint 存在并且其 uuid 和 pod 不一致的情况下，endpoint 资源对象可能已经在之前步骤中被删除，此时需要置 endpoint 为 nil,确保 后续会创建一个新的 endpoint，而不会出现 endpoint 丢失的情况。
This PR mainly involves the following two changes:
Fix the issue where residual endpoints …
> Remove outdated endpoints to prevent blocking the creation of new Pods

- .github/workflows/auto-update-authors.yaml
- .github/workflows/update-cniplugins-version.yaml
- .github/workflows/update-golang-version.yaml
当前GitHub Actions在更新CNI插件版本、Golang版本和作者信息时，会创建多个具有相同标题的PR，导致PR列表中出现重复项。
为以下三个workflow添加了在创建新PR之前关闭相同标题现有PR的功能：
1. `.github/workflows/update-cniplugins-version.yaml` - 处理CNI插件版本更新
2. `.github/workflows/update-golang-version.yaml` - 处理Golang版本更新  
3. `.github/workflows/auto-update-authors.yaml` - 处理作者信息更新
每个workflow都新增了一个步骤：
- **步骤名称**: "Close existing PRs with same title"
- **执行时机**: 仅在检测到需要更新时执行
- **功能**: 
- 使用GitHub API查询具有相同标题的开放PR
- 对每个找到的PR添加关闭评论
- 将PR状态设置为closed
- 使用适当的权限token（GITHUB_TOKEN或WELAN_PAT）
- 每个标题类型只会保留最新的一个开放PR
- 旧的PR会被优雅关闭并附带说明
- 减少PR列表中的重复项，提高维护效率
- 保持原有功能不变，只是优化了PR管理
- 所有修改的YAML文件都通过了语法验证
- 保持了原有workflow的功能完整性
- 新增的API调用遵循GitHub最佳实践
这个优化将显著减少重复PR的数量，使维护工作更加高效。
> Optimize GitHub Actions to prevent duplicate PRs
